### ISSUE TITLE
Gherkin feature is case sensitive

### ISSUE THREAD

**Issue by sheldonhull** [pester/Pester#1010]
## 1. Provide a general summary of the issue in the Title above

I had issues executing with Invoke-Gherkin despite simplifying the format to exactly the same as all the examples. Once I changed the text from the example below to normal case the steps correctly executed. 

```
Scenario: The test environment is setup successfully
GIVEN the test environment is setup successfully
AND the module is imported
```

to 
```
Scenario: The test environment is setup successfully
Given the test environment is setup successfully
And the module is imported
```

## 2. Describe Your Environment

Operating System, Pester version and PowerShell version:

Pester version     : 4.3.1 C:\Program Files\WindowsPowerShell\Modules\Pester\4.3.1\Pester.psm1
PowerShell version : 5.1.15063.966
OS version         : Microsoft Windows NT 10.0.15063.0

## 3. Expected Behavior

Case sensitivity should be removed allowing GIVEN, Given, given, or any combination of characters to matching the steps in PS1 file. 

## 4.Current Behavior
Fails to match the step to the gherkin text based description.

also tested matching the upper case example in steps, but this didn't make a difference. Must be specific to the feature file parsing. 
```

## 5. Possible Solution

remove case sensitive in parsing. 
I reviewed the code for Invoke-Gherkin step parsing here: https://github.com/pester/Pester/blob/master/Functions/Gherkin.ps1#L614

As a quick test I changed the regex and matched the step text by using: 

```regex
(?<=(?:Given|When|Then|And|But)\s+).*
```

I think the first issue is the requirement with `^` to be the start of the line, when there might be whitespace to ignore such as indented steps under the scenario. 
I'll look again later if no updates, but figured that might help

**Comment by nohwnd** [comment]
@Jaykul could you have a look, please?

**Comment by Jaykul** [comment]
The Gherkin syntax _is_ case sensitive. I don't think we have enough documentation about Gherkin syntax, really, but that's partly because we expect people to refer to [their documentation](https://github.com/cucumber/cucumber/wiki/Gherkin)

We are using the official multi-lingual gherkin parser for .net (provided by the cucumber organization who came up with the idea). If we have examples in caps, we should fix those examples -- which examples are they?

That is to say, this syntax is not actually valid Gherkin syntax (you can see that even github's highlighter knows this):

```gherkin
Scenario: The test environment is setup successfully
  GIVEN the test environment is setup successfully
  AND the module is imported
```

You have to write sentence case to get valid Gherkin syntax:

```gherkin
Scenario: The test environment is setup successfully
  Given the test environment is setup successfully
  And the module is imported
````

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
