### ISSUE TITLE
Add alias without .exe when mocking external command

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1043]
## 1. Provide a general summary of the issue in the Title above

Running a test like this: 

```powershell
Describe "-" {
    It "-" {
        Mock Notepad { Write-Host "I am a mock" }
        notepad
    }
}
```
Will result in notepad being executed because `notepad` will resolve into `notepad.exe` command, but Mock will not pick it up since there is no alias for `notepad`. This is counter-intuitive and currently there is no good way of mocking executables without wrapping them into functions, which is especially painful now that powershell is multiplatform and we usually want to call the executable without explicitly specifying the extension (think `git`).

## 2. Describe Your Environment

Pester version     : 4.3.1 4.2.0 C:\Program Files\WindowsPowerShell\Modules\Pester\4.3.1\Pester.psd1 C:\Program Files\WindowsPowerShell\Modules\Pester\4.2.0\Pester.psd1
PowerShell version : 5.1.16299.248
OS version         : Microsoft Windows NT 10.0.16299.0

## 3. Expected Behavior

Mock should pickup the call to notepad even though the underlying command is notepad.exe.

## 4.Current Behavior

The executable is executed.

## 5. Possible Solution

Add alias without extension to the mock.

**Comment by it-praktyk** [comment]
What about using `Get-Command`?
Similar like [here](https://github.com/pester/Pester/blob/5796c95e4d6ff5528b8e14865e3f25e40f01bd65/Pester.Tests.ps1#L32)

**Comment by nohwnd** [comment]
@it-praktyk I am not sure how that helps. Could you expand on it, please?

**Comment by mklement0** [comment]
It's obviously not a proper solution, but simply defining an _empty_ function _in addition_ to the `Mock` is a quick workaround for now:

```powershell
Describe "-" {
    # Dummy function to make the Mock of the same name work.
    function Notepad { } 
    It "-" {
        Mock Notepad { Write-Host "I am a mock" }
        notepad
    }
}
```

**Comment by mklement0** [comment]
@nohwnd:

Here's what I _think_ you're proposing, but just to spell it out (do correct me if I'm wrong):

* Whenever the `<name>` in a  `Mock [-CommandName] <name>` call resolves to an _external application_, implicitly create a `<name>.exe` alias for it _on Windows_, so that both `<name>` and `<name>.exe` invocations are covered by the mock.

* Windows-only code benefits by the `Mock` now automatically covering invocations with and without `*.exe`.

* Cross-platform-aware code benefits by deliberately extension-less invocations (e.g., `git`) now being covered by an extension-less `Mock` (e.g., `Mock git ...`) on Windows too.

**Comment by nohwnd** [comment]
Marked this as Help wanted. The above description is accurate. We just need to define more aliases for the mock. This is potentially breaking change, but hopefully not.

**Comment by renehernandez** [comment]
@nohwnd I am going to start taking a look at this, since it is inline with previous work in aliasing that I have done in Pester

**Comment by nohwnd** [comment]
@renehernandez great! :)

**Comment by renehernandez** [comment]
@nohwnd Based on the implementation and the tests that I am adding in #1252, it doesn't seem to be a breaking change

**Comment by nohwnd** [comment]
@renehernandez do you think that because our tests don't fail? :)

**Comment by renehernandez** [comment]
@nohwnd Part due to that :), because with enough test coverage, any changes that do not break your tests nor require you to change the tests, aren't breaking the public contract of the code. Although, I guess it depends on the definition of breaking changes and how much code coverage the code has :)

And also because I added tests that verified that external commands can be properly mocked in different situations

If you have any user case that I am missing, let me know and I can add it as a test
