### ISSUE TITLE
Skip tests with global test suppression

### ISSUE THREAD

**Issue by claudiospizzi** [pester/Pester#1048]
## 1. Provide a general summary of the issue in the Title above

In our environment, we use Pester for infrastructure tests. We have up to 1000 tests and run these tests against hundreds of servers. The tests themself are quite smart, and will, for example only be executed if a specific features is installed on the target. This will anyway give us a lot of test results. But sometimes, we get some false negative test results, because a special server requires a different configuration than all others.

We would like to have the option to skip this tests with a global test suppression list. Especially we use the test case feature of the It-blocks a lot. Using the -Skip parameter is not an option.

## 2. Describe Your Environment

OS: Windows 10, Windows Server 2012 R2 and later
Pester: Latest
PowerShell: 5.1

```powershell
# Idea: Function to set the global test suppresion.
Add-PesterSuppression -Describe 'SRV-02' -Context 'Windows', 'Roles' -It "Should have installed 'Windows-Server-Backup' feature"

$computers = 'SRV-01', 'SRV-02'

foreach ($computer in $computers)
{
    Describe $computer {

        Context 'Windows' {

            Context 'Roles' {

                $testCases = @(
                    @{ Name = 'Telnet-Client' },
                    @{ Name = 'Windows-Server-Backup' }
                )

                It 'Should have installed <Name> feature' -TestCases $testCases {

                    param ($Name)

                    # Act
                    $feature = Get-WindowsFeature -ComputerName $computer -Name $Name

                    # Assert 
                    $feature.InstallState | Should -Be 'Installed'
                }
            }
        }
    }
}
```

Expected output:
![pester](https://user-images.githubusercontent.com/1934246/40125620-a1293e4c-592b-11e8-9e7d-9a0b7f647943.png)

## 3. Possible Solution

*Part 1*
Adding a new function to set global suppressions. This can e.g. add an element to s module wide variable like `$Script:TestSuppression`. We could also expand that with Get and Clear functions.
```powershell
Add-PesterSuppression [[-Script] <String>] [-Group] <String[]> [-It] <String>
Get-PesterSuppression
Clear-PesterSuppression
```

*Part 2*
Patch the internal Pester function `Invoke-Test` to skip a test, if the "describe", "context" and "it" of the executing test matches with one of the specified suppression's.

I'll provide a PR, if this idea is okay for the maintainers.

**Comment by claudiospizzi** [comment]
Even without feedback to my idea, I've created the proof of concept in this branch:
https://github.com/claudiospizzi/Pester/tree/GlobalSuppression

**Comment by it-praktyk** [comment]
@claudiospizzi, my first impression is that it's a great idea. I'll try to review it soon.

**Comment by claudiospizzi** [comment]
@it-praktyk May I create the PR already, so that you can review it easier?

**Comment by it-praktyk** [comment]
Yes, please :-) Any constructive pull requests are welcomed.

**Comment by claudiospizzi** [comment]
@it-praktyk Pull request created. I'm locking forward to your review.

**Comment by nohwnd** [comment]
Sorry for the long silence, I was taking a little break from Pester. In general this is a nice idea, but this does not work in the expected way for the majority of tests out there. People love to put their code outside of the blocks controlled by Pester, and that is  just one of the reasons why we don't have Tags on inner level Describes and Its. All the Pester blocks simply execute code and then synchronize on one central state object. This gives a lot of flexibility, but prevents us from knowing which tests we have and which setups need to be executed for them. This also means that we cannot guarantee that code that is not needed to be run won't be run. Say you run a setup that takes 10s only to realize that no It block will actually execute, because none will pass the filter. 

This could be improved but we would need to change how Pester is executed, and especially how Pester is used. (In theory we could run the tests in first pass without executing anyting to build the test tree, from that we could determine what will be run and execute it in a second pass. But to do that all the test code needs to be controlled by Pester. )

**Comment by claudiospizzi** [comment]
Hi @nohwnd 
Yes, you are right, depending on the test structure, some code may be executed, even if the test itself will be suppressed. I guess, my idea is appropriate for infrastructure testing, but not so much for unit testing. Generally I see it like this:
- Infrastructure testing: The same test will be executed multiple times against multiple targets. If we have to suppress one target, the -Skip suppression will not work in this use case, but my proposal will do the work.
- Unit testing: The same test normally is only executed once, to verify the code. The -Skip parameter on It blocks will do the work. In addition, for unit tests, I think normally as few as possible tests should have to be skipped.

I see, this proposal is not perfect. But can you still consider merging it? I think for everyone using Pester to execute infrastructure tests, this will be convenient.

**Comment by nohwnd** [comment]
Been thinking about this over the weekend again, and I think that your core idea is good, but I don't like the fact that we would add three new cmdlets just to manage a collection of suppressions somewhere in our inner state. To me a better way to do this would be to provide `-TestPath` parameter to `Invoke-Pester` that would filter out the tests that do not fit this path. This also allows us to take the `-PassThru` result, easily list all the tests that were executed, and reduce / repeat the same run.

I really like the `-like` wildcards that make this really useful for your purpose, and would also be useful for running subset of tests without tagging them.

There are some limitations though: 
- the splitter we are using for the test path is `\` which is a quite common character and can easily get in conflict. I think that you chose this character because we are using it in the `-PassThru` object, and we cannot change it because that would be a breaking change for the output. To solve the filtering more robustly, I would add a `TestTree` property to the object that would represent the test run more accurately, without having to comply with the historic format of `TestResults`. But it would also be more difficult to travers (like when you query TestResults for all failed tests), so I would keep both properties. This does not have to be part of an initial concept though. 

- There should be a guideline that suggests putting all dependencies in blocks controlled by Pester, which would allow us to do the least amount of work executing the blocks, but the scoping on the describe, beforeAll needs to be fixed, and described. At the moment the code executed within Describe is dot sourced to it's parent scope, meaning that any definitions from first Describe would leak to all subsequent describes in the file. Solution to that is adding one more scope above the execution. A solution for that is proposed in #518 

- If people decide to follow the guideline (or don't care about running some code more than necessary), we can also introduce `Discover-Pester` function that would list all tests without executing. This can be done by replacing Describe and Context by implementations that collect the paths, and It by empty implementation (BeforeAll, BeforeEach, AfterEach, AfterAll already do nothing, we execute them differently). `Discover-Pester` would produce the same kind of output as the `TestTree` described above.

I know that some of this is quite tangiental to your original proposal, but I mostly wanted to sum it up, because there are quite a few other linked issues that could be solved by this. You don't need to implement any of this, but an opinion would be welcome 🙂 

#721 - allowing single test to run 
#518 - beforeAll scoping leaks definitions
#335 - running only failed tests
#1097 - nested afterAll are not called

**Comment by claudiospizzi** [comment]
You are right, 3 cmdlets for this feature are quite a lot. I like your idea to use a test path parameter for `Invoke-Pester`. May I suggest an optimization: Can we think about 2 parameters, as `-IncludeTestPath` and `-ExcludeTestPath`? Both parameter should be arrays, so that we can include or exclude multiple patterns the same time. My idea behind this is, that if I have hundreds of tests with various names and want to exclude just one, this will be hard to achieve with just an "include" filter.

The two parameters should behave like this:
- Neither `-IncludeTestPath` nor `-ExcludeTestPath` are specified: All tests will be executed
- Only the `-IncludeTestPath` parameter is used: Only tests matching the include test path will be executed
- Only the `-ExcludeTestPath` parameter is used: Only test not matching the exclude test path will be executed
- Both parameter are used: All tests matching the include test path but in addition don't match the exclude tests path are executed

For the `-PassThru` option, maybe we can also pass the skipped or suppressed tests with the test result as Skipped or Suppressed. That would be important for our case, to have statistics how many tests were skipped. And it's easy to filter them to reduce / repeat the same run.

I don't completely get your opinion to the test path. I understand, that the splitter `\` is not the best solutions, right? What would be your proposal for the pattern or schema of this parameters? Maybe just use `/` or a completely different concept? From my point of view, a `\` or `/` is easy to use and they do not interfere with the `-like` for the filtering, like this:

```powershell
Invoke-Pester -ExcludTestPath "SRV-02/Windows/Roles/Should have installed '*' feature"
```

Generally, I'm open to other solutions. I just published the PR https://github.com/pester/Pester/pull/1057 because in the meanwhile, we use it already in production, to suppress tests for our infrastructure testing. But we would be happy to switch to a global solution for the suppression, even if we have to change, how we call it.

**Comment by nohwnd** [comment]
- `-ExcludeTestPath` yes that is a good idea, we have the same thing for tags and it has the same behavior.
- Slash is fine for a simple filters that you provide by hand, as long as there are no slashes in your test names. But to make this useful also for programatically repeating the tests (e.g. on a build server, or via a plugin for VSCode) I would like to get rid of that ambiguity and use arrays instead.

- I also forgot about one aspect, which is limiting the file paths, in which the filters would apply. I think I might be overcomplicating it a bit.

**Comment by claudiospizzi** [comment]
I see, slash is a bit problematic in combination with file paths. Arrays are the better solution to be precise. It's just, if we want to allow multiple test paths to include or exclude, we need a multidimensional (jagged) array as parameter, e.g. like this:

```powershell
[Parameter(Mandatory = $true)]
[System.String[][]]
$ExcludeTestPath
```

It will be a bit tricky to parse the parameters, especially, if only one path is specified, like the following example, two time the same type input, but once to exclude SRV-01/Windows and once to exclude both Describe blocks for the computers:

```powershell
Invoke-Pester -ExcludeTestPath 'SRV-01', 'Windows'
Invoke-Pester -ExcludeTestPath 'SRV-01', 'SRV-02'
```

Maybe this notation will be required for the first option:

```powershell
Invoke-Pester -ExcludeTestPath (, ('SRV-01', 'Windows'))
```

**Comment by dlwyatt** [comment]
That syntax is ugly as sin, let's not do it that way.  :)

**Comment by claudiospizzi** [comment]
Maybe we can switch to a hash table array `[System.Collections.Hashtable[]]` for the test path parameter. The hash table could be populated with describe, context and it blocks, matching the path to the test. Maybe something like this:

```powershell
Invoke-Pester -ExcludeTestPath @{ Describe = 'SRV-02'; Context = 'Windows' }
Invoke-Pester -ExcludeTestPath @{ Describe = 'SRV-01' }, @{ Describe = 'SRV-02' }
```

**Comment by nohwnd** [comment]
Moving this to 5.x, this is generally possible now, the internal paths are now distinct strings, joining them with `\` should make them good enough for filtering by the user, filtering by a tool can use file paths and locations to make it clear what it means.
