### ISSUE TITLE
Document integration with AppVeyor Ubuntu build

### ISSUE THREAD

**Issue by iricigor** [pester/Pester#1050]
AppVeyor now supports running tests also on Ubuntu / PowerShell core. It should be documented in Readme / Build server integration section ([link](https://github.com/pester/Pester#build-server-integration)). Planets example is already updated and tested ([link](https://ci.appveyor.com/project/nohwnd/planets)).

A couple of consequences to that:
1. It requires specifying an additional image (Ubuntu)
2. The previous point implies we cannot use Chocolatey anymore :( , it should be replaced with `Install-Module`
3. The previous point implies we cannot use WMF image, we should use VS 2017

**Comment by it-praktyk** [comment]
@iricigor, please feel free to propose an update. Thank you.

**Comment by nohwnd** [comment]
@iricigor yeah that is fine, the example in the readme is there to show how easy it is to use Pester in appveyor, the main concern is to keep the config really short and easy to comprehend, which it still it. Choco was used only because installing Pester via Install-Module required enabling nuget first etc. and that was too long, from your config it seems that that step is no longer necessary so using the PowerShell way of installing module is preferable.

**Comment by iricigor** [comment]
Yeap, I know/agree with your comments. As you mentioned, the new config file (visible [in my fork](https://github.com/iricigor/Pester#build-server-integration)) is still compact. I believe one additional line is worth for the new functionality AppVeyor provided. Though true is not all need that functionality yet.

**Comment by nohwnd** [comment]
This was merged.
