### ISSUE TITLE
When mocking Get-CimInstance -filter switch doesn't filter

### ISSUE THREAD

**Issue by ginobrewski** [pester/Pester#1055]
## 1. Provide a general summary of the issue in the Title above
When developing a function that uses Get-CimInstance I find that using -filter works with a real server, but when I try to do a mock of a machine the filter switch does not work, but the mock will work when the function uses Where-Object on the pipeline as a filter instead.

## 2. Describe Your Environment
Pester version     : 4.3.1 3.4.0 C:\Program Files\WindowsPowerShell\Modules\pester\4.3.1\Pester.psm1 C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Pester.psm1

PowerShell version : 5.1.16299.431
OS version         : Microsoft Windows NT 10.0.16299.0
## 3. Expected Behavior
Expect the given function to return two devices out of three from a filter on device type.

## 4.Current Behavior
The test returns three devices since the third drive is not being filtered with the -filter switch. If the Where-object is traded out for the filter the code will work as expected. Learning some best practice seems putting a filter in the stream instead of passing to a where-object function would be more efficient use of code.

For example the function contains this code:
```
$vol = Get-CimInstance -ClassName win32_volume -ComputerName $Computer -Filter "DriveType=3" # | Where-object "DriveType=3"
foreach($disk in $vol){
                $props = @{
                    'ComputerName'=$computer;
                    'FreeSpace'="{0:N2}" -f ($disk.FreeSpace/1GB);
                    'Drive'=$disk.Name;
                    'Size'="{0:N2}" -f ($disk.Capacity/1GB);
                }
            New-Object -TypeName psobject -property $props
```
Testing code:
```
Describe "Get-VolumeInfo" {
    mock Get-CimInstance {
        @([pscustomobject]@{
            Name='c:\';
            Capacity=161061269504;
            FreeSpace=92794884096;
            DriveType=3;
        },
        [pscustomobject]@{
            Name='d:\';
            Capacity=161061269504;
            FreeSpace=92794884096;
            DriveType=3;
        },
        [pscustomobject]@{
            Name='s:\';
            Capacity=0.10;
            FreeSpace=0.10;
            DriveType=5;
        })    } -ParameterFilter {$classname -ieq 'win32_volume'}
     It "volume information single server multiple drives" {
        $result = get-volumeInfo -computername RemoteComputerName
        $result.count | should be 2
        $result[0] | should be "@{FreeSpace=86.42; Drive=C:\; ComputerName=RemoteComputerName; Size=150.00}"
        $result[1] | should be "@{FreeSpace=86.42; Drive=d:\; ComputerName=RemoteComputerName; Size=150.00}"
    }
}
```

## 5. Possible Solution
I have none to offer.
## 6. Context
I have some scripts that are growing so I'm working through 'Learning Powershell Toolmaking in a Month of Lunches' to get them better written. I was using the opportunity and time to learn and apply pester unit testing in the environment. I would like to get some test units written to test changes to the scripts in the future.

**Comment by mikeclayton** [comment]
Hi @ginobrewski,

I think what you're saying is that when you call your ```Get-VolumeInfo``` function in a normal PowerShell session the **real** ```Get-CimInstance``` returns a filtered array which only contains drive objects that have ```DriveType=3```.

By comparison, when you call ```Get-VolumeInfo``` with your Mock version of ```Get-CimInstance```, you are getting an unfiltered array containing the 3 hard-coded values defined in your Mock, some of which don't match the ```-Filter "DriveType=3"``` parameter.  This is because your Mock doesn't know what to do with the ```-Filter``` parameter - it just blindly returns the same 3 values every time.

Using ``` | where-object { $_.DriveType -eq 3 }``` works because PowerShell's ```where-object``` cmdlet is filtering the items returned by both the real and Mock versions of Get-CimInstance, hiding the fact that your Mock is ignoring the filter.

The best way to fix this is to modify your Mock to only return items that match the filter - you only need to superficially copy the way the real Get-CimInstance behaves, and not re-implement all of its functionality anyway.

Hope this helps.

Cheers,

M

**Comment by ginobrewski** [comment]
Thanks for the feedback. It has given me a better understanding of how Mock works with powershell.

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
