### ISSUE TITLE
Allow use of parameter aliases in Mock -ParameterFilter

### ISSUE THREAD

**Issue by richardnagle** [pester/Pester#1128]
## 1. General summary of the issue

Powershell parameters can be defined with aliases:

```powershell

function Get-Something{    
   param(
        [Alias('Path')]
        [string] $PathName)
   #function body
}

Get-Something -Path c:\temp.txt
```

When mocking with `-ParameterFilter` you cannot currently use the alias name to filter, but must use the real parameter name.

```powershell
Mock Get-Something -ParameterFilter {$PathName = "c:\temp.txt"} {return 123} #works
Mock Get-Something -ParameterFilter {$Path = "c:\temp.txt"} {return 456} #fails
```

## 2. Describe Your Environment

Pester version : 4.4.0 3.4.0 3.3.5 C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.0\Pester.psd1 C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Pester.psd1 C:\Program Files\WindowsPowerShell\Modules\Pester\3.3.5\Pester.psd1
PowerShell version : 5.1.15063.1292
OS version : Microsoft Windows NT 10.0.15063.0

## 3. Expected Behavior

`Get-Content` has a parameter named `-Tail` which has an alias `-Last`

```powershell
(Get-Command get-content).ParameterSets[0] | select -ExpandProperty parameters | select Name,Aliases | where Name -eq Tail

Name Aliases
---- -------
Tail {Last}
```

Therefore I would expect this test should pass:

```powershell
It "Uses parameter aliases in Parameter-Filter" {
   Mock Get-Content {return "default-get-content"}
   Mock Get-Content -ParameterFilter {$Last -eq 100} -MockWith {return "aliased-parameter-name"}

   Get-Content -Path "c:\temp.txt" -Last 100 | Should -Be "aliased-parameter-name"
}                                       
```

## 4.Current Behavior

When using an alias in `-ParameterFilter` the variable never has a value.

The output from the above test is

```
[-] Uses parameter aliases in Parameter-Filter 50ms         
  Expected strings to be the same, but they were different. 
  Expected length: 22                                       
  Actual length:   19                                       
  Strings differ at index 0.                                
  Expected: 'aliased-parameter-name'                        
  But was:  'default-get-content'                           
  -----------^    
```

**Comment by nohwnd** [comment]
Mock is generating param block for the parameter filter, so it should also resolve which aliases are there and define them as well to solve this.

**Comment by fflaten** [comment]
Looks like problem is in `Test-ParameterFilter` which tests ever Mock to verify if the filter matches. The parameter `$ScriptBlock`, each Mock's parameterfilter, is unmodified and using the alias, while `$BoundParameters`, the parameters from the Mock call, has had the `Last`-alias resolved to the correct parameter name. This makes the filter-test fail because you get the following scenario:

```
& { param($Path, $Tail) $Last -eq 100 } -Path "c:\temp.txt" -Tail 100
#Last will be $null -> test returns $false -> mock isn't used
```

So while a Mock supports alias when the Mock is called, the filter itself can't use parameter aliases.

I've played with a possible solution to replace all variables in `$ScriptBlock` that matches a parameter alias in the mocked command with the official parameter name. However, if someone is using a variable in the filter which is also the alias for a parameter, then the filter-test will be always true. Ex. with

```
$Tail = 100
Mock Get-Content -ParameterFilter {$Last -eq $Tail } -MockWith {return "aliased-parameter-name"}
```

then `Test-ParameterFilter` would evaluate the mock using

`& { param($Path, $Tail) $Tail -eq $Tail } -Path "c:\temp.txt" -Tail 100`

Not sure how big of a problem it would be. You can write bad filters now as well, but people may not know all the parameter aliases for a cmdlet and use it by mistake.

**Comment by nohwnd** [comment]
@renehernandez ok. This should not be complicated but there is a lot of potential for breaking changes and conflicts with read-only variables, as seen in the issue you are mentioning.

**Comment by renehernandez** [comment]
@nohwnd  I think it would be possible to avoid the conflicts by rewriting the alias in the `ParameterFilter` block to correct parameter name in the mock definition

**Comment by nohwnd** [comment]
@renehernandez can you give me an example?

**Comment by renehernandez** [comment]
@nohwnd  I may be off here, but I would expect that the AST of `ParameterFilter` scriptblock could be iterated and whenever we find an alias, then replace it with the real parameter name from the mock definition.

For conflicting parameter names, after the work in #1007, the parameter name in the mock is prefixed with "_" (e.g. _PSEdition_), thus it shouldn't introduce any conflicts

**Comment by nohwnd** [comment]
Okay that is how you meant it. That might work. I was asking because earlier I was talking about setting a variable not only for that param name but also for the aliases, and that would not work. I did not know that by rewriting your mean rewriting AST. The only thing is that AST is not avaiable in powershell v2.

**Comment by renehernandez** [comment]
@nohwnd, I always forgot checking for powershell 2 because I never use it. The closest option there would be to work with `System.Management.Automation.PSParser`, but unfortunately it is less capable than an AST so will see how it goes.

**Comment by renehernandez** [comment]
As a side note, since the powershell 2 deprecation has been announced already, [see here](https://blogs.msdn.microsoft.com/powershell/2017/08/24/windows-powershell-2-0-deprecation/), do we have a roadmap to drop Pester support for powershell 2)? I believe it would help refactor the code to leverage newer language features

**Comment by nohwnd** [comment]
@renehernandez Pester v5 will be PowerShell v3+, I think you can safely implement this as v3+ only as well :)
