### ISSUE TITLE
PR Discussion: Get-PesterTests

### ISSUE THREAD

**Issue by Stephanevg** [pester/Pester#1192]
Hi,

I would like to discuss a potential adition to the Pester framework, which could result in a PR, soon.
I have opened this issue to see if this would be a good idea to add it in the Pester module.

Indeed, for my module PSClassUtils I have written the a cmdlet named [Write-CUPesterTests](https://github.com/Stephanevg/PSClassUtils/blob/Feature_ConvertToPesterTests/PSClassUtils/Functions/Public/Write-CUPesterTests.ps1). This function will automatically create pester tests for powershell classes.

> This function, is actually one that I think belongs in **PSClassUtils** as it works exclusivley with classes, and uses internal functions of the module to get all the information needed based on classes.

To validate that the code I have generated is acurate or hasn't been updated, I have developed another set of functions which reads out the code from a file, and returns the pester code, in powershell objects (typed, but compatible with PS2).

The functions are the following ones (And are the ones I would like to add to the Pester Module).

- Get-PesterScript
- Get-PesterDescribeBlock
- Get-PesterITBlock

## Get-PesterScript

Returns an object representing the complete PesterScript (TypeName: Powershell.Pester.Script)

>Example:
We can imagine that **$Home/PesterTestScript.Tests.Ps1** contains the following script:

```powershell
Context "Plop"{
    Describe "My DEscribe Block"{
        It "My It block"{
            $false | should be $true
        }
        It "My It block 2"{
            $Woop | should be $Wap
        }
        It "My It block 3"{
            $var = "Plop"
            $e = "ert"
            $var | should be $e
        }
        It "My It block 4"{
            "plop" | should be "Hello"
        }
    }
    Describe "D block 2"{
        It "My It block 2.1"{
            "22" | should be "44"
        }
        It "My It block 3"{
            $e = "w"
            $eww = "e"
            $eww | should be $e
        }
    }
}
  
```

```powershell
$Path = $Home/PesterTestScript.Tests.Ps1
Get-PesterScript -Path $Path
```
Returns the following data:
![image](https://user-images.githubusercontent.com/6302961/50565151-33c85580-0d2c-11e9-87a6-039cd40a4095.png)

Navigating one level deeper (in .Data) we have the interesting part, the pester code of that file:

![image](https://user-images.githubusercontent.com/6302961/50565143-1d21fe80-0d2c-11e9-8e85-92020f9f135f.png)

## Get-PesterDescribeBlock

Returns the DescribeBlock(s) contained in a script. TypeName: Powershell.Pester.Describe

## Get-PesterItBlock

Will return the ITblocks contained in a describe block. TypeName: Powershell.Pester.It

# summary

I think you got the point, but using the AST, I extract the different Pester blocks in seperate objects.
Hiearachly it looks like this:

```powershell
# PesterScript
## Describe
### It
## Describe
### It
```

...

These functions are super specific for Pester, and not at all class related, so I thought they would fit better in the Pester module directly rather then in the PSClassUtils module.

If this is something of your interest, I could provide a PR to discuss code, naming convention etc... (Or perhaps here, or in another issue - you guys tell me how you like to work).

**Comment by nohwnd** [comment]
Thanks for the proposal, but I have to reject it, sorry. I think you'd be wasting your time implementing this to completion. Parsing a Pester file is more complicated than that. The whole framework is based on the different blocks being functions nested in each other. So one can easily take an It/Describe/Context block and wrap it into a function, or even put it in a separate script and invoke that (see e.g. #1188 ). 

I can see that your parsing would easily work for the base cases, but it would be a lot more work to do it completely via AST, you'd have to navigate between files and functions etc. All in all you'd have to pretty much duplicate what happens when the script is running. So there is a much simpler solution: Execute twice. First discover all the tests by running all Describe and Context blocks, but don't invoke It, Before*, After* blocks, only collect them. Then the second time around execute everything. I started developing this over christmas, and now I am slowly getting it to work with the rest of Pester.

**Comment by Stephanevg** [comment]
Ok, I see. I thought I had something interesting for the framework here.
The global idea was just to parse simple pester tests indeed.

You answer made me curious:
@nohwnd you mentionned that it would be easier by executing it twice: 
- Discover
- Execution

How would you actually run a pester test once, without really executing the code in it?
I am interested in the process, would you have an example to share?

Thanks

**Comment by nohwnd** [comment]
@Stephanevg I do have a simple example. You simply run the code twice and take different paths when in discovery mode and when not in discovery mode. 

```powershell
function _describe ($name, $sb) { 
    
    if ($discovery) {
        Write-Host Found block $name
    }
    else { 
       Write-Host Executing block $name
    }

    # invoke in both cases
    & $sb
}

function _it ($name, $sb) {
    if ($discovery) { 
        # in this case we only want to know 
        # that we found a test 
        $tests[$name] = $name
        Write-Host Found test $name
    }
    else {
        # invoke only when not discovering
        Write-Host Executing test $name
        &$sb
    }        
}

function _invoke ($sb) { 
    $discovery = $true
    $tests = @{}
    &$sb
    $discovery = $false
    &$sb
}
_invoke {
    _describe "describe 1" {
        _it "it 1" { 
            Write-Host "this is test 1" -ForegroundColor Cyan
        }
    }
}
```
In this code I run all the Describe blocks first and when I run It, it saves info about the test but does not invoke the associated scriptblock. On the second pass I invoke everything.

In here collecting the test data is kinda pointless, but if you take it further then it gives few advantages: 
1. You get accurate map of the tests even if they are wrapped in a helper function.
1. On the first pass you collect everything, including the scriptblocks associated with Before*/After* blocks, so there is no need to parse them out from the code. The function simply saves the scriptblock to the internal state, and when test is invoked (in the second pass) you take the associated scriptblock and invoke it. 
1. Capturing the scriptblocks on runtime (in case of Before* After* blocks) and invoking them directly (in case of Describe and It blocks) prevents you from de-attaching them from the session state so they keep all of their associated variables.
1. because you know in which nodes there are tests, and you can evaluate filters before executing the tests and setups, it is possible to only run setups where needed. So if you apply a very restrictive filter (say tag that 1 test out of 1000 tests has) you will discover in all files, but only run the on test and all it's parent Before* blocks.

The prototype I am implementing can be found in my fork [here](https://github.com/nohwnd/Pester/blob/new-runtime/new-runtimepoc/Pstr.psm1) and [here](https://github.com/nohwnd/Pester/blob/new-runtime/new-runtimepoc/new-runtime.ps1), but it's probably quite difficult to grasp what is going on because it's messy and there are a lot of unfamiliar concepts.

**Comment by Stephanevg** [comment]
Hi @nohwnd Thanks for sharing your example and the underlying use case, this is pretty interesting :)

I imagine you are using this primarly for internal mechanisms, right? Are you planning to make this public in the module? Like, would a user be able to access the list of the pester tests via a global variable or a function or so? 

Because my intent, was to offer that possiblity to the end user. (I actually needed that for documentation and automation reasons as explained in my first message).

---------------------------

I took your example (So as the one from https://github.com/pester/Pester/issues/1188) and and tried it out with my code based on the AST, and it actually worked quite well.
Of course, In my examples, BeforeEach and AfterEach is missing, but I convinced that would just be another property to add to the ```PowerShell.Pester.Describe``` Type. (And for the occasion create two subtypes:  ```powershell.pester.BeforeEach``` & ```powershell.pester.AfterEach```)


For simplicity, I have uploaded my code on a gist , so you can perhaps try it out your self, and navigate through the objects using dot notation (and perhaps try it out with a more complex example? ) Code is here --> https://gist.github.com/Stephanevg/34cff3425bebb7467bfe4c00f315f5ed


(Please don't take me wrong, I am not pushing or so, I just wanted to share my tests, and understand what you are exactly doing, and in that process learn from your expertise ;) )



## Example from above

![image](https://user-images.githubusercontent.com/6302961/50704251-085ca800-1057-11e9-945b-bb5e05b30c60.png)

![image](https://user-images.githubusercontent.com/6302961/50704261-16aac400-1057-11e9-89e2-fef78b140902.png)


## Example from #1188 

```powershell
$a = Get-PesterTest -Path $Scriptfile
```

![image](https://user-images.githubusercontent.com/6302961/50704198-d51a1900-1056-11e9-85cb-fca13ddebbd1.png)


![image](https://user-images.githubusercontent.com/6302961/50704183-caf81a80-1056-11e9-8da9-a83176e9034c.png)

**Comment by nohwnd** [comment]
> I imagine you are using this primarly for internal mechanisms...

Once I get it to work I will initially keep it internal, to avoid publishing something that needs to be changed ofter. But if the model proves to be useful and stable I was thinking about giving the user access to the internal state (ideally as a readonly object, but I guess that there would be a lot of overhead to do that, so probably it will be a live object). I am not sure if you saw that, but the runtime prototype is just a core that executes code and collects results, and the rest of the functionality (e.g. writing the output (implemented) or TestDrive, Mocking would be provided as plugins. Those plugins are simple a collection of scriptblocks that are called at appropriate times (e.g. before each Block or After all tests). To make this possible the callbacks need to get some context (e.g. name of the test, result of the test and so on). So the functionality you are talking about must be implemented anyway.

Additionally I am building the hierarchical object (let's call it a _test map_) that contains all the blocks ( Describe/Context) and tests (It), and info if they were executed, if they should have been executed, if they passed, failed how long it took, what were the results, outputs etc., and this test map would become the new -PassThru object. Splitting into a function that only discovers tests and does not execute them should be very simple, giving similar output as you have, but I call the `ItBlocks` `Tests` and the `Describe/Context` blocks just `Blocks` because this should be underlying runtime for both RSpec style Pester and Gherkin style Pester. If you would want to then transform it into types it should be as simple as traversing the tree and building another tree with your own objects of choice, but for me classes are not possible because this should all be at least powershell 3 compatible.

> Please don't take me wrong, I am not pushing or so...

Would not cross my mind if you did not mention it.

---

I also remember simply aliasing functions as Describe and It (so they are picked up before the real Describe and It) and used them to build the tree by executing a test suite in the same way as when Discovery is enabled in the above example.

**Comment by nohwnd** [comment]
> You already have ideas on how to create a readonly object in powershell? I would be curious how you plan to implement that one :)

I think it would require traversing the object and making a copy of every value. Not very efficient.
