### ISSUE TITLE
v5: Discovery Performance

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1207]
Quickly tested the alpha, 9000 tests in 1 file, 354 files with 26 tests each, on both PowerShell 5 and 6, on both it takes roughly 30s. Running on Windows 10 and quite fast SSD, but running it in a scriptblock seems not very different, so disk speed is likely not a huge factor here. 

Simply running 9000 scriptblocks in one scriptblock yields 14s on both PowerShell 5 & 6. So there is room for optimization, but it's actually not as slow as I expected. I did not do any optimization for this hot-path yet, so I am likely evaluating empty scriptblocks, adding arrays together, or maybe even using.

30 second "wait time" seems reasonable to me given 9000 tests, and that most of the work should then be saved during runtime. More measurements of course need to be made.

/cc @vexx32

**Comment by vexx32** [comment]
Woah, not bad at all!! Shiny... ✨

**Comment by iSazonov** [comment]
We could make some investigations in PowerShell repo but in last months MSFT team has very low activity :-( to review and merge.
I already prepare some improvements in File Provider but I don’t even try to publish for this reason. Although I still do not lose inspiration

It would be great to have some **baseline** test files in Pester repo for performance measurements  we could use over time.

**Comment by nohwnd** [comment]
@iSazonov  I plan to add some performance checks that compare v4 and v5, and possibly graph them in azdo / appinsights / somethig else, just to have some basic data over time to see that v5 is not degrading.  I have the checks locally.  

I will also try to run Pester under Measure-Script, and see if I get some data from that. 

I could not figure out a reasonable way to look at powershell code performance using a traditional .NET perf tools, if you have any tips let me know. :)

**Comment by iSazonov** [comment]
If you developed and shared some baseline scripts like you mentioned above others could investigate in the area staying on the same wave.

> I could not figure out a reasonable way to look at powershell code performance using a traditional .NET perf tools, if you have any tips let me know. :)

I am thinking about PerfView. This can help to discover hot paths in PowerShell Engine that Pester uses.
After that we will have two way - (1) Make some optimizations in PowerShell Engine, (2) make some optimizations in Pester by replacing expensive constructions, e.g. using a filter function instead of Where-Object.

**Comment by nohwnd** [comment]
Do you have any concrete resources on how to use perfview together with powershell? I was able to record the profile, but could not find a way to link the time spent in the interpreter methods to the actual powershell code that is being executed.

**Comment by iSazonov** [comment]
I say about the PerfView https://github.com/microsoft/perfview
It has great embedded Help.

1. Build PowerShell as Release
2. Run elevated PerfView
3. run pwsh
4. Start Collect in PefView
5. run test script in pwsh
6. Stop Collect in PerfView
7. Open collected file
8. Since you run pwsh from build folder PerfView can able to find pdb files and show PowerShell names.
9. Perhaps PerfView log says that it can not find crossgen.exe. In the case copy it from SDK folder to pwsh home folder.

**Comment by nohwnd** [comment]
@iSazonov could you screenshot a session just so I know what I am looking for? I was able to see the dotnet method names, but could not figure out how I would for example identify that there are performance improvements to be made in just one Where-Object clause.

**Comment by iSazonov** [comment]
In PowerShell repo we have some PRs with CL-Performance label like https://github.com/PowerShell/PowerShell/pull/10047
I hope this help you.

See also:
https://github.com/PowerShell/PowerShell/pull/10454
https://github.com/PowerShell/PowerShell/issues/9941

Where-Object is slow because of slow parameter binding for every input object. It is very complex task to make it more faster.
If possible you could use a filter function instead.

**Comment by nohwnd** [comment]
@iSazonov I was just using that as an example because you were. I don't use where-object on the hot path, and also got rid of as many function calls and cmdlets as reasonably possible. 🙂
