### ISSUE TITLE
String concatenation using the += operator fails

### ISSUE THREAD

**Issue by renehernandez** [pester/Pester#1239]
## 1. General summary of the issue

When doing string concatenation, I cannot append a string into a the `$var` variable defined in the BeforeEach block.

```
Describe 'Joining strings' {
    BeforeEach {
        $var = 'hello'
    }

    It 'returns hello world by variable expansion' {
        $var = "$var world"

        $var | Should -Be "hello world"
    }

    It 'returns hello world by string concatenation using += operator' {
        $var += " world"

        $var | Should -Be "hello world"
    }

    It 'returns hello world by string concatenation using $var = $var + ' {
        $var = $var + " world"

        $var | Should -Be "hello world"
    }
}
```

## 2. Describe Your Environment

Pester version     : 4.6.0 C:\Users\renehernandez\Documents\WindowsPowerShell\Modules\Pester\4.6.0\Pester.psm1
PowerShell version : 5.1.14393.2636
OS version         : Microsoft Windows NT 10.0.14393.0

## 3. Expected Behavior

All tests should pass

## 4.Current Behavior

The second test, using `+=` assignment operator fails. Instead of concatenating, it replaces the value in the `var` variable

**Comment by nohwnd** [comment]
That is because `BeforeEach` runs in a scope above the `It` in Pester v4. So you are pretty much doing this: 

```powershell
&{
    $var = "hello" 
    &{ 
        $var += " world"
        $var
    }
}
```
This is a nice edge case where you might expect the `$var = $var + " world"` to be equivalent to `$var += " world"` but it is not. The diference here is in implicit scopes, so while the first one is equivalent to `$local:var = $var + " world"`, the latter is equivalent to `$local:var = $local:var + " world"`. Notice the absence of the `local:` scope quialifier in the first example, that means that the value will be taken from the parent scope and you get "hello world" result, while in the latter case the first call to `$local:var` will return `$null`, giving you " world" result.

In v5 this should work because `BeforeEach` is running in the same scope as the body of `It`. 

```powershell
&{
    $var = "hello" 
    &{ 
        $var += " world1"
        $var
    }
}

&{
    $var = "hello" 
    &{ 
        $var = $var + " world2"
        $var
    }
}

&{
    $var = "hello" 
    &{ 
        $local:var = $local:var + " world3"
        $local:var
    }
}

&{
    $var = "hello" 
    &{ 
        $local:var = $var + " world4"
        $local:var
    }
}

## output
#  world1
# hello world2
#  world3
# hello world4
```

**Comment by renehernandez** [comment]
For reading the docs, I misunderstood that this was already the behavior :). I am ok with closing this issue then. Looking forward to version 5

**Comment by nohwnd** [comment]
Re-opening this so I can validate that it actually works like this in v5.

**Comment by nohwnd** [comment]
Confirmed, this is behaving correctly in v5.
