### ISSUE TITLE
Mocks in the same context gets duplicated blocks

### ISSUE THREAD

**Issue by renehernandez** [pester/Pester#1241]
## 1. General summary of the issue

While debugging the mock code for the #1128 implementation with the tests examples below, I found out that multiple mock command definitions with the same mocking block generate blocks duplication in the mock `hashtable` object. This seems to be happening at https://github.com/pester/Pester/blob/master/Functions/Mock.ps1#L36

```powershell
Describe "Multiple mocks in same context" {
        Context 'Mocks in BeforeEach' {
            BeforeEach {
                Mock Get-Content { "default-get-content" }
                Mock Get-Content -ParameterFilter {$Tail -eq 100} -MockWith { "aliased-parameter-name" }
            }

            It "returns mock that matches parameter filter block" {
                # body
            }

            It 'returns default mock' {
                # body
            }
        }
}
```

## 2. Describe Your Environment

Pester version   :  latest master
PowerShell version : 6.1.1
OS version         : Microsoft Windows NT 10.0.17134.0

## 3. Expected Behavior

Same blocks should only be added once per mock

## 4.Current Behavior

The `Hashtable` mock object has duplicated blocks

**Comment by nohwnd** [comment]
@renehernandez The example that you shown has two different mock blocks, is it supposed to show the problem? :) 

Is there a problem to solve? Adding the same mock twice (or twenty times) will put it multiple times in the table, but only the first one that passes the mock filter will run (no `-ParameterFilter` means filter `{ $true }` that always passes). So it's just (very slightly) inefficient, but it works just fine? Or is there a problem that I don't know about? 

On the other hand optimising this would mean that we would need to check the mock with scriptblock, the parameter filter and check that they are the same, then we would need to move the existing mock block to the top of the list. 

Consider: 

```powershell
Mock a { "a" }
Mock a { "b" }
Mock a { "a" }
a
```
Here the `{"a"}` body should run, because it was defined last. Naively filtering out the call to mock when we already have that body would mean that `{"b"}` would run which is incorrect.

You also need to think about scopes:

```powershell 
Describe "a" {
    Mock a {"a"}
    It "b" {
            Mock a {"b"}
            Mock a {"a"}
            a
     }
}
```
Here "a" should win inside of the `It` and also survive for the other tests in `Describe`.

Furthermore `-MockWith` scriptblock can be a closure. So having two scriptblocks with the same body content, we need to make sure that they are different when they are both closures, one of them is not closure, and are only the same when they are both not closures.

**Comment by renehernandez** [comment]
@nohwnd It works fine, it just that I was surprised by the fact that the mock object can have multiple copies of the same filter **at the same scope**. But I guess I didn't account for all use cases you have mentioned above. Feel free to close it :)

**Comment by nohwnd** [comment]
@renehernandez Great, I just wanted to clarify :) Closing this.
