### ISSUE TITLE
Last character in parameter filter script blocks getting stripped

### ISSUE THREAD

**Issue by splatteredbits** [pester/Pester#1256]
```
Describe 'Pester4.7' {
    $filter = [scriptblock]::Create( ('$Path -eq ''C:\Windows''') )
    Mock -CommandName 'Test-Path' -ParameterFilter $filter
}
```
fails with this error:

```
Describing Pester4.7
  [-] Error occurred in Describe block 0ms
    ParseException: At line:1 char:23
    + Path -eq ("C:\Windows"
    +                       ~
    Missing closing ')' in expression.
    MethodInvocationException: Exception calling "Create" with "1" argument(s): "At line:1 char:23
    + Path -eq ("C:\Windows"
    +                       ~
    Missing closing ')' in expression."
    at New-BlockWithoutParameterAliases, C:\Build\weaver\PSModules\Pester\4.7.1\Functions\Mock.ps1: line 1638
    at Mock, C:\Build\weaver\PSModules\Pester\4.7.1\Functions\Mock.ps1: line 345
    at <ScriptBlock>, C:\Build\Test-Pester4.7.Tests.ps1: line 4
    at DescribeImpl, C:\Build\weaver\PSModules\Pester\4.7.1\Functions\Describe.ps1: line 199
```

I've tried changing the last characer to a double-quote, enclosing the string in parenthesis, etc. I get the same error.

## 2. Describe Your Environment

```powershell
Pester version     : 4.7.1 C:\Build\*********\PSModules\Pester\4.7.1\Pester.psd1
PowerShell version : 5.1.17134.407
OS version         : Microsoft Windows NT 10.0.17134.0
```

**Comment by renehernandez** [comment]
@splatteredbits Nice catch! I found out the reason for the issue:

At [line 1636](https://github.com/pester/Pester/blob/master/Functions/Mock.ps1#L1636), we are removing the top-level brackets from the text representation of the block AST. 

The problem with that is that I wrongly assumed that will be getting a regular parameterfilter block, i.e:

`Mock -CommandName 'Test-Path' -ParameterFilter { $Path -eq 'C:\Windows' }`

**Comment by renehernandez** [comment]
@nohwnd I will open a pull request with a fix for this soon

**Comment by renehernandez** [comment]
@nohwnd The way I look at this there are two ways of approaching ths:

* Instead of getting the full text of the scriptblock, which we currently do at [line 1619](https://github.com/pester/Pester/blob/master/Functions/Mock.ps1#L1619), we could get the text from the EndBlock section (using `$ast.EndBlock.Extent.Text`) and we would avoid completely the check for the most external brackets. The downside to this is that we could be skipping replacement of aliases if the *scriptblock* where to have any of the other of the possible blocks sections (i.e., **begin**, **process**, **params**, etc). 
Question here: Is this expected for parameter filters blocks?
* The other option would be to check if the string start/end with brackets and remove them if present, but that made realize that the string could start with brackets because it wants them there, for example:
`[scriptblock]::Create('{Name="MyName"}')`

**Comment by nohwnd** [comment]
Begin process or params are not expected.

**Comment by renehernandez** [comment]
@nohwnd Ok, then I am going to go with the first option :)
