### ISSUE TITLE
Code Coverage outside of Pester

### ISSUE THREAD

**Issue by jborean93** [pester/Pester#1262]
## 1. General summary of the issue
This isn't an issue but really a question/feature request. I'm working on adding coverage support for Windows module in Ansible and one of the approaches I'm taking is to use Pester to do the coverage work when the module is executed. It seems like I need to run `Invoke-Pester` with `-CodeCoverage` for this to work but I was hoping I could just execute the script like normal and have a separate cmdlet to invoke with coverage, e.g. `Invoke-WithCoverage -Script ... -CodeCoverage ...`.

The reason for this is simple, I want to still invoke the Ansible modules in our usual wrapper process and for it to still handle errors itself. If I was to run it with `Invoke-Pester`, it mostly works but if an uncaught exception was thrown or some other error raised, they would be captured in the Pester test harness and then missed by our wrapper.

**Comment by nohwnd** [comment]
@jborean93 incidentally I worked on this last weekend, and was wondering if there was a place where code coverage would be useful without Pester and could not find any :) 

In Pester v5 (that is unreleased, and in alpha right now), the code coverage is no longer dependent on the Pester internals, so what you want is imho easily possible, although untested. Also I did not touch 99% of the coverage code, I just isolated it from the rest of pester, so the alpha state should not matter to you :)

If you look [here](https://github.com/pester/Pester/blob/d626341b29a1668aa88310ca9dd57023a8e1b730/Functions/Coverage.Plugin.ps1)  this code binds code coverage to pester, this code runs at the start of every file (it's called container here because it can also be a script block or possibly a data blob or whatever, but you don't have to care about it).  

The important parts here are line 7 that line generates the breakpoints to be hit, and saves them in pester state. Then on when the container is done running, it takes the breakpoints from the state (line 17) and generates a report from them. 

Running those two lines should give you the whole functionality. You just need to preserve the breakpoints. Which for you is simple. So you should end up with something like this: 

```powershell
$config = # the CC config hashtable you give to Pester 
# setup breakpoints
$breakpoints = Enter-CoverageAnalysis -CodeCoverage $config

# your code runs here 

# generate report & remove breakpoints
$coverageReport = Get-CoverageReport -CommandCoverage $breakpoints
Exit-CoverageAnalysis -CommandCoverage $breakpoints
$config = # the CC config hashtable you give to Pester 
# setup breakpoints
$breakpoints = Enter-CoverageAnalysis -CodeCoverage $config

# your code runs here 

# generate report & remove breakpoints
$coverageReport = Get-CoverageReport -CommandCoverage $breakpoints
Exit-CoverageAnalysis -CommandCoverage $breakpoints
```

I can't try it right now, but I think this should pretty much be it. The only other thing is that pester uses SafeCommands hashtable to protect the internals from corruption when users mock built-in cmdlets. So you will need to import that script  as well, or replace all the calls to safecommand hashtable with just the cmdlet (that is really easy via regex, but I will let  you figure it out :) )

If you have more questions, or need help getting this to work let me know, we can work on it together if you can't figure it out, possibly others would find it useful it as well :)

**Comment by jborean93** [comment]
Thanks for the info I will give it a shot and see how I go. I’m still in preliminary work right now and may not get into more details for a while but this is really great info to know.

**Comment by jborean93** [comment]
My apologies I forgot to come back and close this. We ultimately implemented https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/powershell/coverage_wrapper.ps1 into Ansible to achieve the coverage collection. Thanks for the info it was really helpful.
