### ISSUE TITLE
Add possibility to use debugging and breakpoints in mocks

### ISSUE THREAD

**Issue by ykuijs** [pester/Pester#1297]
## 1. General summary of the issue

When creating Pester tests, you can use debugging and breakpoints in Pester file. However, it is not possible to set breakpoints or step through mocks. It would be very helpful to add the possibility to do this to Pester, especially when you have complex mocks which you are trying to troubleshoot.

## 2. Describe Your Environment

Windows 10  and Windows Server 2012 / 2016 / 2019

PowerShell 5.1

Pester 4.7.3

## 3. Expected Behavior

Set breakpoints to mocks, so you can troubleshoot them.

## 4.Current Behavior

Breakpoints don't work in mocks

## 5. Possible Solution

Implement debugging for mocks

## 6. Context

The current behavior makes debugging mocks harder, especially when you have very complex mocks.

**Comment by nohwnd** [comment]
Hi, thanks for the report, I will look into this in v5. 

Note to self: 

In v4 the block for mock (unless it is a closure) are manipulated as a text to add param block and de-attach them from the test scope. In v5 the mock body should run in the test scope and the params should be added to a wrapper script block so we keep executing the same scriptblock and breakpoints still work.

**Comment by nohwnd** [comment]
To achieve debugging here we would have to either:
1) stop re-writing the parameter filter to remove parameter aliases from it - and instead parse the scriptblock and define appropriate variables above (which will be problematic if variables of those names are constants)
2) copy breakpoints and put them in the same place in the re-written block 
3) do not copy breakpoint but trigger the original ones (not sure if possible, and it does not show the real code)
3) remove the functionality that allows using aliases in fliter (easiest, but possibly a solution that we don't want to take)

To debug in the Mock body I removed the call where unbinds the scriptblock and it works, I did not run all tests yet though.

**Comment by nohwnd** [comment]
Discussion on slack: 

seeminglyscience [5:10 PM]
Nah it's stored in `FunctionContext`
Well at runtime, any other time it's just sitting in the debugger


nohwnd [5:12 PM]
pretty much we need to rewrite the sb provided to parameterfilter to allow using aliases of parameters eg $Last when you actually mean $Tail parameter, we do that by asting the scriptblock and then [scriptblock]::create to create a new one which we invoke, that makes the breakpoints not related to the code that actually executes.
So I thought I take the bps that are on the original scriptblock and add new ones on the same lines in the new sb, which might make the editor debug it in a "temp" file, because that is what I see when I step into mock code that is also generated from text.
I am open to any better solution :))

seeminglyscience [5:15 PM]
Do you mean it doesn't fire the breakpoint?

nohwnd [5:18 PM]
yup, it is not the same scriptblock anymore.

seeminglyscience [5:19 PM]
But yeah they aren't really store like that. For line breakpoints you can match up against `Ast.Extent.File` and check breakpoints set for that script on that line/column. All the debugger does is check each sequence point, see if the `IScriptExtent` matches, and then break if it does

So if you want to create a new sb that will hit breakpoints the same way, you need to create an AST with the `ParseInput` method that takes a file name. Then use the `GetScriptBlock` method. Also prepend the text with spaces a new lines to make the extent position match
If only the syntax rewriter was production ready :P perfect use case

**Comment by nohwnd** [comment]
This should not be a breaking change, the mock an param filter both run in test scope now, so it should be compatible change, moving up to 5.x because I don't have to do it now.

**Comment by DannyMeister** [comment]
I have found a workaround which can allow you to break and step through mocks, albeit not by using a normal breakpoint in the IDE.  It uses a variable breakpoint.

```
function Debug-Here {
  if(!(Get-PSBreakpoint -Variable DebugHereCount)) {
      $SCRIPT:DebugHere= Set-PSBreakpoint -Variable DebugHereCount
  }
  $DebugHereCount++
}

Mock MyFunction {
  Debug-Here
  [mock logic you want to debug]
}
```

Idea taken from https://stackoverflow.com/a/20913596/1359579

**Comment by fsackur** [comment]
Question: if #1500 is closed, can this issue be closed?

**Comment by nohwnd** [comment]
@fsackur  Yup this is done. Thanks for bringing it up.
