### ISSUE TITLE
Mock Get-ADUser: ParameterFilter on "-filter" unable to expand variable value

### ISSUE THREAD

**Issue by Fwnolte** [pester/Pester#1327]
## 1. General summary of the issue
When trying to mock a call to `Get-ADUser` that relies on the `-Filter` property, any variables inside the `-Filter` script block do not get expanded at test runtime. 

## 2. Describe Your Environment

Pester version     : 4.8.1 C:\Program Files\WindowsPowerShell\Modules\Pester\4.8.1\Pester.psd1
PowerShell version : 5.1.14393.2969
OS version         : Microsoft Windows NT 10.0.14393.0

## 3. Expected Behavior
I have a module that I'm testing that wraps `Get-ADUser` and performs some data enrichment. The module has several ways to search for users, so I rely on the `-Filter` property and pass it the data I want to search on, in this case stored in a variable `$item`.
```
if ($item -match ".\w*\..*" -and !($item -match "@")) {
    $users = Get-AdUser -filter { DisplayName -Like $item } -Server <REDACTED> -Properties *
}
if ($item -match ".*@.*"-and $item -match "@") {
    $users= Get-AdUser -filter { EmailAddress -Like $item} -Server <REDACTED> -Properties *
}
```
When creating a mock for the `Get-ADUser` call, I would **like** to be able to do the following:
```
Mock Get-AdUser { return $mockAdUser } -ParameterFilter {
    $filter -Like $mockUserEmailAddress # The $mockUserEmailAddress variable is set to 'test.email@mydomain.com'
}
```
Then, I would call my wrapper module:
```
Get-UserInformation test.email@mydomain.com
```

As per my module's code, this would set the value of `$item` to 'test.email@mydomain.com'. However, the `-ParameterFilter` never matches the value of `$item`.

## 4.Current Behavior
In the context of the above example, I was able to determine what's occurring by changing my mock to a more generic one and running the same test.
```
Mock Get-AdUser {
    return $mockAdUser 
} -ParameterFilter {
    Write-Output $filter > ./out.txt
    $filter -Match '.*'
}
```
The contents of the file **out.txt** after running the test:
```
EmailAddress -Like $item
```

As far as I can tell, this means that it's impossible to create a mock that relies on the value of a variable present in the `-Filter` scriptblock. I'm not sure if this is an issue that occurs across all of Pester.

## 5. Possible Solution
Not familiar enough with Pester/Powershell internals to know if I'm doing something wrong, or if it's a Pester problem.

## 6. Context
Unable to correctly test module, as results of tests rely on output of `Get-ADUser`.

**Comment by nohwnd** [comment]
@Fwnolte I am a bit lost about what you want to actually do. But let's figure it out together.  :)

1) Filter
I haven't touched AD in a looooong while. But from what I gather from your examples, the filter is post processed somehow. Meaning that `{ DisplayName -Like $item }` is not an actual ScriptBlock that would be executed, because if it was then `DisplayName` without any quotes or `$_.` would result in syntax error. 

This post processing logic is not present because you are mocking the cmdlet, so what you get is what you see in the point 4 where you are dumping the value of $filer (simpler way to do that is btw `Write-Host -$filter-`, then you print the value to the screen or you print `--` to know that the value was empty.)

2)  In the parameter filter you are testing this `$filter -Like $mockUserEmailAddress` which would expand to this `'EmailAddress -Like $item' -Like 'test.email@mydomain.com'`. On the left there is the `Filter` scriptblock as a string, and on the right the email address. The $item is not expanded because you never executed the `Filter` scriptblock, and even if you would you'd get `The term 'DisplayName' is not recognized as the name of a cmdlet` error.

3) The mock injects the variable if it is a parameter of the mocked function so `$item` resolves to the injected value, I can confirm that, but it won't affect your code because you are not evaluating it.

**Comment by Fwnolte** [comment]
Sorry for not replying quickly! Been a busy week.

To explain WHY I'm running into the problem as described, it's because my
Get-UserInformation module can accept multiple users as a comma-separated
list. (So I can call `Get-UserInformation user1,user2,user3,etc...`. Thus,
I want to test to verify my output is correct when I call the script with
more than one user.

Eventually, each username is passed individually to the following line,
which is inside my `Get-UserInformation` module:
`Get-ADUser -Filter {SamAccountName -Like $username} -Server <REDACTED>
-Properties *`.

In the above line, I would expect Get-ADUser to return 3 different user
objects based on whatever the value of `$username` is for the current
iteration. When setting up the mock for this case, I have 3 separate mocks
of `Get-ADUser` and am relying on the `-ParameterFilter` to look at the
value of the `-Filter` block. I want to run comparisons against this value
in order to have the mocks spit back different user information. However,
the `-ParameterFilter` isn't working because when Pester is checking which
mock object to use, the value of the `-Filter` value is ALWAYS
'SamAccountName -Like $username', rather than 'SamAccountName -Like user1',
as expected.

**Comment by nohwnd** [comment]
@Fwnolte I understand, but the behavior in Pester seems correct. You provide a scriptblock and you get back a scriptblock.  :)

If you want to invoke the scriptblock yourself you need to do it in the parameter filter, but it does not contain a valid PowerShell syntax. You can also just inspect the `$username`.  In any case I would try to avoid stateful mocks as much as possible. 

Here is an example that simulates what you are doing: 

```powershell
Import-Module Pester -MaximumVersion 4.9.9 

function Get-AdUser ([ScriptBlock]$Filter) { }

function Get-UserInformation () {
    foreach ($username in "u1","u2", "u3") {
        Get-AdUser -Filter { SamAccountName -Like $username }
    }
}
Describe "d" { 
    It "i" { 
        Mock Get-AdUser -ParameterFilter { 
            Write-Host Filter: $Filter 
            $true 
        } 
        Get-AdUser -Filter { SamAccountName -Like $username } 
    }

    It "i" { 
        Mock Get-AdUser -ParameterFilter { 
            Write-Host Filter: $Filter
            Write-Host Username: $username
            $true
        }

        Get-UserInformation
    }
}
```
