### ISSUE TITLE
ParameterFilter match array

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#1329]
I was wondering if something like this would be possible?

```powershell
Describe 'test' {
    Mock Invoke-Command

    it 'should pass' {
        Invoke-Command -ScriptBlock { 1 } -ComputerName @('S1', 'S2', 'S3', 'S4', 'S5')

        Assert-MockCalled Invoke-Command -Scope It -Times 1 -Exactly -ParameterFilter {
            $ComputerName -contains @('S1', 'S2', 'S3', 'S4', 'S5')
        }
    }
}
```

It's difficult to assess if the complete array is being matched and not other stuff is in there. Is there a way on how to do this properly?

**Comment by nohwnd** [comment]
It is not difficult, it is just not what -contains or any other built-in operator does. You can script it quite easily, depending on the level of confidence you want. Here is one implementation: https://github.com/nohwnd/Assert/blob/master/src/Equivalence/Assert-Equivalent.ps1#L53 This one is a bit more complex than you need. But the basic ideas are there. Check that the collections are the same size. Iterate over one collection and remember which indexes you’ve already seen (so if left side has 1,2,2 and right has 1,2,1 you don’t take the 2 twice from right because there is only one.). And that’s probably it. I am on my phone, look at the linked solution :))

**Comment by DarkLite1** [comment]
I hear you. Will give that a go. Thanks for the info :)
