### ISSUE TITLE
Code coverage makes the test run really slow when Big psm1 file

### ISSUE THREAD

**Issue by Stephanevg** [pester/Pester#1334]
Hi,

I have noticed that each time I use the `-codecoverage` switch, the test execution gets slower.
But that is not really the big problem. The one that is the most painfull, is when I start the tests. It like needs around 4/5min to really start them.

It is most likley due to the fact that the file on which I am running the tests, is a `.PSM1` with more than  `9000` lines. I could imagine that what takes him so long to start, is that it first needs to set the breakpoints on each of the 9000 lines. (or?)

To test it, we can follow these steps:

1) clone this repository: `git clone https://github.com/Stephanevg/PSHTML.git` to C:\Plop\
2) run `Invoke-pester C:\plop\pshtml\Tests\ -codecoverage C:\plop\pshtml\pshtml\pshtml.psm1`

**Comment by nohwnd** [comment]
Are you running this in console or in an editor? Also which version of Windows are you using? It has been reported that Code Coverage takes extremely long on some builds of Windows #1318

**Comment by EklipZgit** [comment]
Getting this issue, for the last month or so our module builds have been taking foreeeeever. Seems like the time is spent during pester initially loading up, and also a large amount of time spent waiting after the code coverage output is spit back out at the end. Several minutes before starting the tests, and about a minute before pester terminates after outputting the code coverage. 10k line module.

Windows 10 Enterprise, latest-ish patches.

**Comment by nohwnd** [comment]
@EklipZgit you are describing exactly the symptoms the slow breakpoints have. Please see #1318 for more info about the affected systems and where it has been fixed. Unfortunately this cannot be fixed from Pester side because it stems from how powershell handles breakpoints and in the end how it reads registry. The only thing that Pester could do would be to change the mechanism in which code coverage is handled and that would be difficult and would probably bring a lot of bugs by itself. Sorry. 🙁
