### ISSUE TITLE
Mock not overriding function from module if test file is not in the current scope

### ISSUE THREAD

**Issue by ili101** [pester/Pester#1351]
## 1. General summary of the issue

Functions in modules aren't mocked when calling the test file with `& TestFile.ps1` or `Invoke-Pester -Script TestFile.ps1`. `. TestFile.ps1` works.

## 2. Describe Your Environment

Pester version     : 4.8.1 D:\ILI\Profile\Documents\WindowsPowerShell\Modules\Pester\4.8.1\Pester.psd1
PowerShell version : 5.1.17763.592
OS version         : Microsoft Windows NT 10.0.17763.0

## 3. Behavior

``` Powershell
# Make a Module
$Module = {
    function Get-MockMe {
        [CmdletBinding()]
        param()
        Write-Host 'Mock Failed!'
    }
    function Invoke-MockedFunction {
        [CmdletBinding()]
        param()
        Get-MockMe
    }
}
$Module.ToString() | Out-File -FilePath ([IO.Path]::GetTempPath() + '\TestModule.psm1')

# Make test file
$Test = {
    Import-Module ([IO.Path]::GetTempPath() + '\TestModule.psm1') -Force #-Verbose
    Describe 'Test' {
        Context 'Context' {
            #Write-Host (Get-Module 'TestModule' | Out-String)

            It "Mock Test" {
                Mock -CommandName 'Get-MockMe' -MockWith { Write-Host 'Mock Seceded!' }
                Invoke-MockedFunction
            }
        }
    }
}

$TestFile = ([IO.Path]::GetTempPath() + '\TestFile.ps1')
$Test.ToString() | Out-File -FilePath $TestFile

# Run with "." (Output: Mock Seceded!)
. $TestFile
# Run with "&" or "Invoke-Pester" (Output: Mock Failed!)
& $TestFile
Invoke-Pester -Script $TestFile
```

**Comment by mikeclayton** [comment]
Hi @ili101,

I tried your example locally as follows, and I got "Mock Failed" in all three approaches:

```
C:\src\scratch\pester\issue-1351> powershell .\go.ps1
```

**TestFile.ps1**
```powershell
Import-Module ".\TestModule.psm1" -Force
Describe 'Test' {
    Context 'Context' {
        It "Mock Test" {
            Mock -CommandName 'Get-MockMe' -MockWith { Write-Host 'Mock Seceded!' }
            Invoke-MockedFunction
        }
    }
}
```
**TestModule.psm1**
```powershell
function Get-MockMe {
    [CmdletBinding()]
    param()
    Write-Host 'Mock Failed!'
}
function Invoke-MockedFunction {
    [CmdletBinding()]
    param()
    Get-MockMe
}
```
**go.ps1**
```powershell
$ErrorActionPreference = "Stop";
Set-StrictMode -Version "Latest";

Import-Module ".\pester\pester.psd1" -ErrorAction "Stop";

write-host "using dot sourcing..."
. ".\TestFile.ps1"

write-host "using call operator..."
# see https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-6#call-operator-
& ".\TestFile.ps1"

write-host "using invoke pester..."
Invoke-Pester -Script ".\TestFile.ps1"
```

I think this is because the function you're trying to mock is defined inside the "TestModule" module, so you need to tell Pester that's where you want your Mock to be defined:

**TestFile.ps1**
```powershell
Import-Module ".\TestModule.psm1" -Force
Describe 'Test' {
    Context 'Context' {
        It "Mock Test" {
            ******** add -ModuleName "TestModule" to inject the mock into the test module
            Mock -CommandName 'Get-MockMe' -ModuleName "TestModule" -MockWith { Write-Host 'Mock Seceded!' }
            Invoke-MockedFunction
        }
    }
}
```

If you then run the same script the tests all work:

```
C:\src\scratch\pester\issue-1351> powershell .\go.ps1
using dot sourcing...

Describing Test

  Context Context
Mock Seceded!
    [+] Mock Test 691ms
using call operator...

Describing Test

  Context Context
Mock Seceded!
    [+] Mock Test 33ms
using invoke pester...
    ____            __
   / __ \___  _____/ /____  _____
  / /_/ / _ \/ ___/ __/ _ \/ ___/
 / ____/  __(__  ) /_/  __/ /
/_/    \___/____/\__/\___/_/
Pester v4.8.1
Executing all tests in '.\TestFile.ps1'

Executing script .\TestFile.ps1

  Describing Test

    Context Context
Mock Seceded!
      [+] Mock Test 15ms
Tests completed in 354ms
Tests Passed: 1, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0
```

Hope this helps,

Mike

**Comment by ili101** [comment]
Thank you @mikeclayton,
> I tried your example locally as follows, and I got "Mock Failed" in all three approaches:

I run your version, you are getting 'Mock Failed!' on "using dot sourcing..." because you're running go.ps1 in a child scope `powershell .\go.ps1` (Not sure if this is an accurate description), if you run the code interactivity in the console or dot source it `. .\go.ps1` or use VSCode the "using dot sourcing..." part will Mock successfully.
> I think this is because the function you're trying to mock is defined inside the "TestModule" module

I have the same problem mocking for example `Write-Warning`:
**TestModule.psm1**
``` powershell
function Invoke-MockedFunction {
    [CmdletBinding()]
    param()
    Write-Warning 'Mock Failed!'
}
```
> you need to tell Pester that's where you want your Mock to be defined

Yes this works when adding `-ModuleName 'TestModule'` but I don't like using it as it limiting you to one loaded module "RuntimeException: Multiple Script modules named 'TestModule' are currently loaded." and as it works without it when dot sourcing I don't understand why it's not working when using the call operator.

**Comment by ili101** [comment]
@mikeclayton, Small clarification, I Missed this yesterday.
`powershell .\go.ps1` Runs the script ` .\go.ps1` that run the file go.ps1 in a child scope, that why the dot source test was not working for you.
`powershell -File .\go.ps1` Runs the file go.ps1 so you are at the root scope.

Basically Mock is not working without specifying particular module if you are in a child scope.

**Comment by mikeclayton** [comment]
@ili101 - I've spent a couple of hours looking at this, and I think I've reached the limits of my ability to reason about PowerShell scopes, and I'm not sure I can really shed much more light on this I'm afraid :-S.

It definitely looks like it's related to the child scopes, though. To implement a Mock, Pester creates a randomly-named function in the appropriate scope (e.g. "PesterMock_cbaa9725-8267-4c27-8605-6a94eaf92de7" which ultimately calls your mock script block, and it then generates an alias for the function you're mocking which resolves to this function.

However, in the failing examples above the Pester-created function and the alias are in a different scope so the normal function definition gets called instead. (I also found that ```powershell.exe . ".\go.ps1"``` works with the "using dot-sourcing" example, probably for the same reason the others do).

Re the call operator, it looks like this creates a new child scope to execute the command in, so that might explain why it behaves the way it does...

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-6#call-operator-
> Call operator &
> Runs a command, script, or script block. The call operator, also known as the "invocation operator," lets you run commands that are stored in variables and represented by strings or script blocks. The call operator **executes in a child scope**. For more about scopes, see about_scopes.

Sorry I can't be much more help - you might need one of the project owners to response for a more comprehensive response.

Cheers,

M

**Comment by ili101** [comment]
@mikeclayton thank you!, I tried to investigate this to and got lost in the code (: 
Hopefully someone would solve this for us.

**Comment by nohwnd** [comment]
I think @ili101 has problem replicating the successful tests because this has a lot to do with scopes and session states, so maybe there is something that @mikeclayton has imported that @ili101 does not have. Are you both able to replicate / not replicate this in clean session?
---

From what I see the original example does not work because the mock places the function and alias outside of the module, but the call is made from the inside of the module. That means that the original command is picked up, instead of the alias. The session state from which the *call* is made is where you should mock the command for the mock to work correctly. 

Then the dot-sourcing or invoking of the test script should not have much effect, because you are doing that with the test script and the test script is pretty self-contained. 

The problem should not be related to child scopes, running it with . will import it to the current scope, running it with & will run it in child scope, but child scope still can see all the functions and aliases in the parent. And running it with `powershell` will run it in a different process, so if the executed script is not self contained it will not work anyway. 

It is most definitely a session state related "issue". To me the solution provided with ModuleName is valid and should work, and that it works the other way is accidental because you are importing the module multiple times.

Maybe I can take another look in few days, and try it out to see what you are trying to do and what is actually happening :)

**Comment by ili101** [comment]
@nohwnd both of us were able to replicate the working and failing situations.
> The session state from which the call is made is where you should mock the command for the mock to work correctly.

It is in both the working and failing situations. The Import of the module, the `Mock` command and the call to the module function `Invoke-MockedFunction` are all done in `TestFile.ps1`
> and that it works the other way is accidental because you are importing the module multiple times.

The module is being imported only once which is in the beginning of `TestFile.ps1`

Here is a simplified example:
**TestModule.psm1**
``` powershell
function Invoke-MockedFunction {
    [CmdletBinding()]
    param()
    Write-Warning 'Mock Failed!'
}
```
**TestFile.ps1**
``` powershell
Import-Module ".\TestModule.psm1"
Describe 'Test' {
    Context 'Context' {
        It "Mock Test" {
            Mock -CommandName 'Write-Warning' -MockWith { Write-Host 'Mock Seceded!' }
            Invoke-MockedFunction
        }
    }
}
```
If you execute `powershell.exe -File ".\TestFile.ps1"` (Or alternatively run `. ".\TestFile.ps1"` from a clean session) Mock will work.
If you execute `powershell.exe ".\TestFile.ps1"` (Or alternatively run `& ".\TestFile.ps1"` from a clean session) Mock will fail.

**Comment by nohwnd** [comment]
Okay, thanks for the simpler repo. I might be a bit off in my explanation then. This is very weird, and I don't see what exactly is the problem here right now.

**Comment by SqlSusan** [comment]
Having the exact same issue. dot sourcing works just fine, Invoke-Pester seems to forget all about the mocked functions. I'm attempting to mock "Get-Process", seemingly defining the module name in the mock statement causes it fail altogether. Seems like a bug tbh.

**Comment by SunnyOswal** [comment]
i am having same issue. Workaround shared by @mikeclayton works. thanks.

**Comment by mickjmason** [comment]
Just adding some more examples.  I'm using Version 4.10.1 (controlled by my employer and I can't update it).

I'm doing this:
`Import-Module -Name FakeModule
InModuleScope  FakeModule {...
`

If I execute my tests with `invoke-pester .\tests\tests.ps1` then **some** of the Mocks don't work (many do).  If I use the ISE or VSCode debuggers, or dot source the test.ps1 script, they work as expected.

One of the Mocks that fails is for `Test-Path {$true} -ParameterFilter {$Path -eq "c:\fakepath"}`
a very similar Mock that only differs in the path variable works elsewhere.

The other Mock that seems to be ignored is `Copy-Item {}`

I've tried adding -ModuleName to the Mocks that are ignored with invoke-pester, but it doesn't help.

Out of curiosity, i've just tried moving the Describe block that contained the failing Mocks to the top of my test script.  They no longer fail when executing with invoke-pester.  I then moved the describe block back to it's original position.  The still do not fail when using invoke-pester.

Perhaps by moving them around i've fixed a closing brace that was in the wrong position and therefore changed the scope.  I'm not convinced that is the case as adding or removing braces causes errors in VSCode.

¯\_(ツ)_/¯

**Comment by nohwnd** [comment]
@fflaten  Looking at this again to understand what is happening. 

Trying this on 4.8.1 in powershell 7, this is the code we run (twice actually), and we run in script scope:

```powershell 

            $scriptBlock = {
                $setAlias = & (Pester\SafeGetCommand) -Name Set-Alias -CommandType Cmdlet -Module Microsoft.PowerShell.Utility
                & $setAlias -Name $args[0] -Value $args[1] -Scope Script
            }

            $null = Invoke-InMockScope -SessionState $Mock.SessionState -ScriptBlock $scriptBlock -ArgumentList $aliasName, $Mock.BootstrapFunctionName
```

 I stop on the } after setting the alias and try the next steps.

I see that we are setting the alias in the correct session state. And we are not in the top level scope of that session state either. 


```powershell 

[DBG]: PS>  $ExecutionContext.SessionState


Drive                         : System.Management.Automation.DriveManagementIntrinsics
Provider                      : System.Management.Automation.CmdletProviderManagementIntrinsics
Path                          : System.Management.Automation.PathIntrinsics
PSVariable                    : System.Management.Automation.PSVariableIntrinsics
LanguageMode                  : FullLanguage
UseFullLanguageModeInDebugger : False
Scripts                       : {*}
Applications                  : {*}
Module                        :                  # <- this is empty we are in script scope
InvokeProvider                : System.Management.Automation.ProviderIntrinsics
InvokeCommand                 : System.Management.Automation.CommandInvocationIntrinsics


[DBG]: PS> set-alias -name abc -value write-warning -Scope script 

# grab the alias from test module scope and it is there (this differs if you use &)
[DBG]: PS> & (get-module testmodule) { get-command abc -all } 


CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           abc -> PesterMock_bd74b0e1-daf7-47ef-a92e-e14f3d6…

```

```powershell
# $Error variable is only defined in the top scope we are not in the top scope in either of those
[DBG]: PS> get-variable error -scope 0 -ErrorAction Ignore                              

# $error is 4 scopes above
[DBG]: PS> get-variable error -scope 4 -ErrorAction Ignore


Name                           Value
----                           -----
Error                          {Cannot find a variable with the name 'error'., The term 'flll' is not recognized as a name of a cmdlet, function, script file, or executable program.…

[DBG]: PS> & (get-module testmodule) { get-variable error -scope 0 -ErrorAction Ignore }

# $error is 2 scopes above
[DBG]: PS> & (get-module testmodule) { get-variable error -scope 2 -ErrorAction Ignore }


Name                           Value
----                           -----
Error                          {The scope number '4' exceeds the number of active scopes. (Parameter 'Scope')…
```

So this looks like a bug in powershell where using -Scope Script when creating the alias and dot-sourcing will make the alias global instead. 


If this turns out to be problem in v5, maybe we can work around this by using numbered scope. Or maybe just defining anything in the top scope makes it global because maybe powershell considers script == global scope when dot sourcing? 

Have to experiment with this a bit more.
