### ISSUE TITLE
Improve VS code problem matcher

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1452]
Skipping problem matching in the current implementation of VSCode integration. enable vscode marker and options.

**Comment by fourpastmidnight** [comment]
For the Gherkin side of things, I have improved how errors are reported so that problem matchers are easily created. This is part of #1276, which I've come back here to once again attempt to get merged. One of the comments on that PR show the problem matchers I'm using for the Gherkin side of things.

Perhaps similar code or problem matchers would work for the RSpec runner?
