### ISSUE TITLE
5.0 breaking change - missing -PesterOption parameter

### ISSUE THREAD

**Issue by rkeithhill** [pester/Pester#1478]
## 1. General summary of the issue

The posh-git module uses this VSCode task command to run its Pester tests and it fails on 5.0 with the missing parameter error:
```
04-05 12:08:33 13> Invoke-Pester test -PesterOption @{IncludeVSCodeMarker=$true}
Invoke-Pester: A parameter cannot be found that matches parameter name 'PesterOption'.
```

## 2. Describe Your Environment

```
Pester version     : 5.0.0 C:\Users\Keith\Documents\PowerShell\Modules\Pester\5.0.0\Pester.psd1
PowerShell version : 7.0.0
OS version         : Microsoft Windows NT 10.0.18363.0
```

## 3. Expected Behavior

Sort of expected Pester to continue to support this parameter.

## 4.Current Behavior

Errors because the parameter is no longer supported.

## 5. Possible Solution

Seems like Pester would still support some of these invocation options like `IncludeVSCodeMarker=$true` where the output is in a guaranteed form that the VSCode extension with its $Pester problem matcher can find error info like message, file, line.

## 6. Context

Running posh-git Pesters tests from the PowerShell 7 console.  Just testing how these tests behave on Pester v5.

**Comment by rkeithhill** [comment]
BTW, good thing this bumps the major version to indicate breaking changes. On posh-git - with no changes to the tests - all 129 tests fail.  :-(

**Comment by rkeithhill** [comment]
BTW, as part of porting, folks may find this VSCode regex for find & replace helpful (match sure to enable regex in the VSCode Find & Replace box):
```
Find:    Should\s+(?=[^-])
Replace: Should -
```

**Comment by nohwnd** [comment]
Thank you for raising this, the vscode marker switch moved to Pester Configuration object see [Advanced Interface](https://github.com/pester/Pester/blob/v5.0/README.md#advanced-interface), and is present uder Debug section, but it is not implemented. At one point there was a bug in powershell extension for vscode that prevented the squigglies from showing up, and that was just when I was looking at it, while implementing the new code lens. 😀 I am comitted to making the VSCode experience for Pester better, and after a brief talk with Travis think it's better to detect it from the env variables, so that switch will be removed in the future. Do you need it for some other reason than to integrate with VSCode?  

The regex is nice. Migration from the legacy syntax is described in [Migrating from Pester v3 to v4](https://pester.dev/docs/migrations/v3-to-v4), including similar regex, and more guidance.

Added both points to the breaking changes.

**Comment by rkeithhill** [comment]
As long as the $Pester problem matcher in the VSCode extension can be made to work with v5, I'll be happy.  :-)

**Comment by fflaten** [comment]
> As long as the $Pester problem matcher in the VSCode extension can be made to work with v5, I'll be happy.  :-)

About that... I'll just leave this reminder here. 😁
https://github.com/PowerShell/vscode-powershell/pull/2998

**Comment by fflaten** [comment]
Issue solved? Pester 5 tests should work in the next vscode-powershell release.
