### ISSUE TITLE
5.0 breaking change - missing -TestName parameter

### ISSUE THREAD

**Issue by rkeithhill** [pester/Pester#1479]
## 1. General summary of the issue

I'm trying to run a specific test to debug my port to 5.0 and I'm at a loss as to how I run that specific test since the TestName parameter is gone.  

## 3. Expected Behavior

I expect to be able to run a particular test by using the TestName parameter to specify that test.  Not having this will also likely break the VSCode PowerShell extension's capability to run/debug individual Pester tests.

```
Pester version     : 5.0.0 C:\Users\Keith\Documents\PowerShell\Modules\Pester\5.0.0\Pester.psd1
PowerShell version : 7.0.0
OS version         : Microsoft Windows NT 10.0.18363.0
```

## 4.Current Behavior
Erros because there is no longer a `TestName` parameter.
```
04-05 13:10:17 3> Invoke-Pester .\DefaultPrompt.Tests.ps1 -testname 'Default Prompt WindowTitle Tests'
Invoke-Pester: A parameter cannot be found that matches parameter name 'testname'.
```

## 5. Possible Solution

Add back the `TestName`  parameter.

## 6. Context

I'm trying to debug individual test cases as I port from Pester v4 to v5.

**Comment by nohwnd** [comment]
Thanks for raising this issue, you are right the -TestName parameter is missing from the simple api, and that is imho an oversight caused by having `-Focus` in the api up until recently, so there was almost no need for `TestName`. The `-Focus` was removed because it was easy to commit it into your code base and run only a single test on your CI server. Leading you to believe that all your tests are passing while only one of them is. I am working on a better way to pin tests, similar to breakpoints, that will not be easy to commit in your repo, but still should be easy to use.

I will think about how to improve this, I am a bit reluctant to put TestName back into the simple api, because it is not safe to use with tests that expand variables in their names.

As a possible workaround please use one of these options:
- VSCode integration was improved, and now allows just a single test to be run, and debugged, see [VSCode improvements](https://github.com/pester/Pester/tree/v5.0#vscode-improvements). 

- Set a tag on the test, e.g. `It "Get-Emoji" -Tag Debug` and use `-Tag` filter on `Invoke-Pester`, see [Tags on everything](https://github.com/pester/Pester/tree/v5.0#tags-on-everyting)

- For a custom test script you could define the name filter using the `Filter` section on `PesterConfiguration` and provide it through the `-Configuration` parameter. See [Advanced interface](https://github.com/pester/Pester/tree/v5.0#advanced-interface). Problem is that the Name filter seems broken. I never use it and VSCode does not use it either. Filed 2 new bugs. 

#1483 
#1482

**Comment by rkeithhill** [comment]
Thanks for listing out the workarounds.  Please reconsider adding the `-TestName` parameter back.  I was actually doing my debugging from the console and being able to invoke a single test saves a lot of time particularly when you're debugging that test.  Also, I've used a number of unit test frameworks: nunit, mstest, xunit, gtest and they all have a way to allow you to specify a test name to execute.

As for the case where a variable name is used in the test name (I remember fixing this bug at one time on the VSCode Pester code lens), could you detect the use of variables in the name and emit an error when the test is executed?  I'm OK if I'm told that a test case cannot be run individually if its name has to be interpolated.  It would be nice if the error also told me how to use the Filter.Line trick to invoke the test without having to rely on the name.  A solution like this would make running individual tests easy for the 90% of us that don't use variables in our test case names. :-)

**Comment by nohwnd** [comment]
I would have to AST the file to confirm if there are any strings that are using variables, otherwise I am already getting the string expanded by powershell. The name filter has wildcards filter and works on the whole path joined by '.' (when that filter actually it works 😁). Imho just suggesting the filter for interactive use is good enough. The worst thing to happen is that you run less / more tests than intended. There are various other ways to do that. 🙂

What do you think about renaming the filter parameters to `-TagFilter`, `-ExcludeTagFilter`, `-NameFilter`? It would be still possible to use `-Tag` or `-ExcludeTag` but once I add `-Filter that takes a scriptblock it would align much nicer with the rest of the syntax.

**Comment by rkeithhill** [comment]
`-NameFilter` would be fine by me - I think - as long as the test case name is actually filtered against.  What does this mean exactly:

> works on the whole path joined by '.'

BTW gtest has a parameter that is called `--gtest_filter` and it allows for wildcards as well.

**Comment by nohwnd** [comment]
> works on the whole path joined by '.'

```powershell
Describe "a1"  { 
    Context "b1" { 
        It "i1" {
        }
    }
}
```
Path (fullname) to the test above would be "a1.b1.i1", and would use `-like` to do the matching. So for example "*i1", "*b1.i1", or "*b1".

**Comment by rkeithhill** [comment]
OK, that makes sense.  I thought maybe `path` could have been referring to the file's path.

**Comment by nohwnd** [comment]
Maybe that should also be renamed to FullName in the result object.

**Comment by rkeithhill** [comment]
I think `NameFilter` is OK for the parameter name but in the docs, be sure to specify that it allows filtering over the full name Describe.Context.It.  Another option, if you were to take a page from the gtest book is to call it `-TestFilter`.  Maybe that would allow for more filtering options like line number?

**Comment by nohwnd** [comment]
There is -FullNameFilter

**Comment by reemmadkour** [comment]
This still does not work. There is no work around to specify a specific it block when using Invoke-Pester -Configuration

**Comment by fflaten** [comment]
> This still does not work. There is no work around to specify a specific it block when using Invoke-Pester -Configuration

@reemmadkour It depends. If you have unique names, you can use `Filter.FullName` in the configuration object. E.g.

```powershell
$conf = New-PesterConfiguration
$conf.Output.Verbosity = 'Detailed'
$conf.Run.ScriptBlock = {
    Describe 'a1' { 
        Context 'b1' { 
            It 'i1' {
                1 | Should -Be 1
            }
            It 'i2' {
                1 | Should -Be 1
            }
        }
    }
}
$conf.Filter.FullName = 'a1.b1.i1'

Invoke-Pester -Configuration $conf

# output

Starting discovery in 1 files.
Discovery found 2 tests in 19ms.
Filter 'FullName' set to ('a1.b1.i1').
Filters selected 1 tests to run.
Running tests.
Describing a1
 Context b1
   [+] i1 6ms (1ms|4ms)
Tests completed in 86ms
Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 1
```

Known limitation: The filter is applied during discovery-phase, so if you use data-driven tests you can't target based on the expanded variables. See https://github.com/pester/Pester/issues/1891

Please open a new issue if you still have any questions :)

**Comment by reemmadkour** [comment]
@fflaten Thanks that works!
