### ISSUE TITLE
[v5] Consider moving "Discovering" messages to Output Diagnostic Level

### ISSUE THREAD

**Issue by JustinGrote** [pester/Pester#1552]
Because each test file name is shown in the "Running" section, the discovery section duplicates the information and leads to a "wall of purple" if you have tests in a lot of separate files
![image](https://user-images.githubusercontent.com/15258962/82133584-cabb7380-97a2-11ea-9411-74c8b72e6581.png)

However I don't want to go all the way to minimal, I want the "wall of green" of passing tests to watch progress and see how the performance of each test went.

Therefore, I think the discovery section on output normal should look like it does on output minimal (just that discovery started and completed, two lines) and then do the normal output. This would also be closer to what v4 users would expect on default which will ease the v4-v5 transition.

Here's a mockup of what I think Output Normal should look like:

![image](https://user-images.githubusercontent.com/15258962/82133614-179f4a00-97a3-11ea-9d96-d3a09ff75aa5.png)
![image](https://user-images.githubusercontent.com/15258962/82133618-238b0c00-97a3-11ea-95bb-de0341e98243.png)

**Comment by nohwnd** [comment]
Imho the Discovery is an important part of the new approach, and unlike your case where everything is done in <1s, because you did everything right. Some people might see discovery taking much longer on few files, and this output will help with the transition by identifying where they still have misplaced code. 

I could stop writing a new line after printing the file, because it is a serial operation, which would reduce the amount of lines written to the screen. 

But generally I understand your reasoning, and feel like this should be re-visited in few months / a year when Pester5 is more widely adopted.

**Comment by JustinGrote** [comment]
But I'm saying still preserve the discovery headers, so you can show someone their discovery took 20 seconds or whatever, and also still throw any discovery errors in this section. Then if they bump up to diagnostic (as you normally would in troubleshooting) you can then see the per file times to troubleshoot.

I get your point and this is a preference item so maybe I'll PR in a setting :)

**Comment by nohwnd** [comment]
> I get your point and this is a preference item so maybe I'll PR in a setting :) 
Noooooo! 😁 I am not adding 40 different settings for output, I plan to make the whole output replaceable, and this would only force the plugin authors to implement those options.

**Comment by iSazonov** [comment]
I like @JustinGrote because I am thinking about PowerShell repo where we have ~400 test files.

**Comment by nohwnd** [comment]
I am of course open to discussion, but would like to avoid changing a lot of stuff right before release, or releasing 20 more RC versions and never get to the 5.0.0 release. 🙂

**Comment by fflaten** [comment]
How has this issue mature? In current v5 versions, the default Normal-output only contains the summary from discovery as requested, but it also only outputs containers in green + failed tests which doesn't match the images in OP.

![image](https://user-images.githubusercontent.com/3436158/120526457-8284e880-c3d9-11eb-8467-2b4cde272a78.png)

Is this acceptable or did the discussion just move to Detailed-view which will also show the wall-of-green-tests, but then include all files (pre-filter) in the discovery-output? 🙂 
![image](https://user-images.githubusercontent.com/3436158/120526490-8b75ba00-c3d9-11eb-8f98-7f3b4ca030b8.png)

**Comment by nohwnd** [comment]
My current opinion on this is: 
- Move the discovery messages to the pester debug output so we only see them in diagnostics. This keeps Diagnostic consistent. Because it should be the same output as Detailed + Pester debug messages.
- Do not include the Filter in the default debug messages category (this will exclude them from being see in the diag output, but we can still enable them by setting showdebugmessages, and showdebugmessagesfrom). Or split them into Filter and FilterCore as the other logs do it, to show user only interesting info that is not overwhelming.

**Comment by fflaten** [comment]
Sounds good to me. 

I think part two about filter output should continue in #1746, but I do agree 👍

**Comment by nohwnd** [comment]
k. Smashed both into 5.3 because it seems like we have a clear plan.
