### ISSUE TITLE
v5: When using a Switch parameter the tests fails in certain circumstances

### ISSUE THREAD

**Issue by johlju** [pester/Pester#1576]
## 1. General summary of the issue

When running this this example it fails with the error `ParameterBindingValidationException: Cannot bind argument to parameter 'SessionState' because it is null.`

```
BeforeAll {
    Remove-Module -Name 'DscResource.Common' -Force
    New-Module -Name 'DscResource.Common' -ScriptBlock {
        function Assert-Module
        {
            [CmdletBinding()]
            param
            (
                [Parameter(Mandatory = $true)]
                [System.String]
                $ModuleName,

                [Parameter()]
                [System.Management.Automation.SwitchParameter]
                $ImportModule
            )

            if (-not (Get-Module -Name $ModuleName -ListAvailable))
            {
                $errorMessage = $script:localizedData.ModuleNotFound -f $ModuleName
                New-ObjectNotFoundException -Message $errorMessage
            }

            if ($ImportModule)
            {
                Import-Module -Name $ModuleName
            }
        }
    } | Import-Module

    $script:moduleName = 'DscResource.Common'
}

Describe 'Assert-Module' {
    BeforeAll {
        $testModuleName = 'TestModule'
    }

    Context 'When module is available' {
        BeforeAll {
            Mock -CommandName Import-Module -ModuleName 'DscResource.Common'
            Mock -CommandName Get-Module -MockWith {
                return @{
                    Name = $testModuleName
                }
            } -ModuleName 'DscResource.Common'
        }

        Context 'When module should be imported' {
            It 'Should not throw an error' {
                { Assert-Module -ModuleName $testModuleName -ImportModule } | Should -Not -Throw
            }

            It 'Should call the expected mocks' {
                Should -Invoke -CommandName Import-Module -Exactly -Times 1 -Scope Context
            }
        }
    }
}
```

## 2. Describe Your Environment

```powershell
Pester version     : 5.0.0 C:\source\DscResource.Common\output\RequiredModules\Pester\5.0.0\Pester.psd1
PowerShell version : 7.0.1
OS version         : Microsoft Windows NT 10.0.19041.0
```

## 3. Expected Behavior

Might do what is meant to do. 🙂 

## 4. Current Behavior

* If I remove the switch parameter `-ImportModule` from the call to `Assert-Module` the tests passes.
* If I remove the `-ModuleName 'DscResource.Common` from the `Mock`'s the tests passes.
* If I add a `-ModuleName 'DscResource.Common` to each `Should -Invoke` the tests passes.

## 5. Possible Solution

Might need some documentation since the error message is not very descriptive in this case.

## 6. Context

I worked around it by adding `-ModuleName 'DscResource.Common'` to the `Should -Invoke`.

For some reason the tests when running the particular test file individually and when I removed the  `-ModuleName 'DscResource.Common'` on the `Mock`'s. But running it through our CI pipeline that starts Invoke-Pester through `Invoke-Build` in a test task it failed with the below errors. Once I added the `-ModuleName 'DscResource.Common'` to the `Should -Invoke` the tests passed in the CI pipeline as well. 

```
Running tests from 'C:\source\DscResource.Common\tests\Unit\Public\Assert-Module.Tests.ps1'
Describing Assert-Module
 Context When module is not installed
   [+] Should throw the correct error 35ms (35ms|0ms)
 Context When module is available
  Context When module should not be imported
    [-] Should not throw an error 43ms (42ms|0ms)
     Expected no exception to be thrown, but an exception "System.Exception: Please ensure that the PowerShell module 'TestModule' is installed. (DRC0009)" was thrown from C:\source\DscResource.Common\output\DscResource.Common\0.9.1\DscResource.Common.psm1:1034 char:5
         +     throw $errorRecordToThrow
         +     ~~~~~~~~~~~~~~~~~~~~~~~~~.
     at { Assert-Module -ModuleName $testModuleName } | Should -Not -Throw, C:\source\DscResource.Common\tests\Unit\Public\Assert-Module.Tests.ps1:41
     at <ScriptBlock>, C:\source\DscResource.Common\tests\Unit\Public\Assert-Module.Tests.ps1:41
    [+] Should call the expected mocks 8ms (7ms|1ms)
  Context When module should be imported
    [-] Should not throw an error 38ms (37ms|0ms)
     Expected no exception to be thrown, but an exception "System.Exception: Please ensure that the PowerShell module 'TestModule' is installed. (DRC0009)" was thrown from C:\source\DscResource.Common\output\DscResource.Common\0.9.1\DscResource.Common.psm1:1034 char:5
         +     throw $errorRecordToThrow
         +     ~~~~~~~~~~~~~~~~~~~~~~~~~.
     at { Assert-Module -ModuleName $testModuleName -ImportModule } | Should -Not -Throw, C:\source\DscResource.Common\tests\Unit\Public\Assert-Module.Tests.ps1:51
     at <ScriptBlock>, C:\source\DscResource.Common\tests\Unit\Public\Assert-Module.Tests.ps1:51
    [-] Should call the expected mocks 8ms (8ms|1ms)
     Expected Import-Module to be called 1 times exactly but was called 0 times
     at Should -Invoke -CommandName Import-Module -Exactly -Times 1 -Scope Context, C:\source\DscResource.Common\tests\Unit\Public\Assert-Module.Tests.ps1:55
     at <ScriptBlock>, C:\source\DscResource.Common\tests\Unit\Public\Assert-Module.Tests.ps1:55
```

**Comment by fflaten** [comment]
Might be a rookie question since I'm not very experienced with mocks, but.. 
> If I remove the -ModuleName 'DscResource.Common from the Mock's the tests passes.

Why would you use `-ModuleName 'DscResource.Common'` when you create mocks for cmdlets like `Get-Module` and `Import-Module` which aren't internal to your module but actually belongs to a different module? The mocks should get cleaned up after the context is done, so I wouldn't expect it to be required to avoid pollution.

As long as you specify a module to implement your mock in, then you should also specify it while running the invoke assertion as the ModuleName-parameter affects the scope (inside or outside your module's private scope/world) of where Pester can both create the mock and later on look to find it again during the assertion. Giving them different scopes/worlds to work in is like asking for trouble.

Better yet, simply remove the parameter both places as you're not mocking an internal function inside the 'DscResource.Common' module.

I do agree that the error is confusing and there might also be a bug here, but it primarily feels like a user error. Maybe I'm wrong, if so please correct me so I can understand this better! 🙂 

**Troubleshooting**

The exception occurs during the call to `Test-ParameterFilter` in `Should-InvokeInternal`. It fails because `$ContextInfo.Hook.CallerSessionState` is null which is normal since `$ContextInfo` actually belongs to the original `Import-Module`-cmdlet and `Hook` is a mock-only property. Since you didn't specify a `ModuleName `in `Should -Invoke`, it resolved `Import-Module` in the caller state ("normal" scope) where only the cmdlet exists (your mock only exists inside your module).

What is a bit confusing to me is that when the mock is registered in Pester, it's stored as a "non-module function" due to
https://github.com/pester/Pester/blob/8d555269cfcd8e3aee13d1efb10f962afc922f96/src/functions/Mock.ps1#L36
The result is that the mock is registered as "||Import-Module" and not something like "DscResource.Common||Import-Module" in the mock list and in the call history/log for mocks.

Later on, `Should -Invoke` looks through the call history/log for mocks and falsely matches the resolved command (original cmdlet) with the mock's entries in the call history possibly due to the generic naming-situation above. When it goes through each entry in the history/log to see if the call matches your ParameterFilter (even thought it's blank in this case) it breaks because `Test-ParameterFilter` doesn't expect contextinfo belonging to a non-mock command. This is waaay beyond my knowledge, so @nohwnd would have to clear up troubleshoot the exception any further.

_Side-note: It probably doesn't make the situation any easier that `Microsoft.PowerShell.Core` isn't considered a module which makes `(Get-Command Import-Module).Module.Name -eq $null`, considering the `Module.Name` parameter is used in some of the mock logic._

```powershell
PS > Get-Command Import-Module | fl Module*
ModuleName : Microsoft.PowerShell.Core
Module     :
```

**Comment by johlju** [comment]
Let's close this as I too feel this was user error du to lack of knowledge. I know better now. 🙂  `ModuleName` should never been on those mocks and removing them solves the problem with the reproducible code above.
