### ISSUE TITLE
Mock Get-ADUser - access all properties

### ISSUE THREAD

**Issue by hjorslev** [pester/Pester#1600]
## 1. General summary of the issue

If I run Get-ADUser I will need to specify the parameter -Properties to access all that are not included in the default set.

I am attempting to mock the property AccountExpirationDate, but I get the error as described in section 4.

## 2. Describe Your Environment
```
Pester version     : 5.0.2 C:\Users\frede\OneDrive\Documents\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psd1
PowerShell version : 5.1.18362.752
OS version         : Microsoft Windows NT 10.0.18363.0
```

## 3. Expected Behavior

```powershell
Describe 'Test-User' -Tag 'User' {
    BeforeAll {
        if (-not (Get-Module -Name ActiveDirectory)) {
            Import-Module "$env:BHProjectPath\Tests\Lib\ActiveDirectory.psm1" -Force
        }
    }

    It 'AccountExpiration' {
        Mock -CommandName Get-ADUser -MockWith {
            New-Object Microsoft.ActiveDirectory.Management.ADUser Identity -Property @{
                SamAccountName        = 'fhp'
                AccountExpirationDate = (Get-Date -Format '01/01/1999')
            }
        }
        Test-User -UserName 'fhp' | Should -Not -BeNullOrEmpty
    }
}
```

## 4.Current Behavior

```
[-] Test-User.AccountExpiration 382ms (372ms|9ms)
 InvalidOperationException: The member "AccountExpirationDate" was not found for the specified .NET object.
 CmdletInvocationException: The member "AccountExpirationDate" was not found for the specified .NET object.
 ParameterBindingValidationException: Cannot validate argument on parameter 'UserName'. The member "AccountExpirationDate" was not found for the specified .NET object.
 at <ScriptBlock>, C:\Users\frede\support_scripts\SupportTools\Tests\Public\User\Test-User.Tests.ps1:15
```

## 5. Possible Solution

Not sure...

## 6. Context

I would like to mock the property AccountExpirationDate.

**Comment by nohwnd** [comment]
I don't see AccountExpirationDate on the [ADUser type](https://docs.microsoft.com/en-us/dotnet/api/microsoft.activedirectory.management.aduser?view=activedirectory-management-10.0), so the error is what the exception message says. You are trying to set a property that does not exist directly on the type. 

Maybe the property is added by PowerShell as part of the extended type system, so maybe you just need to create the object. And then set it using . notation, instead of using -Property on New-Object. 

Or maybe the property is present only if you do a query and use -Property, I would try that, and look at the type of the property by Get-Member, and replicate that in your mock. 

$u = Get-AdUser -Property AccountExpirationDate ....
$u | Get-Member -Name AccountExpirationDate

Look at the output...

$mockObject | Add-Member -Name AccountExpirationDate ...etc.

**Comment by hjorslev** [comment]
Yes, that solution worked:
```powershell
Mock -CommandName Get-ADUser -MockWith {
	$UserObject = New-Object Microsoft.ActiveDirectory.Management.ADUser -Property @{
		SurName           = ''
		Name              = ''
		UserPrincipalName = ''
		GivenName         = ''
		SamAccountName    = ''
		Enabled           = $true
		ObjectClass       = 'user'
		SID               = 'S-1-5-21-2889043008-4136710315-2444824263-3544'
		ObjectGUID        = 'e1418d64-096c-4cb0-b903-ebb66562d99d'
		DistinguishedName = ''
	}
	$UserObject | Add-Member -MemberType 'NoteProperty' -Name 'AccountExpirationDate' -Value ([DateTime]::ParseExact('01-01-1999', 'dd-MM-yyyy', $null))
	Write-Output -InputObject $UserObject
}
```

Thanks for your help!
