### ISSUE TITLE
$StartLine fallback

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#1673]
Maybe the $StartLine should be nullable and fallback to $ScriptBlock.StartPosition.StartLine when the value is not provided? That way I am way less likely to run into this when I implement some other LineFilter and test it in the Runtime, but not RSpec implementation? 

Another option would be to fallback to $MyInvocation of the New-* command, but that seems like a worse thing to do.

_Originally posted by @nohwnd in https://github.com/pester/Pester/pull/1664#r482717661_

**Comment by nohwnd** [comment]
@fflaten moved the comment here, it was not needed for the PR and I wanted to release it.

**Comment by fflaten** [comment]
$MyInvocation would give us the position for the call to New-* inside, not It/Describe/Context. Which is why the Get-PSCallStack alternative was mentioned in the PR.

I agree that it should probably fallback to the previous behavior to always have a value. The usual implementations (It/Describe/Context) will behave in the new way anyways and a simple PSBoundParameters-check in New-Test/Block won't cost much to save some headache for custom scenarios. Will let us move the RerunFailed.tests.ps1 back into Pester.Runtime.ts.ps1 as well.

Should I make a PR?

**Comment by nohwnd** [comment]
> $MyInvocation would give us the position for the call to New-* inside, 
And that is exactly what I want. To keep New-Test / New-Block to be safe to call, when I use it in more tests.

**Comment by fflaten** [comment]
I see. By using startposition of the scriptblock, we should be able to cover both direct usage of new-test/block and future alternatives to it/context/describe that forgets to specify startline. Best of both worlds 👍

**Comment by fflaten** [comment]
I've created a PR with a suggested solution and reverted changes to a test which covers your scenario.

**Comment by nohwnd** [comment]
Thx, commented.
