### ISSUE TITLE
Variables defined in BeforeAll not populated in the IT description text

### ISSUE THREAD

**Issue by arcanecode** [pester/Pester#1689]
## 1. General summary of the issue

This is the code sample that demonstrates the issue:

```powershell
Describe -Tags ('Unit', 'Acceptance') "DataFabricator Module Tests"  {

  BeforeAll {
    $module = 'DataFabricator'
    $here = Split-Path -Parent $PSCommandPath

  Context 'Module Setup' {

    It "$module has the root module $module.psm1" {
      "$here\..\$module.psm1" | Should -Exist
    } # It

  } # Context 'Module Setup' 

} # Describe -Tags ('Unit', 'Acceptance') "DataFabricator Module Tests" 
```

When executing the tests, the "It $module has the root module $module.psm1" only displays " has the root module .psm1" in the output. However, variables defined in BeforeAll work fine inside the code block passed to It. The test does pass, as my DataFabricator.psm1 file does exist.

I'm not sure if this is by design, or a bug.

## 2. Describe Your Environment

Pester version     : 5.0.4 C:\Users\arcan\OneDrive\Documents\PowerShell\Modules\Pester\5.0.4\Pester.psd1
PowerShell version : 7.0.3
OS version         : Microsoft Windows NT 10.0.19041.0

## 3. Expected Behavior

Expected output to read "DataFabricator has the root module DataFabricator.psm1"

## 4.Current Behavior

Returns " has the root module .psm1" in the output

## 5. Possible Solution

Allow the use of variables within the It descriptor (having it for the Context block as well would be useful)

## 6. Context

I was attempting to provide more context in the output for tests as they run.

As I indicated, I'm not sure if this is due to the new redesign, or an actual bug. If it is due to the new design, is it something that could be addressed?

**Comment by nohwnd** [comment]
That is because the BeforeAll won't run until the `Run` phase. But the text is expanded during `Discovery` because you are using double quoted string. With Pester 5.1.0-beta1 you could use "<module>" and it should work correctly.

**Comment by arcanecode** [comment]
Just confirming, using 5.1.0-beta1 using "<module>" or any other variable name in < > works fine, it correctly expands the variable into the space.

Just out of curiosity, is there a difference between single and double quotes when using the < > syntax. I haven't seen one, but am wondering if the rules of string interpolation should apply to these replacements as well, and only replace within double quotes.

**Comment by nohwnd** [comment]
There are differences, but Pester can't see them because once expanded by the PowerShell engine, the string is just a string. There are not metadata on it that would describe how it was produced, if as a literal from `'this is a cow'` or as expanded string like `"this is $animal"`. If `$animal` is not in scope when the string is expanded, Pester will see only `this is ` string.

So what our expansion does is that it escapes all `` ` `` and `$` with an extra `` ` `` to preserve it through the expansion, and then replaces `<abc>` with `$abc` and expands it.  This way if Pester sees `value <value> should be $null` it will spit out `value 10 should be $null` and not  `value 10 should be `.
