### ISSUE TITLE
A happy report on Pester 5.1.0 Beta 2 on Multiple Platforms

### ISSUE THREAD

**Issue by arcanecode** [pester/Pester#1711]
This isn't an issue, but a happy report on report on using Pester on multiple platforms.

I've created a new module called DataFabricator. It's goal is to fabricate fake but realistic looking data like names, addresses, phone numbers, company names, and more.

I used Pester 5.1.0 Beta 2 to test it. So far I've tested on these platforms:

- Windows 10 (current version)
- macOS Catalina 10.15.7
- macOS Big Sur 11.0 Beta 9
- Ubuntu 20.04
- Ubuntu 20.10 Beta

It worked great on all platforms. It took a while to write the tests, but having them made testing on all these platforms go quickly.

If you want to see my tests, they are on my GitHub site: [DataFabricator](https://github.com/arcanecode/DataFabricator). They are pretty straight forward, mostly I used Be, Contains, and Match.

I'll be putting the DataFabricator on PSGallery in the near future, but for now you can clone the repository if you want to play with it.

I did discover one oddity that I think is more of a PowerShell issue. I have a function `Get-AboutDataFabricator`. It originally just displayed a here string with info about the DataFabricator.

In the test, I just copied the same here string into the test, and used Should Be to compare the two. It failed, because the here string in the function had carriage return / line feed (\r\n) in it, but the here string within the test only had line feeds (\n). As a result the test failed.

I worked around it with what I think wound up being a better idea. I store the message in a text file, then use Get-Content -Raw to load the message in both the function and in the test. This will make it easier to update the message in future, and the test passed as both matched.

Not sure if there needs to be a switch on Be to do carriage return / line feed insensitive or not, but just a suggestion.

Ubuntu 20.10 will be released on Oct 22, and I'll do another set of tests on it then. Big Sur is due out anytime now. Apple has announced a special event on Oct 13, my guess is they'll be announcing Big Sur's release, either on the 13th or within a few days after it.

**Comment by nohwnd** [comment]
Thanks for the report, Pester is running it's tests on all major OS versions, even though not all the versions that you listed, so I would be pretty bummed if it did not work 🙂

> I worked around it with what I think wound up being a better idea. I store the message in a text file, then use Get-Content -Raw to load the message in both the function and in the test. This will make it easier to update the message in future, and the test passed as both matched.

That sounds like it's harder to read the test now. And if it is now easier to update the message, maybe it is shared by too many tests? 

I would guess your problem is caused by git configuration rather than powershell. Sounds like one of your files has line endings standardized while the other does not. Just in case you'd need it, here is awesome talk on git, and line endings. https://www.youtube.com/watch?v=VxmL6g9uy-A&ab_channel=NDCConferences

> I'll be putting the DataFabricator on PSGallery in the near future, but for now you can clone the repository if you want to play with it.

I quickly looked through few of your tests and found few smaller things.

https://github.com/arcanecode/DataFabricator/blob/master/Tests/ConvertFrom-CityStateCode.Tests.ps1

Putting all your expected values into `BeforeAll` makes this unnecessarily difficult to read. You have to lookup every variable value, instead of just reading it directly on that line. Plus there is a chance that the variable will have incorrect value. 

Using subexpression `$()` instead of just `()` is a bit unusual, and I was wondering if there is any point to it, but I don't see any. 

I would avoid calling the function twice when I put two Shoulds in the same test, that would help me ensure that I don't make a typo in one of those calls and get a false positive.

https://github.com/arcanecode/DataFabricator/blob/5bd388d59c10e5c130e4defa16591fd5659568f6/Tests/Get-FabricatedCity.Tests.ps1#L20-L25

Here you define $here (which is unnecessary, because $PSScriptRoot is automatic variable. And then you don't use it. 

https://github.com/arcanecode/DataFabricator/blob/master/Tests/Get-FabricatedPostalCode.Tests.ps1#L67

Do you find this type of comment actually helpful? 🙂 To me it's just waiting to get outdated, and does not help ensure that the scope is correct, when misplaced `}` is present. so to me it's just noise. But I saw it in few places, and always wondered why people bother with it.
