### ISSUE TITLE
Debugging generated tests takes for ever due to the output of filter commands

### ISSUE THREAD

**Issue by simonsabin** [pester/Pester#1746]
## Summary of the feature request

If I'm generating tests (100s due to permutations), when you try and debug them, the discovery phase outputs lots of FILTER .... diagnostic information, and thats really slow.  takes minutes to output them all event though discovery in non debug mode is 1second

## How should it work? (optional)
Provide some way to prevent the display of the FILTER messages.

**Comment by nohwnd** [comment]
You can disable the output in VSCode by setting the Debug Output Verbosity to Detailed (or whatever you like). You will lose the diagnostic output on debugging though. Maybe the Filter could reduced just to output tests that are filtered out? 

You can also use $PesterPreference.Debug section to set the logging however you like.

**Comment by simonsabin** [comment]
Yep got that and as you say it is all or nothing. It appears the outpouring of the message is really slow. Each one takes a time, is that vs code or pester?
I thought the setting in settings overrode everything. Is also found setting debug preferences ended up throwing an error about something that should never happen, the message said this can happen when preferences is different in different scopes

**Comment by simonsabin** [comment]
I wonder if there is scope for two options debug and debug with verbosity.

**Comment by nohwnd** [comment]
> Yep got that and as you say it is all or nothing. It appears the outpouring of the message is really slow. Each one takes a time, is that vs code or pester?

It's partly pester becuase it determines in every function if Write-PestertDebugMessage should write to screen, and there is a bunch of messages that are never written but still pay the cost of calling the Write-PestertDebugMessage function. The  Write-Host is called when the message is written and that is really slow in general, and it's even slower in VSCode. I would say it's 20% pester and 80% Write-Host.

> I thought the setting in settings overrode everything. Is also found setting debug preferences ended up throwing an error about something that should never happen, the message said this can happen when preferences is different in different scopes

Do you have a repro for that? That message is coming from Write-PestertDebugMessage, because I want every call to that function to be wrapped in `if` to avoid the cost of function call when not in debugging mode.

> I wonder if there is scope for two options debug and debug with verbosity.
No plan for that at the moment, it would have to map to yet another output level, or set the output level using Pester preference. You can PR it to vscode if you have time to figure out what would be the best settings. But I guess you'd be reducing the amount of info that is output using the Diagnostics output, so that change would have to be adopted into Pester as well.

**Comment by nohwnd** [comment]
Will move filter out of the default list of debug messages, or split them to Filter and FilterCore if there are some that you really should see, but most of the noise will be hidden to make it less overwhelming.

**Comment by simonsabin** [comment]
I like that.

**Comment by fflaten** [comment]
> or split them to Filter and FilterCore if there are some that you really should see, but most of the noise will be hidden to make it less overwhelming.

What would qualify as important? Filters for successfull match?
Ex. in my demo the original 27 lines of Filter-output would become:

```
Filter: (MyLargeFunction.When running first code path.When running alternate code path.Should happen) Test is included, because it's tag 'Test' matches tag filter 'Test'. 
Filter: (MyLargeFunction.When running second code path) Block is included, because it's tag 'Test' matches tag filter 'Test'. 
Filter: (MyLargeFunction.When running second code path.Should happen) Test is included, because its parent is included. 
Filter: (MyLargeFunction.When running second code path.Should call all verifiable mocks) Test is included, because its parent is included. 

```

**Comment by nohwnd** [comment]
I think how much that will reduce just depends on your usage of tags. If you include 'Acceptance' tests by a tag you have the same problem. I was thinking more like a general info that we don't repeat for every test. But I don't see any here, so this will probably all be hidden.

**Comment by fflaten** [comment]
**Tag-events**
Yeah, the last picture is include-/excludetag specific duplicates. Don't see the same repeated "there is .. filter" with fullname or line. If you specify both includetag and excludetag, those duplicates amount to **1/3 (!)** of the Filter-messages currently. To be consistent we should remove them (users can rely on the discovery-messages at the top mentioning active filters) or add similar debugmessages for active fullname/line-filters to keep them close while diagnosing. Either way, it shouldn't be shown by default in Diagnostic as it's noisy. :) 

**General filter-output**
The part about having a FilterSuccess/FilterCore by default in Diagnostic to only show "included because active filter or parent" is a generic improvement though. Ofc. if you run with filters that matches 100+ tests that will still be many events, but only 5-15% of current volume depending on filters used. If a user is using Diagnostics they might expect some info, if not then we can disable all filter debug by default as there's not really much left to show no already covered during discovery (see below)

Do you have a example of the "general info"? I thought that was pretty much covered in the discovery-messages.
```
Pester v5.3.0-alpha4

Starting discovery in 1 files.
Filter 'Tag' set to ('test').
Discovering in C:\Users\Frode\Git\Pester\Samples\demoIssue1814.tests.ps1.
Found 8 tests. 14ms
Discovery finished in 31ms.
Running tests.
```
Maybe add a message about number of tests after filters have been processed before "Discovery finished .."? However that output might be just as useful for the detailed view to clarify before/after filters and would be a discovery-message like the "filter .. set to .." messages and not a debugmessage.

**Comment by nohwnd** [comment]
Yes I agree, I did not see any non-general info from the tag that I might want to stay.

**Comment by fflaten** [comment]
Should I submit a PR or are you already on it?

**Comment by nohwnd** [comment]
I did not start on it.

**Comment by simonsabin** [comment]
Thanks for addressing this, is there a separate point about the speed of "debug" messages in VSCode. One of the reasons for the issue was the time it takes to output especially when you've loads of tests. Is that a pester thing, a powershell thing or a VS code thing?

**Comment by nohwnd** [comment]
It's powershell thing. Write-Host is slow, and there are a lot of filter messages so it takes time. 

```powershell
$fs = 1..1000
$wh = Measure-Command { $null = foreach ($f in $fs) { Write-Host $f } }
$c = Measure-Command { $null = foreach ($f in $fs) { [Console]::WriteLine($f) } }
$n = Measure-Command { $null = foreach ($f in $fs) { $f } }
"Write-Host: " + $wh.TotalMilliseconds
"Console: " + $c.TotalMilliseconds
"None: " + $n.TotalMilliseconds
```

Write-Host: 295.2234
Console: 50.6269
None: 3.2287

**Comment by simonsabin** [comment]
I assume Console WriteLine isn't great for non interactive situations?

**Comment by nohwnd** [comment]
I think it would be mostly fine for us to move to use console.writeline exclusively. I am just not sure if people are redirecting the output or not. Also in normal output we report pretty much 1 line per file, so the difference is negligible. 

On the other hand when you enable Diagnostic the whole execution gets additional performance hit, because we check for every debug message if we should write it by calling a function and checking a list of options. Just calling a function is much much slower than the if condition that we do normally. So those tiny hits add up and the whole execution gets much slower.

https://github.com/pester/Pester/blob/40501acbc107daf31f07c803ec77bff9debe6f4c/src/Pester.Utility.ps1#L260-L332

Probably moving the code that figures out whether to write the message at all to C# would help to greatly reduce the cost of enabling the debug messages, even if we still wrote them using write-host.
