### ISSUE TITLE
[5.1.0 RC1] CI parameter causes PowerShell to crash, Exit Code 14

### ISSUE THREAD

**Issue by wsmelton** [pester/Pester#1769]
## General summary of the issue

PowerShell is crashing with exit code 14 when I include the `-CI` parameter to `Invoke-Pester`. If I don't include it then PowerShell does not crash.

This repeats in VS Code Insiders and Windows Terminal

## Describe your environment

```
Pester version     : 5.1.0-rc1 C:\Program Files\WindowsPowerShell\Modules\pester\5.1.0\Pester.psm1
PowerShell version : 5.1.19041.546
OS version         : Microsoft Windows NT 10.0.19041.0
```

VS Code Insiders (latest)
Windows Terminal Preview 1.4.2652.0

## Steps to reproduce

1. Import module and Pester 5.0.1
1. Run tests `Invoke-Pester <tests file> -Output Detailed -CI`
1. I see `coverage.xml` generate
1. Output in the window shows the `Tests Passed...` line and then pauses
1. PowerShell exits with `exit code 14`

If I remove the `-CI` parameter it does not do it.

![image](https://user-images.githubusercontent.com/11204251/98822337-5599c580-23f6-11eb-8f95-d86574016a38.png)

```powershell
    #My code
```
-->

## Expected Behavior

CI does not cause PowerShell to crash.

## Current Behavior

Exit code 14 is received with PowerShell process closing

**Comment by fflaten** [comment]
This is by design. `-CI` is meant to be used in a CI pipeline as a shortcut for multiple options, including `Run.Exit = $true` which causes this. It also enables testresults and codecov. Try [Advanced Interface/Configuration](https://github.com/pester/Pester#advanced-interface) if you only need code coverage and test-results etc.
