### ISSUE TITLE
Should -Not -InvokeVerifiable not working

### ISSUE THREAD

**Issue by bradchristie-velir** [pester/Pester#1779]
## General summary of the issue
Attempting to write a test that ensures a function is called in one instance, not called in another. For example, installing a PSRepository only if it's necessary. While I have 1 test working, the other is not. According to the docs, `Should` supports `-Not` when using `-InvokeVerified`.

Is there a better way to approach this?

## Describe your environment
Using docker to execute test(s):

```
Pester version     : 5.0.4 C:\Users\ContainerAdministrator\Documents\WindowsPowerShell\Modules\Pester\5.0.4\Pester.psm1
PowerShell version : 5.1.17763.1490
OS version         : Microsoft Windows NT 10.0.17763.0
```

## Steps to reproduce

```powershell
$script:PSRepositoryName = "ExampleRepo"
$script:PSRepositoryLocation = "https://my.myget.org/f/my/api/v2"

Function Register-MyRepository {
  If ($null -eq (Get-PSRepository $script:PSRepositoryName -ErrorAction Ignore)) {
    Register-PSRepository $script:PSRepositoryName $script:PSRepositoryLocation -InstallationPolicy Trusted
  }
}

Describe "Register-MyRepository" {
  It "Should register if not exist" {
    Mock Get-PSRepository { } -ParameterFilter { $Name -eq $script:PSRepositoryName }
    Mock Register-PSRepository -Verifiable { } -ParameterFilter { $Name -eq $script:PSRepositoryName }

    Register-MyRepository | Should -InvokeVerifiable
  }
  It "Should not register if exist" {
    Mock Get-PSRepository {
      @{
        InstallationPolicy = "Trusted"
        Name = $script:PSRepositoryName
        PackageManagementProvider = "NuGet"
        ProviderOptions = @{}
        PublishLocation = "${script:PSRepositoryLocation}/package/"
        Registered = $True
        ScriptPublishLocation = "${script:PSRepositoryLocation}/package/"
        ScriptSourceLocation = ""
        SourceLocation = $script:PSRepositoryLocation
        Trusted = $True
      }
    } -ParameterFilter { $Name -eq $script:PSRepositoryName }
    Mock Register-PSRepository -Verifiable { } -ParameterFilter { $Name -eq $script:PSRepositoryName }

    Register-MyRepository | Should -Not -InvokeVerifiable
  }
}
```

## Expected Behavior
Both tests should pass (note `-Not -InvokeVerifiable` to ensure `Register-PSRepository` is _not_ called)

## Current Behavior

Second test fails:

```
Starting discovery in 1 files.
Discovery finished in 34ms.
[-] Register-MyRepository.Should not register if exist 49ms (47ms|2ms)
  Expected Register-PSRepository to be called with  $Name -eq $script:PSRepositoryName 
 at Register-MyRepository | Should -Not -InvokeVerifiable, C:\Users\brad.christie\OneDrive - Velir\Powershell\Pester-InvokeVerifiable.ps1:34
 at <ScriptBlock>, C:\Users\brad.christie\OneDrive - Velir\Powershell\Pester-InvokeVerifiable.ps1:34
Tests completed in 848ms
Tests Passed: 1, Failed: 1, Skipped: 0 NotRun: 0
```

**Comment by fflaten** [comment]
Thanks for the report!

Considering you only have a single verifiable mock in that test, then verifiable is kinda overkill. It's more for convenience to avoid many `Should -Invoke xyz` lines in a test. I'd personally use `Register-MyRepository | Should -Not -Invoke -CommandName Register-PSRepository` to be more explicit.

@nohwnd Any reason why InvokeVerifiable doesn't support negate? I'm guessing just an oversight? I wouldn't think this was commonly used, but I could see the logic of it being "all or nothing". `-Not` is a common should parameter, so it will show in the syntax either way.

**Comment by bchristie** [comment]
@fflaten thanks for the feedback, was going for the minimum viable example here. Still, I feel like -Not should be possible, otherwise it should be broken out via a new parameter set.

Just my $0.02.

**Comment by fflaten** [comment]
In my mind, a test with `Should -Not -InvokeVerifiable` would fail only when absolutely all verifiable mocks actually were called. Looking at the current implementation this might not be possible atm. due to how we track verifiable mocks. As soon as they are called, the bool-flag used to mark them are flipped and at that point there's no way to separate "all verifiable mocks were called" vs "no verifiable mocks where defined in the first place" AFAIK.

This would result in a poor error-message as we wouldn't be able to tell users which of the scenarios occurred. The latter scenario should warn the user that the call to `Should -Not -InvokeVerifiable` was completely unnecessary. If the logic around verifiable mocks is changed in the future, it might be possible (https://github.com/pester/Pester/issues/1814#issuecomment-854039887)

@nohwnd Any thoughts?
- Implement `-Not` without being able to tell users any details about why it failed (no verifiable mocks defined vs all verifiable mocks were called)?
- Simply skip registering `-Not` specifically for `InvokeVerifiable`.

While looking at it, we should throw error when `-ActualValue` is provided (as in `Should -Invoke`) since that also is a unused parameter, one that we can't hide just as easily.

**Comment by nohwnd** [comment]
Looks like what we use for the verifiable is a "hack", but has a simple fix. Add .Executed on the behavior and set it to $true when executed, and keep the Verifiable to the value that user specified, that is $true for a verfiable mock, or $false (the default) for nonverifiable.

https://github.com/pester/Pester/blob/40501acbc107daf31f07c803ec77bff9debe6f4c/src/functions/Mock.ps1#L974

Then in `Should-InvokeVerifiable` we just need to count verifiable mocks, when 0 we report there weren't any. 

Then count Executed, when any is false, we report that not all were executed. In the code below we only get verifiable behaviors, so we just count them. And the rest of the code changes to check Executed instead of Verifiable.

https://github.com/pester/Pester/blob/main/src/functions/Mock.ps1#L299

**Comment by fflaten** [comment]
That's true 👍 Your suggestion above was my initial thought to fix this specific issue, but I wanted to delay modifying the verifiable-logic until #1814 was discussed just in case it requires more drastic changes to the verifiable-logic.

If this is ready to go, I can submit a PR.

**Comment by nohwnd** [comment]
Yes please, I think this will clean up the semantics in the implementation.

**Comment by fflaten** [comment]
Follow-up.. The error-messages in this assertion is pretty basic, ex. it currently only complains about the first missing command and not all of the missing behaviors.  Played with some new error-messages. 

`Should -InvokeVerifiable` in Pester 5.2.0 (used the most complex mock to illustrate since it only shows one):
![image](https://user-images.githubusercontent.com/3436158/120824069-5e034a80-c558-11eb-8da6-7bfe4e35bad2.png)

`Should -InvokeVerifiable` after change:
![image](https://user-images.githubusercontent.com/3436158/120824126-6b203980-c558-11eb-935e-18cf2e45c7f5.png)

`Should -Not -InvokeVerifiable` after change:
![image](https://user-images.githubusercontent.com/3436158/120824152-71aeb100-c558-11eb-9ded-ec0a9b1f94cf.png)

Thoughts?

**Comment by nohwnd** [comment]
I think Should has the ability to report multiple errors, or maybe this is only used for the collect-all-should-errors and happens on the end of It, but might be reused.Anyways let’s just fix the -Not, and delay further improvements to later. I think it would be way more valuable to invest into Should -Invoke to list all the invocations when not passing, as requested somewhere else.

**Comment by fflaten** [comment]
> Anyways let’s just fix the -Not, and delay further improvements to later.

Does that include error listing all invoked commands in -Not or just one random command like the positive assertion has atm to have them consistent?

**Comment by nohwnd** [comment]
Up to you, whichever is simpler. Or if you want to invest your time into fixing this properly go for it, I am not your boss and we are not on a time schedule 🙂🙂🙂

I was thinking that maybe we could internally collect all the problems, generate multiple errors and then just reuse the write-multiple errors logic. But I have very vague idea how -InvokeVerifiable works now, I remember I just coded it to pass tests, but was not looking too deep into it when working on v5.

I would just fix this with the same behavior the positive case has.
