### ISSUE TITLE
How does pester test programs with interaction(User input required)?

### ISSUE THREAD

**Issue by Andy-AO** [pester/Pester#1826]
How does pester test programs with interaction(User input required)?

If the code contains `read-host`, it can be tested by Mock.

But sometimes being mocked obviously doesn't work. 

For example, I want to test what happens when the Mandatory parameter of the command doesn't exist, or test `out-host -Paging`. 

How to test in this case? 

If there is a way to pass in user input, it can solve this problem.

Of course, this is not limited to pester, it can also be used `PowerShell.exe` Or `[PowerShell]`, But I haven't found a specific way.

If this is difficult to implement at present, I propose to add this Feature to pester.

thanks!

**Comment by fflaten** [comment]
Not sure what you'd like to test with `Out-Host` - isn't that Microsoft's job? 🙂
Like `Write-Host`, `Read-Host`, `Format-*` etc., `Out-Host` is for interactive use and only shows information you already have as objects - which are far easier to test. Personally I'd keep blocking cmdlets like `Out-Host -Paging` away from my scripts and let the user add it during invocation if desired (maybe add as tip in the help)

We usually try to keep UI/presentation away from the business logic by storing them as their own scripts/functions with parameters and validation so you can focus on unit-testing the logic.  If you'd then like to include a user-friendly controller-script to run x functions, then `Read-Host` etc. don't really need to be tested as thoroughly because you know the functions (business logic) that will depend on the user input won't accept invalid parameter-values anyways.

If a parameter is marked as mandatory then PowerShell won't run the function unless it's specified. You can also add parameter-validation to avoid it accepting empty or invalid values. What more would you like to test? Ex.
```
[CmdletBinding()]
param (
    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [string]
    $Param1
)
```

`*-Host` cmdlets aren't meant for automation, so automated testing is somewhat limited and hard to implement (AutoHotKey next?). You can however use mocks to test different `Read-Host` input and to verify `Out-Host -Paging` was called at all. By specifying a parameterfilter you can create different automated user inputs for different prompts. Ex.

scriptTest.ps1
```
[CmdletBinding()]
param (
    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [string]
    $Param1
)

$greeting = Read-Host "Enter a greeting"
$name = Read-Host "Enter a name"

"$greeting $name !"
1..30 | Out-Host -Paging
```
scriptTest.Tests.ps1

```
Describe "Script Test" {
    BeforeAll {
        # Can also be placed in It-block if specific values are needed per test
        Mock -CommandName Read-Host -ParameterFilter { $Prompt -match 'greeting' } { "Hello" }
        Mock -CommandName Read-Host -ParameterFilter { $Prompt -match 'name' } { "Andy" }
    }
    It "Test Out-Host -Paging" {
        Mock -CommandName Out-Host -ParameterFilter { $Paging -eq $true }

        & "$PSScriptRoot/scriptTest.ps1" -Param1 Test | Should -Be "Hello Andy !"
        
        #Verify Out-Host was called using -Paging
        #Btw. you'd need to add paramterfilter to Should if there were multiple Out-Host mocks
        Should -Invoke -CommandName Out-Host
    }
}

```

**Comment by Andy-AO** [comment]
> Not sure what you'd like to test with `Out-Host` - isn't that Microsoft's job? 🙂
> Like `Write-Host`, `Format-*` etc., `Out-Host` is for interactive use and only shows information you already have as objects - which are far easier to test. Personally I'd keep those and especially blocking cmdlets like `Out-Host -Paging` away from my scripts and let the user add it during invocation if desired (maybe add as tip in the help)
> 
> We usually try to keep UI/presentation away from the business logic by storing them as their own scripts/functions with parameters and validation so you can focus on unit-testing the logic. If you'd then like to include a user-friendly controller-script to run x functions, then `Read-Host` etc. don't really need to be tested as thoroughly because you know the functions (business logic) that will depend on the user input won't accept invalid parameter-values anyways.
> 
> If a parameter is marked as mandatory then PowerShell won't run the function unless it's specified. You can also add parameter-validation to avoid it accepting empty or invalid values. What more would you like to test? Ex.
> 
> ```
> [CmdletBinding()]
> param (
>     [Parameter(Mandatory)]
>     [ValidateNotNullOrEmpty()]
>     [string]
>     $Param1
> )
> ```
> 
> `*-Host` cmdlets aren't meant for automation, so automated testing is somewhat limited and hard to implement (AutoHotKey next?). You can however use mocks to test different `Read-Host` input and to verify `Out-Host -Paging` was called at all. By specifying a parameterfilter you can create different automated user inputs for different prompts. Ex.
> 
> scriptTest.ps1
> 
> ```
> [CmdletBinding()]
> param (
>     [Parameter(Mandatory)]
>     [ValidateNotNullOrEmpty()]
>     [string]
>     $Param1
> )
> 
> $greeting = Read-Host "Enter a greeting"
> $name = Read-Host "Enter a name"
> 
> "$greeting $name !"
> 1..30 | Out-Host -Paging
> ```
> 
> scriptTest.Tests.ps1
> 
> ```
> Describe "Script Test" {
>     BeforeAll {
>         # Can also be placed in It-block if specific values are needed per test
>         Mock -CommandName Read-Host -ParameterFilter { $Prompt -match 'greeting' } { "Hello" }
>         Mock -CommandName Read-Host -ParameterFilter { $Prompt -match 'name' } { "Andy" }
>     }
>     It "Test Out-Host -Paging" {
>         Mock -CommandName Out-Host -ParameterFilter { $Paging -eq $true }
> 
>         & "$PSScriptRoot/scriptTest.ps1" -Param1 Test | Should -Be "Hello Andy !"
>         
>         #Verify Out-Host was called using -Paging
>         #Btw. you'd need to add paramterfilter to Should if there were multiple Out-Host mocks
>         Should -Invoke -CommandName Out-Host
>     }
> }
> ```

 I want to use the test method to describe this feature, just like taking notes in a notebook. I just use the test method, which is more accurate.

Now it seems that PowerShell has not been able to be flexible to such a degree. If want to describe it well, have to test PowerShell itself. Fortunately, it is open source .

**Comment by nohwnd** [comment]
You would have to write your own powershell host for that I am afraid, or replace the current host during runtime via reflection. Then you would be able to handle your prompts in any way you like.

**Comment by nohwnd** [comment]
It is not a difficult task though, because you can delegate all the unmocked functions to the real host, to avoid re-implementing them. I experimented with it in the past, it was just too complex to ensure it works across all powershell versions, platforms, and hosts.
