### ISSUE TITLE
Invoke-Pester with -Tag output is incorrect with multiple Describe or Context blocks with different tags

### ISSUE THREAD

**Issue by toddbrownmcis** [pester/Pester#1848]
## General summary of the issue
When using **-Tag** parameter with **Invoke-Pester** on a tests file with multiple **Describe** or **Context** blocks with different tag values, the **Normal** **Verbosity** output is incorrect.

## Describe your environment

Pester version     : 5.1.1 C:\Program Files\WindowsPowerShell\Modules\Pester\5.1.1\Pester.psm1
PowerShell version : 5.1.14409.1018
OS version         : Microsoft Windows NT 6.1.7601 Service Pack 1

## Steps to reproduce

1. Create file.tests.ps1 as **one** of the following:
 ```powershell
Describe "Describe1" -Tag "Tag1" {
    It "It1" { $true | Should -Be $true }
}

Describe "Describe2" -Tag "Tag2" {
    It "It2" { $true | Should -Be $true }
}
```
**OR**
```powershell
Describe "Describe1" {
    Context "Context1" -Tag "Tag1" {
        It "It1" { $true | Should -Be $true }
    }
    Context "Context2" -Tag "Tag2" {
        It "It2" { $true | Should -Be $true }
    }
}
```
2.  Invoke-Pester -Path .\file.tests.ps1 -Tag Tag1

## Expected Behavior

Should output the following:
```
Starting discovery in 1 files.
Discovery finished in 120ms.
[+] C:\Temp\file.tests.ps1 635ms (12ms|583ms)
Tests completed in 647ms
Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 1
```

## Current Behavior

Current **Normal** **Verbosity** output is missing the test file line:
```
Starting discovery in 1 files.
Discovery finished in 120ms.
Tests completed in 647ms
Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 1
```

**Comment by nohwnd** [comment]
Thanks this was actually a problem with marking the parent block as not passed when there are some blocks that did not run. This was not caught in tests because there is inconsistency in the code that checks results, where it uses `if ($Context.Result.Passed) {` to check if the block passed, but for failed it uses `if ($Context.Result.ErrorRecord.Count -gt 0) {`, And neither of those conditions were true, so we did not get extra output on the screen notifying us of this mistake. 

Unifying the code to use the `$Context.Result.Result` would have reported the block as not run, which also would not help, because we don't print such blocks.
