### ISSUE TITLE
Invoke-Pester should handle failures without presenting stack traces

### ISSUE THREAD

**Issue by asears** [pester/Pester#1875]
## Summary of the feature request

Stack traces are useful for Pester devs, however it may be just noise in the build for others, at least with some errors.  

## How should it work? (optional)

A few examples

1. Having no tests in a folder passed to pester throws System.Management.Automation.RuntimeException which could be handled by the script and present the user with a friendlier error or optionally just warn or info on this.  Pester configuration settings could enable this change to display friendlier errors, or set levels of errors vs. warnings vs. info messages during test discovery.

"No test files were found and no scriptblocks were provided."

I don't think Pester should care enough to throw an error if the user did not have tests in a folder passed. This would be similar to pytest functionality which will complain if tests folder missing, otherwise just says 0 tests run.  

2. Having no folder to save the code coverage output presents System.IO.DirectoryNotFoundException: Could not find a part of the path which could be caught and perhaps create the folder?

3. Having no folder to save the test results output presents Resolve-Path, System.Management.Automation.ParameterBindingValidationException.

**Comment by nohwnd** [comment]
I agree overall, and agree fully with 2 and 3. But in I think that 1 should report an error by default and only allow reporting empty run without error when user opts into that via configuration. Otherwise providing non existing path will report test run success, which in MSTest we see mentioned often as source of problems.

**Comment by nohwnd** [comment]
The issue 1. also happens when you filter out all tests, which can happen by accident. I would like this to work nicer, to have consistent experience with ThrowOnFailedRun (or how that option is called) when we throw when some test failed at the end after printing the report and other stuff. 

Bu implementing this means more changes. For example when CC is enabled, then running no tests should report all code as uncovered. This would complicate how we setup CC, as we would have to figure it out before discovery (before filter), and then actually set it up before run. Not hugely complicated, but more complicated than just throwing. We should also return empty test result. 


So I guess I could implement 2. and 3. as those are easy fixes, and add the note that you might have filtered all tests out to the error in 1. But refactoring this to work better, and possibly adding -Strict mode back in would have to wait.
