### ISSUE TITLE
Export to Allure format

### ISSUE THREAD

**Issue by rismoney** [pester/Pester#1960]
This is a pretty awesome test reporting tool upon reading the docs and reviewing their code and has a ton of supported formats.  I know that pester can export to nunit/xml formats.  However the tool leverages a plugin system to convert these standard outputs into a format consumable by allure.

I think enabling output to this format would be awesome!  Allure seems to have a pretty vibrant community.

https://github.com/allure-framework/allure2

Doable?

**Comment by rismoney** [comment]
So it looks like I can get some basic functionality, out of exporting to junit xml

So it looks like testsuite name is derived from the path.  I know the root testsuite name is configurable, but I would like to override the testsuite names from the file paths.

Is there a way in the tests to perhaps set an alternate naming value that is more meaningful than /path/to/file.

**Comment by nohwnd** [comment]
You can use -PassThru to get the result object and make the report in any format you want. Take the Export-NUnitXml as areference, it uses the same object to get the NUnit report. You are not limited to the current supported formats.

It is unlikely to add another format directly to Pester, because that means that I have to support it forever. But I am open to adopting it to the Pester org as a separate repo if you are willing to become a maintainer of that. You can then choose to support only some version of Pester / Allure, or all.

**Comment by rismoney** [comment]
This will work.  Passthru is a viable option.  At this time I have to run a "publish to allure" script anyway so it's not a huge deal to do some object manipulation.

I think the format for junit works out of the box now.  I didn't want to add additional logic to the output formats.  I don't believe the full $path is the right value to be used but fail to see a better option.  Since my use case is infrastructure testing atm, I am replacing the path with hostname/testname.
