### ISSUE TITLE
Discovery and setup of mocks from sut scripts

### ISSUE THREAD

**Issue by asears** [pester/Pester#1970]
## Summary of the feature request

With Azure Powershell and in general during testing, I find mocking super helpful.  Is there a method to detect what 'should' be mocked in a subject under test script, and how many times it should be -Times -Exactly called?  Having many external calls it's tedious to mock them all manually.

I'm looking for a BeforeAll mock generator to help discover calls which are not currently mocked in the test script, which should be mocked prior to running the test.  

## How should it work?

As part of test script development workflow, run a Pester command to discover external commands and calls.  Generate stubs of mocks for the calls as output.  These stubs can be implemented in a Pester test script.

A Pester command - Discover-Mocks? - could discover a folder's Powershell scripts, and return a list of external function calls or command dependencies, including Powershell's built-in calls, external module calls, command-line executables and script calls.

If a script looks like this:

ScriptName.ps1

```powershell
Write-Host "this is a script. I don't want write-host in my test results but I will use ParameterFilter to check what's going on"
Connect-PowerBIServiceAccount | Out-Null # This might return something in my mock.  It would be nice to discover outputs of this function and generate a stub.
Start-Sleep 1 # because I don't want my test to get stuck I'll mock this
New-PowerBIGroup -Name test
```

The output could look something like this or perhaps as a fully stubbed out Describe/BeforeAll/Context/It snippet:

```powershell
$ Discover-Mocks -Path .\ScriptName.ps1

ScriptName.ps1
        Mock 'Write-Host' -MockWith {}
        Mock 'Connect-PowerBIServiceAccount' -MockWith {}
        Mock 'New-PowerBIGroup' -MockWith {}
        Mock 'Out-Null' -MockWith {}
        Mock 'Start-Sleep' -MockWith {}

       Should -Invoke -CommandName Start-Sleep -Exactly -Times 1
       ...
```

This should be doable with some of the functionality of the Powershell AST?

Eventually this could just generate the Pester tests and mocks with some NLP and GPT-3 but I'd be happy with just getting list of mocks required to implement for now...

**Comment by fflaten** [comment]
I like the idea, but my immediate thought would be that this belongs in it's own module and not directly in the engine.

What exactly should be mocked is a subjective considering Pester can be used for both integration and unit testing.

**Comment by asears** [comment]
Yes, this does seem more like scaffolding of test functionality and generation of tests rather than direct engine/invoke-pester functionality.  This is probably a helper module, function or script.  Would be nice if it was a plugin.  Pester knows what a Pester mock is so I think it should live next and extend this functionality.

Much of the functionality to discover what is a valid Pester mock and what is available from the real command is in Create-MockHook I think?  Verify what can and can't be mocked, generate context, discover other metadata.  The missing piece is the discovery of all valid CommandName's in a file, rather than a specifically-called CommandName.  

https://github.com/pester/Pester/blob/40501acbc107daf31f07c803ec77bff9debe6f4c/src/functions/Mock.ps1

I was wondering if Discovery or Mock Phase may be able to be extended / reused to do this functionality via some output messages?  Perhaps suggesting some mocks but not running the tests just yet?

**Comment by fflaten** [comment]
IIRC Pester doesn't care much about built-in/external commands except. We only process them when `Mock` is called to define the mock or when calling an existing mock because you're actually calling a Pester-generated alias to invoke the hook (MITM-style), so I don't think there's much existing processing to be reused. Maybe except for the helper-functions to resolve commands and validate if it's a supported module-type.

The syntax for defining Mock is pretty static, so keeping the helper-moduled updated should be fine. Scaffolding will probably only get you so far either way due to `-ParameterFilter` and `-ModuleName` which can get complex. You can use AST to find `CommandAst` to get command name + syntax, then resolve and filter them based on loaded modules just to ignore non-supported module types and return a basic mock (not guaranteed to be working) or list to the user.

A limitation with AST alone is knowing which module state it was called from and as a result which module the CommandName belongs to since it can be reused in multiple modules. You also wouldn't know what type of output to expect, something that might be cool. Not sure if it's possible at all to get the returned data, but you'd probably have to hook into the debugger to access it.

**Comment by nohwnd** [comment]
Yeah, what @fflaten said above. Depending on your needs AST might get you pretty far. If you only want to look at code contained in files that are in specific folder you might be pretty successful with it, maybe 90% there. If you want to be able to get stuff from imported modules, dot-sourced files, and other stuff that happens on runtime, you would have to write some pretty intelligent resolver that would do those things. This is also a reason why I avoided using AST for Pester discovery, it is static analysis so you can't really know things that happen on runtime. In many cases you can guess it, but you can't know for sure, so it's not very well suited for framework that needs to work for everyone.

**Comment by fflaten** [comment]
Closing as won't fix as this should be an external module/script if created. 

Let us know (in discussions maybe?) if this becomes real so we can maybe link to it on the website, or if you need some input while developing. 🙂
