### ISSUE TITLE
Mock module exported functions

### ISSUE THREAD

**Issue by nathandhami** [pester/Pester#1985]
## General summary of the issue
Cannot mock an exported module function. According to the documentation, it should be able to mock public functions.

## Describe your environment

Pester version     : 5.2.2 C:\Program Files\WindowsPowerShell\Modules\Pester\5.2.2\Pester.psm1
PowerShell version : 5.1.19041.906
OS version         : Microsoft Windows NT 10.0.19041.0

## Steps to reproduce

1. module Peace.psm1

```powershell
function Get-Result {
    "YEA"
}

Export-ModuleMember -Function Get-Result
```

2. Run test script
```powershell
BeforeAll {
    Import-Module Peace -Force
    function Invoke-Result {
        Get-Result
    }
}

Describe 'A' {
    BeforeAll {
        Mock -ModuleName Peace -CommandName Get-Result { Write-Output "HELLO" }
    }

    It "mock get result" {
        Invoke-Result
        Assert-MockCalled -ModuleName Peace Get-Result -Times 1
    }
}
```

## Expected Behavior

Assert-MockCalled passes

## Current Behavior

Mocked function never gets executed
[-] A.mock  getresult 16ms (14ms|1ms)
 Expected Get-Result in module Peace to be called at least 1 times but was called 0 times
 at Should -Invoke @__params__p, C:\Program Files\WindowsPowerShell\Modules\Pester\5.2.2\Pester.psm1:13460

**Comment by nohwnd** [comment]
`-ModuleName` parameter means from which module you will be calling the mocked function (or in other words: inside of which module you want this mock to be active.) It does not mean the name of the module in which the function is defined. 

And similarly for the Assert-MockCalled. It means to filter the calls only to those that used the mock that was active in that module. 

Your code is calling the mock from the script scope because the function is public. You should remove `-ModuleName` from both calls and it will work.

**Comment by nathandhami** [comment]
I thought I had tried that. Thanks for the clear explanation! Its working.
