### ISSUE TITLE
Data Driven test using -ForEach with array ignores It test

### ISSUE THREAD

**Issue by aawhistle** [pester/Pester#2072]
## General summary of the issue
It seems that Pester v5.3.0 does not discover data driven tests using the -ForEach Array

## Describe your environment

Pester version     : 5.3.0 C:\Program Files\WindowsPowerShell\Modules\Pester\5.3.0\Pester.psm1
PowerShell version : 5.1.17763.592
OS version         : Microsoft Windows NT 10.0.17763.0

## Steps to reproduce

```powershell
Describe 'Data Driven Bug Test' {
    BeforeAll{
        $TestArray = @(0,1,2,3)
    }
    Context 'Undiscovered Context' {
        It 'TestArray[<_>] value should be <_>' -ForEach $TestArray {
            $TestArray[$_] | Should -Be $_
        }
    }
    Context 'Discovered Context' {
        It 'TestArray values should match its index' {
            foreach ($Index in $TestArray)
            {
                $TestArray[$Index] | Should -Be $Index
            }
        }
    }
}
```

## Expected Behavior

Both contexts are discovered. Context 1 produces 4 tests (one for each in array) and they all pass. Context 2 produces 1 test and passes.

## Current Behavior

Context 1 is ignored. Context 2 produces 1 test and passes.

## Possible Solution? (optional)

Something changed between Pester v5.2.2 and v5.3.0. A similar test functioned on v5.2.2, but on update to v5.3.0 the test became undiscovered.

**Comment by fflaten** [comment]
There shouldn't be any change here in tte latest version. `-Foreach` is processed during the Discovery-phase, while `BeforeAll` where you define the variable is processed later during the Run-phase, so that array isn't created in time for `-Foreach.

This is how Pester v5 works. You need to switch the `BeforeAll` with [`BeforeDiscovery`](https://pester.dev/docs/usage/data-driven-tests#beforediscovery).

**Comment by fflaten** [comment]
@aawhistle Closing this as I believe it's solved. Correct me if I'm wrong 🙂
