### ISSUE TITLE
Can't set CoveragePercentTarget in New-PesterConfiguration

### ISSUE THREAD

**Issue by Jaykul** [pester/Pester#2108]
## Can't set CoveragePercentTarget in New-PesterConfiguration

```PowerShell
$Config = New-PesterConfiguration @{ CodeCoverage = @{ CoveragePercentTarget = 90 }}
$Config.Codecoverage.CoveragePercentTarget
```
```Text
Default Description                                                            Value
------- -----------                                                            -----
     75 Target percent of code coverage that you want to achieve, default 75%.    75
```

I'm **really unhappy** with this command, if I'm honest. How is it possible that this doesn't produce an error:

```PowerShell
$Config = New-PesterConfiguration @{ Nonsense = @{ NobobyCares = 90 }}
```

I can't figure out any way to make this command actually set the coverage target. I had to manually set the `.Value` on the output object.

**Comment by nohwnd** [comment]
Something is wired incorrectly in there, this also does not work `$c = [PesterConfiguration] @{ CodeCoverage = @{ CoveragePercentTarget = 90 }}`, but `$c.CodeCoverage.CoveragePercentTarget = 90` works.

**Comment by fflaten** [comment]
It's caused by CoveragePercentTarget being a `DecimalOption` and `configuration.GetValueOrNull<decimal>("CoveragePercentTarget")` used in config merging being strict on the type validation without any double/decimal/int conversion. So it will always return null (-> default value) unless you explicitly provide a decimal, ex.

```powershell
$Config = New-PesterConfiguration @{ CodeCoverage = @{ CoveragePercentTarget = [decimal]91 }}
$Config.Codecoverage.CoveragePercentTarget                                                   

Default Description                                                            Value
------- -----------                                                            -----
     75 Target percent of code coverage that you want to achieve, default 75%.    91
```

`$c.CodeCoverage.CoveragePercentTarget = 90` is solved by implicit cast for int defined in `DecimalOption`.

Quick fix: Change to `IntOption` which should suffice 99% of time.
Bonus: Support some conversions GetValueOrNull<T> in case people provide double when T is int etc. ?
