### ISSUE TITLE
Support Cobertura as Code Coverage Report Format

### ISSUE THREAD

**Issue by eizedev** [pester/Pester#2203]
### Checklist

- [X] Feature request has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### Summary of the feature request

Hi,

we are internally using Gitlab CI for all our powershell stuff. Gitlab only supports [Cobertura](https://cobertura.github.io/cobertura/) as code coverage report format (See [Gitlab Test Coverage](https://docs.gitlab.com/ee/ci/testing/test_coverage_visualization.html#how-test-coverage-visualization-works)). Pester internally only supports 'JaCoCo' or 'CoverageGutters'. I have read a few other issues like this https://github.com/pester/Pester/issues/212#issuecomment-338228471 about the implementation of cobertura and other formats.

Could you please add a cobertura compatible Code Coverage Report format like JaCoCo in Pester?

(The TestResult Format `JUnitXml` is already supported in gitlab.)

Thanks,
René

**Comment by nohwnd** [comment]
I don't have a capacity to implement this myself right now. Putting for adoption from community.

I think this a good first issue to solve even though the scope is a bit big if this is your first PR ever. There is already code that creates jacoco format and cobertura would be similar hopefully.

**Comment by joeskeen** [comment]
I found where the JaCoCo generation code is. 

https://github.com/pester/Pester/blob/6e8eb89da86fcd7298047cda385f3c4b67ef311f/src/functions/Coverage.ps1#L805

As Cobertura is another XML-based coverage format, I'm hoping it wouldn't be too hard to implement. I did find the Cobertura DTD files which describe the format: <https://github.com/cobertura/cobertura/tree/master/cobertura/src/site/htdocs/xml>

That being said, I'm not sure which version of Cobertura we would want to support. The Cobertura output I get from Jest JavaScript unit tests (via jest-junit) shows as coverage-04.dtd, so perhaps that would be a good place to start as I already know that it is supported by tools like ReportGenerator and Azure Pipelines. Thoughts? If I get a chance I may take a crack at it since I could really use this functionality.

**Comment by fflaten** [comment]
> That being said, I'm not sure which version of Cobertura we would want to support. The Cobertura output I get from Jest JavaScript unit tests (via jest-junit) shows as coverage-04.dtd, so perhaps that would be a good place to start as I already know that it is supported by tools like ReportGenerator and Azure Pipelines. Thoughts? If I get a chance I may take a crack at it since I could really use this functionality.

Searching around the web it seems `coverage-04.dtd` is mostly the one referenced. Didn't look at what the differences would be. Looks like Cobertura isn't really maintained much lately, but I guess that means the DTD is kinda stable.

JaCoCo seems to be generally widely supported and preferred, so as long as the version is compliant with Gitlab which requires conversion now, then it should be fine I guess. 🙂  Really weird how to keep delaying the JaCoCo-support (ETA Q2'24 it seems).

**Comment by joeskeen** [comment]
Yeah, seems like Cobertura is still a preferred format in the JS world, as that's one of the most commonly referenced output formats when I'm looking into Jest code coverage. Unfortunately I haven't found any JaCoCo format plugin for Jest... It would be nice if all the code ecosystems could agree on some kind of uniform standard LOL!
