### ISSUE TITLE
Detailed Output vs Test Report - Skipped

### ISSUE THREAD

**Issue by Splaxi** [pester/Pester#2220]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

It seems that the logic with expanding the path of a given test, is being handled differently when we are talking about the detailed output and the output object.

```powershell
BeforeDiscovery {
    $colLogicApps = @(
        @{ Name = "1" }
        @{ Name = "2" }
        @{ Name = "3" }
        @{ Name = "4" }
    )
}

Describe "Execute <name>" -ForEach $colLogicApps {
    BeforeEach {
        if ($Name -eq "3") {
            Set-ItResult -Skipped -Because "Just because"
        }
    }

    It " Skip when 2" {
        if ($Name -eq "2") {
            Set-ItResult -Skipped -Because "Just because"
        }

        1 + 1 | Should -be 2
    }
}
```

The detailed output expands the path of each test / describe:

<img width="684" alt="image" src="https://user-images.githubusercontent.com/8750181/180150712-e06e370b-37e7-423d-8e7c-c3568d627444.png">

But the output object looks like this:

```powershell
$temp = Invoke-Pester -Path "..." -Output Detailed -PassThru
$temp.tests | ft Name, Path, ExpandedPath
```

<img width="731" alt="image" src="https://user-images.githubusercontent.com/8750181/180151142-bcf7bc04-7ca8-4e07-9b24-6f075fa40f97.png">

### Expected Behavior

I would expect the expanded path to work the same way as the detailed output, so when you are generating NUnit/JUnit files, the would reflect the same values.

**Comment by fflaten** [comment]
Thanks for the report. `ExpandedName` and `ExpandedPath` are evaluated after the setups because they could create variables used in the name iirc. So skipping inside `BeforeEach` vs `It` will be different since the latter will already be finished with setups -> name is expanded.

We could however update the placeholder-value for `ExpandedPath` that you see now to be expanded as far as we reached before skip/failure. That would solve this issue where only the block has a variable + make it easier to identify the correct block in general. 👍

**Comment by Splaxi** [comment]
Thanks for the feedback.

Is there any way I can assist with this, so we can have the change to be part of the next release? I'm new to the code base of pester, but I'm up for the challenge to see if I can fix it and do the PR.

Just need some pointers, then I can test local and see if my scenario can be handled or not.

**Comment by fflaten** [comment]
Absolutely, contributions are always welcome 😃
You can see how to build and test in [CONTRIBUTING.md](https://github.com/pester/Pester/blob/main/CONTRIBUTING.md). I personally use the devcontainer in the repo so I don't need .NET locally.

As for the code:
- **Test (It)**
You can see how `ExpandedPath` is set [here](https://github.com/pester/Pester/blob/dd7d09eb730c8d9fc7ac746aeecf750bf98b9d00/src/Pester.Runtime.ps1#L653). I'm thinking we could set it once more earlier in `Invoke-TestItem` before the skip-check and/or framework-setup. `$Test` should be the same as `CurrentTest` at that point.

- **Block (Describe/Context)**
Current logic is [here](https://github.com/pester/Pester/blob/dd7d09eb730c8d9fc7ac746aeecf750bf98b9d00/src/Pester.Runtime.ps1#L392-L398). `ExpandedPath` could be set the same way probably around L321.

- We should also add a test or two [similar to this](https://github.com/pester/Pester/blob/dd7d09eb730c8d9fc7ac746aeecf750bf98b9d00/tst/Pester.RSpec.ts.ps1#L1756-L1770) to verify that it works when a) a block fails due to `BeforeAll`, b) a test fails in a `BeforeEach` (or `Set-ItResult` which is a special exception -> fail).

Maybe in a new block (`b` function)? These are P-test which are used to test behavior of Pester-engine itself from the outside. `b` is like  `describe/context`, `i` is like `It` and we can only use the `Verify-*` assertions found in the `tst\axiom`-folder.

**Comment by fflaten** [comment]
Still interested in submitting a PR @Splaxi? 🙂

**Comment by Splaxi** [comment]
Yeah - but when I tried the last time, I could find a way to solve the issue.

So I feel that I'm smart enough to tackle the challenge, regardless of me having the issue 🤦‍♂️

**Comment by fflaten** [comment]
Looking back at it months later it wasn't my best explanation neither 😄
I think I've covered it in the related PR.
