### ISSUE TITLE
A variable with name 'TestDrive' already exists

### ISSUE THREAD

**Issue by vors** [pester/Pester#250]
I don't have a good repro, I just encountered this problem once.
I'm pretty sure that I didn't declare `$TestDrive` myself.

```
New-Variable : A variable with name 'TestDrive' already exists.
At C:\Users\localadmin\Documents\WindowsPowerShell\Modules\Pester\Functions\TestDrive.ps1:20 char:9
+         New-Variable -Name $DriveName -Scope Global -Value $Path
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (TestDrive:String) [New-Variable], SessionStateException
    + FullyQualifiedErrorId : VariableAlreadyExists,Microsoft.PowerShell.Commands.NewVariableCommand
```

**Comment by dlwyatt** [comment]
That happens to me all the time when I am debugging tests and I hit control-c, rather than letting Pester finish running.  (I wind up aborting the whole test run before Pester gets around to removing the test drive.)

Not a huge deal, though we might be able to fix it by using a try/finally block somewhere.
