### ISSUE TITLE
Mock/Assert-MockCalled scoping issue

### ISSUE THREAD

**Issue by iainbrighton** [pester/Pester#268]
I don't know whether this is a known issue or is "by design". However, I would expect the following two tests to pass:
```
function MyFunction { throw }

Describe "Mocks called" {
    It "is called once." {
        Mock MyFunction { }
        MyFunction;
        Assert-MockCalled -CommandName MyFunction -Exactly 1;
    }
    It "shouldn't be called." {
        Mock MyFunction { }
        Assert-MockCalled -CommandName MyFunction -Exactly 0;
    }
}
```
This fails with the following error:
```
Executing all tests in 'C:\Users\Iain\Desktop\AssertFailure.Tests.ps1'
Describing Mocks called
 [+] is called once. 118ms
 [-] shouldn't be called. 21ms
   Expected MyFunction to be called 0 times exactly but was called 1 times
   at line: 516 in C:\Users\Iain\OneDrive\PowerShell\Modules\Pester\Functions\Mock.ps1
Tests completed in 139ms
Passed: 1 Failed: 1 Skipped: 0 Pending: 0
```
If you swap the two "It" blocks around it works fine! Therefore, it looks like something isn't being torn down or cleaned up correctly after each "It" script block? This is based on the latest build downloaded today (24 Jan 2015).

Thanks, Iain

**Comment by dlwyatt** [comment]
That's sort of by design, though the design was driven mainly by a desire to avoid breaking changes between Pester v2 and v3, and might be a little bit confusing.  Couple of things:

- Mocks are never scoped to an It block.  If you happen to put the Mock command inside the It block, that mock will still be live for the duration of whatever the It block's container is (could be Context or Describe).
- Assert-MockCalled, by default, looks for all calls to a mock inside the parent of the It block (Context or Describe).  You can override this behavior with the -Scope parameter on Assert-MockCalled; in this case if you add `-Scope It` to each of the calls to Assert-MockCalled, the tests will work fine in any order.

**Comment by iainbrighton** [comment]
Ah OK - my bad. If it's by design then so be it, now I know, I'll add the -Scope It parameter where necessary in future! Thank, Iain
