### ISSUE TITLE
Describing Create file with passthru and Create directory with passthru fail new install

### ISSUE THREAD

**Issue by elliottn** [pester/Pester#273]
Just started getting involved with pester.  Following some intro to pester guides haven't been able to help me get past a couple failures that appear.  Installation issue?

```
Describing Create file with passthru
 [-] returns the file from the temp location 61ms
   Expected: {True}
   But was:  {False}
   at line: 75 in C:\Users\Nick Elliott\Documents\WindowsPowerShell\Modules\Pester\Functions\TestDrive.Tests.ps1
   75:         $thefile.FullName -like "${env:TEMP}*" | Should Be $true
Describing Create directory with passthru
 [-] returns the directory from the temp location 67ms
   Expected: {True}
   But was:  {False}
   at line: 84 in C:\Users\Nick Elliott\Documents\WindowsPowerShell\Modules\Pester\Functions\TestDrive.Tests.ps1
   84:         $thedir.FullName -like "${env:TEMP}*" | Should Be $true
```

**Comment by dlwyatt** [comment]
Wouldn't worry about it.  I've run into that a couple of times, and it's always been because my $env:temp variable contained an 8.3 file name in the path for some reason, which screws with the string comparison.  We could account for that in the tests, I suppose, but it's a minor annoyance that doesn't happen on our build server.

**Comment by dlwyatt** [comment]
Ah, what the heck, I'll just fix it.  It's like 3 lines of code.  :)

**Comment by elliottn** [comment]
Test fix commit works like a champ on my machine.  Thanks!
