### ISSUE TITLE
Allow accumulation of test result objects

### ISSUE THREAD

**Issue by vors** [pester/Pester#283]
Scenario: I have a script `RunAll.ps1`, which calls different pester test suites [in parallel] with different inputs (see #271 for more context). So I roughly has something like:

``` powershell
$testResults = @{...} | % { Invoke-Pester -Path $_.Path -PassThru -Parametes $_.Parameters }
```

I want to be able to get a single object from `$testResults` that represents aggregated test results.

**Proposing new cmdlet**

``` powershell
SYNTAX:
Merge-PesterTestResults -TestResults object[]

Usage:
Merge-PesterTestResults $testResults
```

Does it make sense to include such cmdlet in pester?

**Comment by nohwnd** [comment]
@vors Definitely makes sense to me. Although I am not sure how the resulting object should look like. Currently the PesterResult is "flat", just collection of test results and some summary of it. The upside of this representation is that you can easily query failed or passed tests by simply using Where-Object. The downside is that it does not correctly represent that there were multiple test suites running and their hierarchy as the nUnit does.

So if simply adding the lists of the tests together is good enough, then implementing it should be a piece of cake, just add the collections together and re-calculate the summary properties. (it used to be automatic but Dave removed it for performance reasons)

I'd also suggest using **Join-PesterResult** instead of Merge.


---


In future versions, when multiple levels of "describe" are implemented we'll probably have to make the object more hierarchical and provide View-* cmdlets to flatten the hierarchy as needed (similar to clicking group by test suite, group by test result in some test result viewer GUI).

**Comment by nohwnd** [comment]
In v5 the result is hierarchical, and one result object is produced per file. The functions that process the results to xml / codecoverage / on-screen output will be published from the module so then adding multiple runs together is as simple as adding arrays toghether. v5 will also have built in -Parallel mode so this is done automatically for the basic cases. 

Closing this because it is now part of the design.

**Comment by vors** [comment]
Nice!
