### ISSUE TITLE
Restore original function on Exit-MockScope

### ISSUE THREAD

**Issue by MatthieuMEZIL** [pester/Pester#286]
Hi 

I have this function in a ps1 file:
function Test()
{
    mkdir "C:\Temp\Foo"
}

Then I use this test:
Describe "Foo" {
    It "bar" {
        Mock mkdir
        Assert-MockCalled mkdir 0 -ParameterFilter { }
	Test
    }
}

I can run it once but if I want to run it again on the same PowerShell session, I have this error: "Could not find Command mkdir"
Is there any workaround to avoid it?

Thanks

Matthieu

**Comment by dlwyatt** [comment]
Hmm, interesting.  This line is the culprit:

```posh
$ExecutionContext.InvokeProvider.Item.Rename("Function:\PesterIsMocking_$CommandName", "script:$CommandName", $true)
```

That is supposed to be restoring the original function when the mock is removed, but it's got that hard-coded "script:" scope.  That's appropriate most of the time, but in this case, mkdir is a function that originally exists in the Global scope, not Script.  As soon as the test script finishes executing, it's gone.

As a temporary workaround, you could just mock New-Item instead (since mkdir is just a simple wrapper around New-Item with the -Type parameter set to "Directory".)  I'll see if there's a simple way for us to fix this in the more general case, though there's probably not a huge need to mock global functions.

**Comment by MatthieuMEZIL** [comment]
Ok. Thanks. I will try with this way.

**Comment by MatthieuMEZIL** [comment]
Just tested. Thanks. It works fine with this workaround
