### ISSUE TITLE
Reset Mock call history

### ISSUE THREAD

**Issue by eliah-hecht-zocdoc** [pester/Pester#313]
I'm not entirely sure if this is a feature request or bug report, since I'm not certain what the intended behavior is, but based on my experiences with other testing frameworks, I expected that if I set up a mock in a `BeforeEach`, each test would have a clean mock with no call history. This code sample should indicate what I mean:

``` posh
Describe "foo" {
    BeforeEach {
        Mock Get-Content
    }

    It "calls get-content" {
        Get-Content "abc"
    }

    It "Sees that Get-Content was called in the previous test" {
        Assert-MockCalled Get-Content # Passes
    }
}
```

I would have expected the second test to fail, but it passes (seeing the call that the previous test had made to `Get-Content`).

**Comment by dlwyatt** [comment]
Running the Mock command again will set up a new active mock implementation, but it doesn't clear the call history.  Instead of putting the Mock command in BeforeEach, you can use the -Scope parameter of Assert-MockCalled. 

    Assert-MockCalled Get-Content -Scope It

**Comment by eliah-hecht-zocdoc** [comment]
Ah, that does work, although now my `Assert-MockCalled` invocations are getting a bit verbose. Is this the pattern you would suggest, though?

**Comment by nohwnd** [comment]
This is an interesting suggestion. When we re-designed Pester between 2.0 and 3.0, we arrived at conclusion that setting `Mock` scope to `It` by default is limiting. But since then I started to write tests that are simpler and rely less on common setup or context of previous tests. 

Personally I would also like this behavior to change. I don't recall when was the last time I needed to verify Mock calls from whole Context or Describe. But unfortunately this is how it was designed for Pester 3 and changing the behavior would be breaking change.

**Comment by SamuelHowes-ma** [comment]
+1

I just started out on Pester and ran into this issue. I expected the scope to be 'It' by default, and had to do some digging to find this issue. 

Based on my experience with other mocking frameworks I would expect scope to default to 'It'

**Comment by jabbera** [comment]
Ditto!

**Comment by DarkLite1** [comment]
+1

**Comment by richardnagle** [comment]
+1

**Comment by nohwnd** [comment]
In v5 Mock scopes to It by default
