### ISSUE TITLE
Debugger seems to have issues stopping on code that runs in Before/After blocks

### ISSUE THREAD

**Issue by theficus** [pester/Pester#319]
I'm not sure if this is a bug in Pester, or a limitation of PowerShell but I wanted to call this out for awareness.

What I'm finding is when I'm trying to debug a a Pester script (I've only tried this in powershell_ise), whenever I set breakpoints in BeforeEach/BeforeAll/AfterEach/AfterAll they are never triggered when hit. It makes troubleshooting a real pain since I don't get a stop where expected.

Even odder, if I call a function from within a Before/After block, and set a breakpoint within that funciton, then the breakpoint does trigger.

**Comment by dlwyatt** [comment]
I'm aware of this, but I'm not sure if I can fix it.  The problem is due to how we support this arrangement:

```posh
Describe 'Whatever' {
    It 'Works' {

    }

    BeforeEach { }
    AfterEach { }
}
```

Even though the BeforeEach / AfterEach blocks occur after the It block, they will still be executed.  When Pester starts a Describe or Context block, it parses the test script to look for BeforeEach / AfterEach blocks, and if it finds any, it creates copies of that code in memory to be executed when it finds any It block.

Those ScriptBlock objects in memory are no longer associated with a file or line number, which is what the debugger needs in order to trigger breakpoints.  I'll do some digging at some point and see if I can reconstruct that information, but it's probably not a high priority.

**Comment by theficus** [comment]
Ah, very interesting. 

This also explains why if I look at the $Error details, ScriptStackTrace looks all funky not showing any details after a certain point of what failed where. That's because it doesn't have the script stack information available to be able to do this due to how it's being invoked from memory.

This can be worked around by calling a function within the Before/After block at least and this is what I do today when I'm trying to troubleshoot something especially tricky.

**Comment by dlwyatt** [comment]
It looks like I can probably fix this in v3 and later by using the AST to search for `BeforeEach` / etc, instead of the current v2-compatible parsing code.  (The ScriptBlockAst class has a GetScriptBlock() method which produces a ScriptBlock object that is still associated with the file and line numbers, unlike ScriptBlock.Create() ).

**Comment by dlwyatt** [comment]
I've got a PR to fix this in v3+, will merge it tomorrow after the tests run.  I wasn't able to get it working in PSv2 yet, but since very few people are likely to be using the v2 ISE or console to set breakpoints in these blocks, I'm not terribly concerned about it.
