### ISSUE TITLE
Mock scoping for It blocks

### ISSUE THREAD

**Issue by eliah-hecht-zocdoc** [pester/Pester#320]
I expected that if I created a mock inside an `It`, the mock would not apply to other `It` blocks (i.e. those other blocks would get the unmocked function). Would it be possible to make that the case? Do you think people are relying on this scope bleed?

**Comment by dlwyatt** [comment]
This is another one of those things that we haven't fixed since that's how it originally worked, and we didn't want to potentially break existing test scripts without a good reason.

That said, we may be leaning toward doing a "clean up" major release for v4.0, fixing some of these annoying bits of behavior.

**Comment by Jaykul** [comment]
Are you saying you're going to **require** moving mocks that are in `Describe` blocks now into `BeforeAll` blocks? That would require us to rewrite just about every use of mocks that we have (which might very well mean every test file we own).

**Comment by nohwnd** [comment]
Ignoring mocks during Discovery, and binding them to their parent block when not in a setup block should not change much, they cannot be filtered to Before* blocks. So if it is not a lot of effort and will make moving from v4 to v5 easier I will do it.

**Comment by nohwnd** [comment]
The scoping is set to `It` by default. The Mock is ignored during discovery, so you can keep them outside of BeforeAll, if that helps making the migration easier.
