### ISSUE TITLE
Mocking CIMObjects

### ISSUE THREAD

**Issue by terrapin893** [pester/Pester#345]
I'm trying to write unit tests for some code I have that does stuff with iSCSI disks.  This includes bringing them online, partitioning and formatting them.  All I'm really trying to do is verify that the required functions are called, and I'm running into an error that seems to be related to the commandlets requiring input in the form of a CIM Object. 
```powershell
#- Function to test
function Connect-LocalISCSIDrive {
    Get-Disk | Set-Disk -IsOffline $false
}

#- Test code
Describe 'example' {
    It 'call functions' {
        Mock Get-Disk { return 0 } -Verifiable
        Mock Set-Disk { return 0 } -Verifiable
        Connect-LocalISCSIDrive
        Assert-VerifiableMocks
    }
}

#- Error
Cannot retrieve the dynamic parameters for the cmdlet. Parameter set cannot be resolved using the specified named parameters.

#- Example of output of Get-Disk (CIM Object)
PS C:\Pester\test> $x = Get-Disk

PS C:\Pester\test> $x.GetType()

IsPublic IsSerial Name                                     BaseType                                                                                                        
-------- -------- ----                                     --------                                                                                                        
True     True     CimInstance                              System.Object  
```
So I'm wondering how this could be done.  Is there a way to mock up a CIM object with the right properties that the Set-Disk cmdlet will take it?  Should I just not unit test something like this?

**Comment by dlwyatt** [comment]
Damn it...  When I write https://github.com/dlwyatt/Pester/commit/56d27d641c23c57d045f0f4852ce5593eb0323c8 , I was thinking it might introduce some sort of bug like this, but I couldn't come up with a way to reproduce it at the time.  I'll look into this soon.

It's nothing to do with the object type, by the way.  You get the same error even if you don't bother to mock Get-Disk:

```posh
#- Function to test 
function Connect-LocalISCSIDrive {
    Get-Disk | Set-Disk -IsOffline $false
}

#- Test code 
Describe 'example' {
    It 'call functions' {
        Mock Set-Disk -Verifiable
        Connect-LocalISCSIDrive
        Assert-VerifiableMocks
    }
}
```

**Comment by terrapin893** [comment]
Thanks for the quick response!

**Comment by dlwyatt** [comment]
This is tricky to solve 100%.  There's a lot going on here, but I'll try to summarize:

- When you mock a command, a mock "bootstrap" function gets injected into your session.  This has copies of the original command's param block, so it can handle pipeline input and all that.  That function's job is just to gather up the parameters that the caller passed, and send them on to Pester's Invoke-Mock command (which is what tests parameter filters, figures out which version of the mock to invoke, records call history, etc.)

- We want these mocks to also inherit the original command's dynamic param behavior.  So the mock bootstrap has a dynamicparam block which calls Pester's Get-MockDynamicParameters command.  When the mocked command is an advanced function, Get-MockDynamicParameters works by invoking a script block which is generated from the contents of the mocked function's dynamicparam block.  Because that dynamicparam block probably relies on logic that reads either $PSCmdlet, or the function's parameter variables, we also copy the original command's param block.  That looks something like this:

```posh
function MockedCommand
{
    [CmdletBinding(DefaultParameterSetName = 'One')]
    param (
        [Parameter(ParameterSetName = 'Two')]
        [Parameter(ParameterSetName = 'Three')]
        [switch] $Test,

        [Parameter(ParameterSetName = 'One', ValueFromPipelineByPropertyName = $true)]
        [string] $One,

        [Parameter(ParameterSetName = 'Two', ValueFromPipelineByPropertyName = $true)]
        [string] $Two,

        [Parameter(ParameterSetName = 'Three', ValueFromPipelineByPropertyName = $true)]
        [string] $Three
    )

    dynamicparam {
        if ($PSBoundParameters.ContainsKey('One'))
        {
            # Generate some dynamic params
        }
    }

    end {
        # Do whatever
    }
}

$dynamicParamCopy = {
    [CmdletBinding(DefaultParameterSetName = 'One')]
    param (
        [Parameter(ParameterSetName = 'Two')]
        [Parameter(ParameterSetName = 'Three')]
        [switch] $Test,

        [Parameter(ParameterSetName = 'One', ValueFromPipelineByPropertyName = $true)]
        [string] $One,

        [Parameter(ParameterSetName = 'Two', ValueFromPipelineByPropertyName = $true)]
        [string] $Two,

        [Parameter(ParameterSetName = 'Three', ValueFromPipelineByPropertyName = $true)]
        [string] $Three
    )

        if ($PSBoundParameters.ContainsKey('One'))
        {
            # Generate some dynamic params
        }
}
```

Seemed like a good idea at the time.  But you're running into a problem with this approach... because we put that copy of the dynamicparam code into a self-contained script block, it is a bit more strict than a normal dynamicparam block, because when a normal dynamicparam block runs, there's still more parameter binding to happen later when pipeline input is taken into account.  That means it doesn't matter if some mandatory parameters are missing at that point in time, or if it can't resolve a particular parameter set yet.

Now, we fixed the mandatory parameters problem by making all parameters in that dynamic param block copy optional.  Now, we could tackle the parameter set problem the same way by just stripping out all of the Parameter attributes, and producing something like this:

```posh
$dynamicParamCopy = {
    [CmdletBinding()]
    param (
        [switch] $Test,
        [string] $One,
        [string] $Two,
        [string] $Three
    )

        if ($PSBoundParameters.ContainsKey('One'))
        {
            # Generate some dynamic params
        }
}
```

I think that should work, but there's one catch that's nagging at me.  In a normal dynamicparam block, it's possible to define logic based on $PSCmdlet.ParameterSetName.  If you tried to mock a function that used that approach in its dynamicparam block, we'd be breaking that now because there wouldn't be any parameter sets anymore.

I need to sleep on this and see if I can come up with a better solution.  I've got some ideas swirling around just as I type this message, but I'm sleepy at the moment, and will come back and read it again tomorrow.  :)

**Comment by dlwyatt** [comment]
Stepping back a little bit here.  I can summarize this more succinctly:  Our goal is to be able to copy the code from an existing function's dynamicparam block, and execute it in such a way that it produces all of the same dynamic parameters (under the same conditions) when calling the mock.  Ideally, this should work for any dynamicparam block, regardless of what's in it.  If it works for the original function, it should work for the mock.

I've added some new tests to the https://github.com/dlwyatt/Pester/tree/DynamicParamFix branch to express the various types of conditions our code might need to handle.  Many of these already pass, but the "cannot resolve parameter set" one is broken at the moment.  The trick is to fix that without breaking the others.  If anyone can think of other types of dynamicparam code that I'm not testing yet, please feel free to chime in.  Automatic variables, stuff to do with module scopes, everything's on the table.
