### ISSUE TITLE
Possible unexpected behavior in Should Be

### ISSUE THREAD

**Issue by modesto** [pester/Pester#388]
Hi,

Given this test:
```
Describe "Should Be should fail, but succeed" {
	It "Shoul Be not equal and fails" {
		@("item1", "item2") | Should Be "item2"
	}

	It "Shoul Be not equal but succeed" {
		"item2" | Should Be @("item1", "item2")
	}
}
```
I think both tests should behave the same way, but the first one fails and the second not

Perhaps the answer is the same to this issue : https://github.com/pester/Pester/issues/328

Regards

**Comment by dlwyatt** [comment]
This will be fixed in v4 (and was covered in PR #252).  The reason for this is that PowerShell's comparison operators behave differently when a collection is on the left, and `Should Be` was just a wrapper around the `-eq` operator at first.  As a side effect of allowing comparison of arrays with `Should Be`, this quirk just goes away.
