### ISSUE TITLE
Exported commands should not contain plural nouns

### ISSUE THREAD

**Issue by rchaganti** [pester/Pester#397]
In the current release (that is inbox with Windows 10 GA), there are cmdlets with plural nouns. 

Assert-VerifiableMocks
Get-MockDynamicParameters
Set-DynamicParameterVariables

As per the PowerShell module [strongly encouraged design guidelines](https://technet.microsoft.com/en-us/library/dd878270%28v=vs.85%29.aspx), the exported commands should not contain plural nouns.

Since Pester in now inbox with Windows 10 and Windows Server 2016, it is recommended that these exported commands contain singular nouns.

**Comment by nohwnd** [comment]
Hello, thanks for the issue.
We are aware that the naming (and other) guidelines are not followed by Pester. Not in just those places that you list, but also in many other places (like Describe, Should, It and so on). The Assert is also not a valid Verb (as per Get-Verb). But unfortunately there is not much we can do about that without breaking what the users of the framework are used to. If we ever finish decoupling the language from the core of the Pester, I already suggested alternative syntax that uses Test-Case, Test-Block, Assert-Equals etc. to make the framework work with PowerShell nicely.

**Comment by dlwyatt** [comment]
Get-MockDynamicParmeters and Set-DynamicParameterValues are really "internal" functions that unfortunately need to be exported for the mocking framework to function (because it jumps back and forth across module scope boundaries.)  Renaming those is no big deal, since we control all of the calls.

Assert-VerifiableMocks is more of a pain, since renaming it would be a breaking change.  We could easily rename the command and then export an alias for backward compatibility, but have you really gained anything at that point?  (Also, this would not affect the version of Pester shipped in Windows 10 anyway.)

**Comment by it-praktyk** [comment]
What about changing it in Pester v.4? 

Means to achieve backward compatibility add functions with current (plural nouns) names with deprecation warnings and rename the real functions?

**Comment by Jaykul** [comment]
That's what [Alias(...)] is for 😉

**Comment by it-praktyk** [comment]
Yes, but with alias displaying of a deprecation warning is not possible (?).

**Comment by nohwnd** [comment]
There already are breaking changes regarding contains, so let's just make it a breaking change as well. It is just a simple replace that can be done over whole test base in seconds.
