### ISSUE TITLE
Mock call operator (&\Ampersand)

### ISSUE THREAD

**Issue by nhudacin** [pester/Pester#415]
Is there a way to mock the call operator? 

I have several functions where I'm using this and I would like to test the functions without having to setup a ton of additional stuff for MSBuild, MSTest, etc. 

I was using invoke-expression because that's an easy Mock BUT invoke-expression does not handle spaces in arguments at all which is a deal breaker for me. 

Any other ideas?

**Comment by dlwyatt** [comment]
Do you have an example of the code?  The way Pester's mocking works, is it intercepts PowerShell's command resolution.  So this works fine:

```posh
$commandName = 'Get-Content'
Mock $commandName

& $commandName
```

Because you're using the & operator on a string, which still goes through the normal resolution process.  However, this would not work:

```posh
$command = Get-Command Get-Content -CommandType Cmdlet
Mock Get-Content

& $command
```

Because you're using the & operator on the cmdlet specifically, so PowerShell never tries to resolve the Get-Content name to find the mock.

**Comment by nhudacin** [comment]
Here's some example code: 

```powershell
& SQLPackage.exe /a:Script /sf:$sourceDacPac /tf:$targetDacPac /tdn:$targetDatabaseName /op:$(Join-Path $outputPath ($targetDatabaseName + '_deployment.sql')) /pr:$(Join-Path $publishProfilePath DB.Release.publish.xml)
```

That's in a function called Get-ReleaseSQLScripts and I would like to mock the result of sqlpackage.exe to have both a successful and unsuccesful outputs. 

This is my current workaround which wasn't working until a few minutes ago. Setting the $Global:LastExitCode seems to be working. 

```powershell

function Invoke-ExternalCommand {

    # Reset $result in case it's used somewhere else
    $result = $null

    # Reset $LASTEXITCODE in case it was tripped somewhere
    $Global:LASTEXITCODE = 0

    $result = & $command $arguments  

    if ($LASTEXITCODE -ne 0) {
        Throw "Something bad happened while executing $command. Details: $($result | Out-String)"
    }

    Write-Verbose "$($result | Out-String)"
}

# Called from other functions like this: 
Invoke-ExternalCommand MSTest.exe @(
                "/testcontainer:$testContainer",
                "/resultsfile:$outputFile")

```

**Comment by dlwyatt** [comment]
Ah.  The call operator isn't really a problem here, but mocking external commands (or scripts) with Pester is unfortunately a bit flaky, and I wouldn't recommend doing it.  Wrapping those calls in a PowerShell function, as you've done with Invoke-ExternalCommand, is a good workaround because then you can just mock Invoke-ExternalCommand instead.

**Comment by nhudacin** [comment]
Ok cool!! Thanks (again) for the help @dlwyatt! :+1: 

Closing the issue.

**Comment by b4tt1enet** [comment]
@dlwyatt I just want to confirm based on your previous post - is it impossible then to mock a command that is retrieved through Get-Command?

I'm wondering if I need to change my code to not use Get-Command, or if there is a way to test it as it is. My code is basically what you wrote in your post:

```PowerShell
$command = Get-Command Get-Content -CommandType Cmdlet
Mock Get-Content

& $command
```

**Comment by dlwyatt** [comment]
Depends on how and when you call Get-Command.  If it's called after the mock has been created, and allows for `Alias` results (or `Function`, in earlier version of Pester), then you could still wind up executing the mock (because the mock is what Get-Command would return).  When you specify `-CommandType Cmdlet`, though, you'll always be executing the original command rather than the mock.

**Comment by DarkLite1** [comment]
One could also use `Start-Process $Command` and mock that.
