### ISSUE TITLE
Need a way of skipping tests on Describe and Context level.

### ISSUE THREAD

**Issue by BerheAbrha** [pester/Pester#442]
Hello,

There are times when we need to skip the whole Describe clock or group of tests grouped in to Context block.  But So far the parameter -Skip is only applicable to 'It'.  This request is to implement a way to skip group of tests or the whole describe block based on Certain condition. 

Describe TestCalculator -skip:$calculatorDoesNotExist  {
Context AdditionTests -skip:$calculatorDoesNotExist {
It Addition {..}
It subtraction {..}
It Multiplication {..}
}
}

**Comment by dlwyatt** [comment]
Hmm.  In the short term (if you don't need PowerShell v2 support), you could just use `$PSDefaultParameterValues` to do this.

```posh
Describe TestCalculator {
    $PSDefaultParameterValues = @{ 'It:Skip' = $calculatorDoesNotExist }
    It Addition {..}
    It subtraction {..}
    It Multiplication {..}
}
```

It would be easy to implement a Skip parameter that is inherited by any `It` blocks inside a Context / Describe, but any code that you have running outside of the `It` blocks would still have to run, if you wanted to have any record of those skipped tests in your output.  Alternatively, we could just skip the entire body of the describe (which would prevent any `It` blocks from showing up in the test results, even as a skipped test.)  Neither of those solutions is ideal, but it's what we have to work with.

Incidentally, that second scenario (skipping the entire `Describe` body could be done right now by wrapping it in an `if` statement:

```posh
Describe TestCalculator {
    if ($calculatorExists)
    {
        It Addition {..}
        It subtraction {..}
        It Multiplication {..}
    }
}
```

**Comment by BerheAbrha** [comment]
$PSDefaultParameterValues = @{ 'It:Skip' = $calculatorDoesNotExist } is great idea in terms of avoiding specifying  -Skip parameter in each test. But it is still going to execute initializing logics that might be inside context block. The work around for now as you explained it above is to use if-logic both for Context and Describe blocks. And this request is, to support the -Skip parameter for context and Describe block so that test authors will avoid nesting one more if-statement.

**Comment by dlwyatt** [comment]
I'm not sure that's a good implementation for us either, unfortunately.  In an ideal world, we would have a tests definition file that gets parsed all ahead of time, so we know what Describe / Context / It block structure there is.  Then we could skip entire Describe / Context blocks, the way you suggest, and still log information about any children that were also skipped.  If we get to a point where we drop support for PowerShell v2, that might even be an option.

For now, though, we know nothing about the children of a Describe or Context until it gets executed.  So if we skip the entire Describe, we lose information about any of the tests that it contained, and any type of `-Skip` parameter we add should really be marking those tests as skipped in the output somehow.

**Comment by TravisEz13** [comment]
I'm facing the same issue @BerheAbrha was on a somewhat separate project (completely separate code wise.)  Basically +1.

Could you do a compromise implementation that knows about the children if running on newer versions of PS, but doesn't on PS 2?  BTW, I need at least basic PowerShell 2 support.

**Comment by dlwyatt** [comment]
There's a similar discussion going on in #461 .  In addition to PowerShell v2 not being supported, any tests that are split across multiple files would also not filter properly (assuming that any calls to Pester commands such as Describe and It were made in the other files.)  However, within those limitations, this seems to be a popular enough request that I may just do it.

**Comment by KarolKaczmarek** [comment]
+1,  I need this functionality as well

**Comment by BlackAngelTiger** [comment]
May be the Tags can help you to exclude or skip tests you do not want to execute at the moment.
A example of this can be found here: https://github.com/pester/Pester/wiki/Describe#tags

**Comment by TravisEz13** [comment]
@BlackAngelTiger 
The thread has already discussed why `Skip` doesn't completely solve the problem (https://github.com/pester/Pester/issues/442#issuecomment-166708838).
> it is still going to execute initializing logic that might be inside context block

Regarding using tags to skip, in a large test suite, creating tags to skip for every condition and then the combinations of conditions used in tests would be unwieldy.  I think the current solution of using `skip` works better.

**Comment by majkinetor** [comment]
I am currently writing tests upward and put the `exit` after it, but that also isn't enough. You want to be able to quickly run ONLY desired test. How about special parameter on It and Context which essentially ignores _everything else_. 

Lets say we have parameter `Debug` that when present, forces tests to run and ignores everything else. 
If `Debug` is present on any element, only elements marked with it run. It makes sense to have `IgnoreDebug` on pester level to change this behavior (so if dev forgots to remove it, build server can still run everything).

Consider this example

```
Context 1 {
  It 1
  It 1 -Debug`
}

Context 2 -Debug {
    It 3
    It 4
}

Context 3
```
`pester` will run It 1,3,4
`pester -IgnoreDebug` will run everything.

This will make developing and debugging much faster.

**Comment by ffeldhaus** [comment]
A big problem with the current limitation to skip only `It` blocks is, that `BeforeAll`, `BeforeEach` and `AfterAll`, `AfterEach` Blocks are still executed, even if no tests will be executed. Especially for complet test setup / finalization, this can cause a large test overhead.

What needs to be done to implement this?

**Comment by nohwnd** [comment]
@ffeldhaus  a lot of stuff 🙂 I am implementing it [here](https://github.com/nohwnd/Pester/tree/new-runtime).

**Comment by TravisEz13** [comment]
@nohwnd 	does you change try to address this issue?  I've been thinking about it since and I think an object that I can read test results would solve a lot of by problems.

But what I really want to be able to say is don't run test B if test A fails (yes, implying that test B depends on test A.)

**Comment by nohwnd** [comment]
@TravisEz13 Depends on which problem you mean.

### Running setups for everything even if no test will run - yes.
 I execute all the files twice, which sounds scary but if your tests have all code in pester controlled blocks I can run all Describes and Its (but not the scripblock associated with the It), so I get the structure of the tests even if you put them in different files, or wrap them in functions. This collects everything in a big hierarchical object on which I then determine which tests should run by evaluating filters. Another upside is that before* and after* blocks don't have to be parsed because I just capture them during discovery, and then execute them in the appropriate place. On the second pass I run every describe and test that is marked as Should run, effectively executing only those setups and teardowns that need to run. I also have a block that controls your dependencies, so I dot-source them only during execution and only when any block in the current file will run.

### Dependencies among tests - Not yet
At the moment there are no dependencies among tests,  and the state I publish into the test is limited to just it's name. But I write it in a way that a plugin can access the whole state of the current block/test, so it should be easy to add, and I can see that being able to fail all tests when one test fails to be requested quite a lot and this is quite similar.

**Comment by majkinetor** [comment]
> At the moment there are no dependencies among tests, 

This can be considered anti pattern. 

BTW, nobody had any comment on my proposal [here](https://github.com/pester/Pester/issues/442#issuecomment-441612536). Is there any other way to achieve skipping irrelevant tests why debugging single test ?

**Comment by nohwnd** [comment]
@majkinetor yes, I am aware of that, but it's usefulf for environment testing where you don't want to spend doing 40 more requests to server when you detected that it is offline. 

Forcing only a single test to run is not possible right now, but I'd like to achieve the same functionality in the new runtime, it's pretty much a very strict implicit filter, but you set it based on the test, and not when you provide parameters to Invoke-Pester.

**Comment by TravisEz13** [comment]
I agree that dependencies among tests should not be encouraged, but it's not always best to eliminate them.  In my tests, first I'm testing that the docker image actually got created.  If the docker image isn't there, there is no reason to run all the tests for that image.  The tests are identical for all images.  So, tags are not a good way of managing this.  I also don't want to just remove the test case from the list because I would like the test results to be accurate.

Actually, thinking about it now, a way to skip via a command in the test case or via the test data would probably be better for my current scenario.

**Comment by nohwnd** [comment]
Summmary for myself: 

Multiple issues mentioned here:
- Dependencies among tests. I plan to add failing after first failed test, is tracked here #360 and will probably need more research with people who actually write env valiadation tests 
- Running just one test and only it's setups - that already works, and one test / block can be selected by `-Focus` ✔

- if there is -Skip on block it will allow to easily skip everything in that block, this should cover most of the cases

- so the only difficult thing is to -Skip on a given predicate when it does not apply to the whole file, one such case might be skipping tests that can only run on windows, this could be solved more systematically by adding `-Platform` switch or something like that 

- othewise you are probably mixing together tests that shold not be together, but anyways, leveraging the default parameter value we could provide a scriptblock predicate that would evaluate against the block / test, giving a fine grained, context aware control. This is not the same as having a -Filter on Invoke-Pester that takes a scriptblock, because in this case you want to determine if the test should be skipped based on result of some local function. This is very similar to Set-ItResult, the only thing it avoids is putting Set-ItResult in every test.

- for the other cases there are other filters that can filter the tests based on names, tag filters that can filter on blocks and tests, and name filters that can filter on test. So imho adding -Skip to block would solve 99% of those issues, and the rest can be post poned to avoid overengeneering this. 

The main issue of skipping whole blocks I am tracking in #1266, the rest I will look into when I find out what are people using -Skip for.
