### ISSUE TITLE
Invoke-Pester should be able to support .pst1 files (Future possibility)

### ISSUE THREAD

**Issue by kilasuit** [pester/Pester#444]
Recently whilst getting to grips with Pester I found it frustrating that there wasn't an included default "testing" file type and that there was a need to have the tests in a `filename.tests.ps1` file.

So I have raised on User Voice to add pst1 as an accepted file extension dedicated only to tests which can be seen and upvoted here http://bit.ly/pst1ext

**Comment by dlwyatt** [comment]
In order to invoke PST1 files as scripts, they'd need to change the PowerShell engine, I think.  That would mean the files only work in the latest version of PowerShell, and you wouldn't be able to execute those tests against older versions.  If the PowerShell team does add that extension as an executable option at some point, I would of course add it to the Pester module (for supported PowerShell versions), but personally, I wouldn't be using that option for a very long time, because I want to test my modules against many different PS versions.

**Comment by it-praktyk** [comment]
Due to lack of discussion and votes of your request http://bit.ly/pst1ext I assume that we can close the current issue. Feel free to reopen if you can add something new. Thank you for your understanding.
