### ISSUE TITLE
Updating Pester on Windows 10

### ISSUE THREAD

**Issue by mrboring** [pester/Pester#488]
Hi

I'm using Windows 10 which comes with Pester. I can sucessfully update Pester and a new version appears in the following folder:

C:\Program Files\WindowsPowerShell\Modules\Pester

I've removed some versions and I'm left with two sub-folders:

3.3.5
3.4.0

If I do `Import-Module Pester` I always get 3.3.5. The only way I can get the latest version is to add the following to my profile, or type if from the Powershell commandline:

`Import-Module "C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Pester.psd1"`

Does Powershell's autodiscovery of modules understand versioning, or do I have to update my Profile each time a new version of Powershell is released?

Thanks.

Alan

**Comment by nohwnd** [comment]
@mrboring Seems to be working on my Windows 10. I started with Pester `3.3.5` (not imported to the current session). Then I did `Install-Module Pester -Force`, which installed the newest version, and then on import I got the newer version imported. I am on the latest stable build of Windows 10, with the standard version of PowerShell that comes with it. 
![image](https://cloud.githubusercontent.com/assets/5735905/13774827/5ddc9396-eaa1-11e5-81e9-5dee76624dd9.png)

**Comment by mrboring** [comment]
@nohwnd 
Not sure how I did it, but I had several versions and I was using `Update-Module`. I think that because I had a version other than 3.3.5 the update worked, but is did not register the new version.

So, as you pointed out, I then used Install-Module with -Force and it worked.

Thanks for the quick response.

**Comment by kilasuit** [comment]
However I am also getting the same issue - this is caused as by default Pester wasn't installed using install-module as seen in this screen shot  - even using -Force doesn't work :-1: 

![pester](https://cloud.githubusercontent.com/assets/6355225/13775662/b93917a4-ea9d-11e5-88aa-43773e1d7bb0.JPG)

I think that this is a bug for the OneGet repo more than on here but good to see the work around by @nohwnd

**Comment by nohwnd** [comment]
@kilasuit well to be honest I was surprised that it worked for me, because I was getting the same error as you do on older versions of Windows, but I thought they simply fixed it. Are you on the latest stable with all updates?

**Comment by dlwyatt** [comment]
That's a bummer.  We asked them to try to include the XML metadata file that would allow for a no-hassle `Update-Module` on a clean install of Windows 10, but I guess that never happened.  So yeah, use `Install-Module -Force`.

With the side-by-side module installation support in PowerShell v5, there's really no difference between `Install-Module` and `Update-Module` anyway.

**Comment by kilasuit** [comment]
Its not just the Pester one either - PackageMangement & PowerShellGet modules suffer this too as they are bundled into the OS (as will any other modules not installed via Install-Module)

@nohwnd I've been on Insider Fast Ring on this machine since September.

I kind of understand the reason behind it - but disagree with the implementation as the PSGallery is untrusted by default which means that it will still prompt the user when -Force isn't used.

However if you install a lower version from PSGallery (so after 3.3.5 but not 3.4.0 - I chose 3.3.10) using Install-Module then Update-Module will work as expected as shown below because of the inclusion of the PSGetModuleInfo xml file in the module install location.
![pester2](https://cloud.githubusercontent.com/assets/6355225/13784217/4cd20020-eac6-11e5-9ed0-7ed39285c93b.JPG)
