### ISSUE TITLE
Error message is not helpful when missing Name parameter value

### ISSUE THREAD

**Issue by juneb** [pester/Pester#496]
When you use Describe/Context/InModuleScope without the required name string, you get an error message that says there's no scriptblock. 

This is a fantastic error message when you've misplaced your opening brace, but it doesn't help when the name is missing. 

Please change it so it detects the missing name and returns a helpful error message. Thanks!

**Comment by dlwyatt** [comment]
Hrm.  That's PowerShell being helpful.  The syntax for those commands (with positional parameters) is `Command <string> <ScriptBlock>`.  If you omit the string, PowerShell casts your ScriptBlock object to a string (because literally everything can be represented as a string in .NET), and then by the time Pester's code gets to look at the parameters, it sees that you've "passed" an argument to Name, but not ScriptBlock.

Off the top of my head, I can think of two ways to solve this:

- If either Name or ScriptBlock are missing, just give a generic Syntax message that shows them both as required (while still mentioning the "opening brace can't be on the next line" hint.)
- Change the parameter type of `$Name` from `[string]` to `[object]`.  That'll allow us to detect if someone passed a ScriptBlock to the command for the Name parameter, and give a more useful error message.  However, things like `Get-Command -Syntax` and `Get-Help` won't be as nice, since Name will no longer show up as a string.

I also considered looking at `$MyInvocation.Line` to see if it looks like someone passed just a script block, but there are too many edge cases for that to be my preferred approach.  (Other named parameters first such as `-Tags` or `-TestCases`, multi-line calls, people passing variables or expressions as arguments, etc.)

**Comment by juneb** [comment]
That's tough. From a usability standpoint, I would recommend leaving the type as <String> to help users and adding both cases to the error message. It's easier for the end user to understand and both cases are easy for the user to detect.

RuntimeException: Can't find the test script block. Have you put the open curly brace on the next line? Do all Describe, Context, It, and InModuleScope script blocks have a name string?

**Comment by nohwnd** [comment]
I think we can be as verbose as we need so how about having something like this: 

```
Name or Test parameter is null. There are multiple possible causes of this problem. 
Please inspect the values of the parameters and decide which action needs to be taken.
  Name: '$name'
  Test: '$test'
  - If the name is populated with your test code, then you did not specify the name, 
and due to positional parameter binding powershell cannot infer that.
  - If the name is populated with name-like value, and test is empty then you either forgot to define a test script block or you positioned the opening { on the next line, but it has to be on the current line.
   - If both values are empty you forgot to provide both name and test script block.

        Here is an example of a well formed It block: 
        It "has the name specified first" { # and curly brace goes on the same line
            #your test code goeshere
        }"

**Comment by dlwyatt** [comment]
The script block that gets passed in is likely to be a large number of lines; we probably don't want to embed the values of `$name` or `$test` into the error message.  I think something like this would be sufficient:

```
Name or Test parameter is null.  Syntax:  Describe <Name> <ScriptBlock>.  Make sure the opening brace for your script block is on the same line as the Describe command.
```

**Comment by nohwnd** [comment]
So a shortened script, one two lines max, just to be able to tell that the scriptblock got passed as Name? I can't tell how grateful I am as a developer for getting an exception message that tells me exactly what is wrong instead of letting me guess, or forcing me to use breakpoints.

But it's your  call :)

**Comment by juneb** [comment]
I really respect everyone on this team for their excellent contributions, but I have to disagree on the extended error message. It's wordy and all that red text is intimidating and not necessary. Remember the super-long error message when New-PSSession failed to connect? I think the thing went on for a page listing possible reasons that the machine couldn't connect. Not a great idea. 

Also, I was wondering why the Name parameter is always required. As a user, I understand its value for Invoke-Pester -TestName, but not everyone uses it and you can always use -Tag. Can't Pester generate random names when none are provided?

**Comment by nohwnd** [comment]
@juneb I do remember it, and I also remember that it never helped me. :)

**Comment by it-praktyk** [comment]
Sorry, what is it a conclusion?
Should we close it now or assign to be triaged once again?

**Comment by nohwnd** [comment]
How about we simply look at the value of `$Name` as if it is more than 1 line and `$ScriptBlock` is missing we fail with message that suggests that user might have forgotten to provide `-Name`? Like this: 

```powershell
function a {
    [CmdletBinding()]
    param(
    [String] $Name, 
    [ScriptBlock]$ScriptBlock) 

    
    if ($null -eq $ScriptBlock) 
    {
        $potentialScriptBlock = $Name -split "`n" | Select -First 3
        if (@($potentialScriptBlock).Length -gt 1)
        {
            throw "ScriptBlock is missing, but the Name has multiple lines. Is it possible that you forgot to provide -Name and ScriptBlock is now incorrectly passed as -Name?`nProvided value: $($potentialScriptBlock -join "`n")`n..."
        }
    }
    "works"
}

# works fine
a "name" { 
"a"
"b"
}

# prints error
a {
"a"
"b"
}
```
![image](https://user-images.githubusercontent.com/5735905/50053176-8f8dbe80-0130-11e9-9e4b-05d0578d2813.png)

**Comment by jd-porter** [comment]
Hello, first-time contributor, long-time fan. I'm interested in fixing this issue.

Based on the discussion so far, maybe we should keep errors text brief but informative (in line with current error wording). I like @nohwnd's approach to determining if a name looks like a script block, too.  Tried using some ValidationScripts on parameters, but they don't seem to be the right approach in this situation.

**Comment by nohwnd** [comment]
Hello @jd-porter thanks, I am glad you like Pester. 🙂 

I think that validate script is not the place to do this, instead you need to place an `if` like [this one](https://github.com/pester/Pester/blob/master/Functions/It.ps1#L154-L156), that checks if we got a value to the `-Test` parameter, and if not it looks at `-Name` and when that has multiple lines, then user most likely forgot to provide the name. So you throw a message like the one I described. 

Where the `if` should be placed in relation to the one that already is there, is left for you to figure out. You might also have a look on `Describe` I am sure the same logic should apply there. 

If you have any problems let me know, I am sure I can help you, you can reach me here, on twitter, or on powershell slack.
