### ISSUE TITLE
Error message not helpful when missing scriptblock

### ISSUE THREAD

**Issue by juneb** [pester/Pester#498]
I forgot to enclose my input to Should Not Throw in curly braces. The message that I got about an ampersand looks like some code fails to handle a very predictable exception.

Can we please fix this?

    [-] Error occurred in Context block 403ms
      Expected: the expression not to throw an exception. Message was {The expression after '&' in a
 pipeline element produced an object that was not valid. It must result in a command name, a script
block, or a CommandInfo object.}...

**Comment by nohwnd** [comment]
This can be fixed by making the `scriptblock` parameter of  `PesterThrow` mandatory. If you input null or you specify a function that has void output and you forget to wrap it in a script block, the assertion will fail to run. As an added bonus it will also fix this use case: 

```powershell
describe "null behavior" {
    function sut { 
        $processes = Get-Process 
        #nothing is returned
    }

    it "falsly passes" {
        sut | should throw
    }
}
``` 

Originally the `$null` the `sut` returns failed to convert to scriptblock, which threw the exception you mentioned, and the test passed, because it expected an exception.

Now the question is: should we let the powershell do the null check and output the generic message, or should we do the check ourselves and output something like: The scriptblock is null, you likely forgot to wrap your  code in a script block: Correct form is `{ Get-Something } | Should Throw`? 

I like the custom exception more, how would you word it?  

As a side note there is a whole other range or errors that you will get when you forget to wrap a function that *has* output. In that case you get a conversion error (can't cast "System.Process" to ScriptBlock for example), and those we can't catch and convert to custom exceptions (at least not in the PesterThrow), but I assume that those errors are easier to debug, because they are not that misleading.

**Comment by dlwyatt** [comment]
We could change the parameter in PesterThrow to just be an Object, and check to make sure it's a non-null ScriptBlock ourselves.  That'll give us the opportunity to give a useful error message no matter what happened earlier in the pipeline.

**Comment by nohwnd** [comment]
That's also an option. For me the conversion error is obvious and common enough that most of the people getting it should be able to see what's wrong. What do you think?

**Comment by juneb** [comment]
If you're asking me what I think, I prefer the technique that generates the useful error message. The message about the ampersand reveals implementation details that are not otherwise surfaced to the user.

If you need help with an error message or any other text, please feel free to assign the bug to me, if that's possible.

For this one, I think something like this would be helpful:
"Scriptblock not found. Input to 'Throw' and 'Not Throw' must be enclosed in curly braces."

**Comment by nohwnd** [comment]
@juneb Thanks for the wording of the message. I made a PR for the change.
