### ISSUE TITLE
No example for Fixture parameter of Context 

### ISSUE THREAD

**Issue by juneb** [pester/Pester#500]
Please add an example. I'm not sure how the Fixture parameter is supposed to work.

In general, each parameter of a command should appear in at least one help example.

**Comment by dlwyatt** [comment]
Strictly speaking, every example has Fixture in it.  That's the script block.

Pester's written with PowerShell functions, but the base parts are sort of intended to be its own language.  I write Contexts like this:

```posh
Context 'Some Name' {
    # Some Code
}
```

rather than this:

```posh
Context -Name 'Some Name' -Fixture {
    # Some Code
}
```

Even though both are valid syntax, and I'd lean toward avoiding positional parameters in general, for a Pester test script the parameter names just get in the way.  It would be like having to put named parameters in for `if` statements:

```posh
if -Condition ($i -gt 5) -Action {
   # Do-Something
}
```

**Comment by juneb** [comment]
Makes sense.
