### ISSUE TITLE
Pester project needs an error message file

### ISSUE THREAD

**Issue by juneb** [pester/Pester#524]
We should establish an error message file, so we can track, edit, and reuse standard error messages, instead of having spontaneous, unedited error messages strewn among the files. 

We can use the strategy designed in about_Scripts_Internationalization and name the file something like \en-US\PesterErrors.psd1.

Then, in each psm1 or ps1:
`Import-LocalizedData -BindingVariable msgTable -FileName PesterErrors.psd1`

**Comment by nohwnd** [comment]
Quick search in the code for 'throw' and 'write-error' shown 32 usages of throw and 2 usages of write-error. Good half of it, is the Throw part of Should Throw. With that few usages, there might be probably one or two error messages that can be reused. Is it really worth it to move the errors from the code to a separate file?

**Comment by juneb** [comment]
Structurally, yes. Let's see what other people have to say.

**Comment by dlwyatt** [comment]
In the v4 dev branch, there's already a strings file for that sort of thing.  (It was introduced by @Jaykul for the differences between Gherkin and Pester tests, but we can move error messages and other such things into there as well.)

**Comment by iainbrighton** [comment]
And it will of course enable easy localisation (see what I did there?!) if needed/wanted in future.

**Comment by nohwnd** [comment]
I am going to close this, if we decide to do it in the future then we can open a new issue, but at the moment I don't see that this would happen, and I don't want to support the added complexity in the code. So this issue would just hang around as it did till now.

I don't see enough benefits in moving to any other language to warrant the complexity it would add. There are just a few error messages, but Should adds `-Because` strings and there will be more features where we print the output based on context and options that user provided, making it form at least remotely proper English is difficult as is, adding another language would be way more complex. Hope you understand. 😊
