### ISSUE TITLE
Pester tests misbehave with closures

### ISSUE THREAD

**Issue by lmmarsano** [pester/Pester#525]
See [lmmarsano/pester-closure-issue](//github.com/lmmarsano/pester-closure-issue) for a unit test demonstrating the problem.

Something strange goes on with a closure's name bindings in unit tests.
This code
```powershell
Set-StrictMode -Version latest
function Outer {
    {
        Inner
    }.GetNewClosure()
}
function Inner {
    'call Inner'
}
```
and this unit test
```powershell
Describe 'function in closure' {
    Context 'original' {
        $closure = Outer
        It 'runs normally' {
            $closure | Should Not Throw 
        }
    }
    Context 'mock' {
        $Inner = Get-Command -CommandType Function -Name Inner
        Mock Inner { & $Inner @args }
        $closure = Outer
        It 'runs normally' {
            $closure | Should Not Throw 
        }
    }
}
```
fail with `CommandNotFoundException`.
The presence of `.GetNewClosure()` sets the difference between failure and success.
Direct calls from the console, in contrast, don't raise exceptions.

**Comment by dlwyatt** [comment]
That's not a Pester problem.  Can reproduce the same behavior like this:

```posh
Set-StrictMode -Version latest
function Outer {
    {
        Inner
    }.GetNewClosure()
}
function Inner {
    'call Inner'
}

$closure = Outer
& $closure
```

When you create a new closure, it's essentially creating a script module in memory, behind the scenes, with a snapshot of whatever variables existed at the time the closure was created.  The `Inner` function isn't actually resolved until you execute the closure, though, and at that point, this anonymous script module can't see functions defined in your script (unless that script happens to be dot-sourced into the Global scope.)

Here's how you can make it work in both cases, whether Pester is involved or not:

```posh
function Outer {
    $innerFunction = Get-Command Inner -CommandType Function

    {
        & $innerFunction
    }.GetNewClosure()
}
```

This way, the `Inner` command resolution happens in the `Outer` function, not in the closure.  Since you assigned the result to a variable, that variable is captured when the closure is created, and everything works fine.

**Comment by lmmarsano** [comment]
Thanks: that explains a lot.
It unsettles me that the closure call would still not resolve the `Inner` function when they're in the same script.
Not a Pester problem, though.
