### ISSUE TITLE
How to mock and retrieve the Get-Disk object to a variable.

### ISSUE THREAD

**Issue by sathish1000** [pester/Pester#543]
I have the following lines to Mock..

$DiskDetails= Get-Disk 
I want to mock Get-Disk but assign a Get-Disk object {with values filled by me} to $DiskDetails so that I use $DiskDetails values down the line. 
Can you help me with this ?

**Comment by dlwyatt** [comment]
Depends on what you need to do with the object later.  If you're just accessing its properties yourself, then you can have your mock return a PSObject with the same property names.  If you need to pass the object on to another function, then a PSObject may not work because of type constraints (even if you're mocking the other command).  Then the solution becomes trickier; depends on the type of object you're dealing with.

In the case of Get-Disk, it's a CIM object, and you can create instances using New-CimInstance with the -ClientOnly switch.  Something like this:

```posh
$disk = New-CimInstance -Namespace Root/Microsoft/Windows/Storage -ClassName MSFT_Disk -ClientOnly
```

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
