### ISSUE TITLE
V4:  Nice to have: Merge Invoke-Pester and Invoke-Gherkin to a single command

### ISSUE THREAD

**Issue by dlwyatt** [pester/Pester#552]
It can simply look for *.Tests.ps1 files and use the Pester execution, and find *.scenario files to use Gherkin execution.

Possible annoyance:   Pester and Gherkin each have their own style of output.  It's easy to fix the console output as things are executing (Scenario versus Describe, etc), but the summary would have a combined total from both.  Should we have two summaries, one for Pester Tests.ps1 files and one for Gherkin scenarios?  Or just combine them and not worry about the wording?

**Comment by redoz** [comment]
I think I'd rather seem the kept separate, but I'm not a Gherkin user (and doubt I ever will be). 
My personal feeling is that Gherkin != Pester, so why does Pester even support it? Obviously I'm missing a lot of back story here but it feels like there should be a Gherkin module depending on Pester that could then be a shim converting/executing the Gherkin tests using Pester as the underlying engine.

**Comment by Remco-74** [comment]
I'm not really interested in using Gherkin style testing either, and see it more as overhead for Pester. Please leave Pester and Gherkin separate.

**Comment by dlwyatt** [comment]
Not sure I understand why people who have no intention of using Gherkin will care one way or the other.  If you don't have any .scenario files in your folder structure, you won't be incurring any more overhead.  Likewise for people who are only using Gherkin, for that matter.  The only people who are likely to be impacted are projects who have a mix of both, for some reason.

**Comment by michaeltlombardi** [comment]
We'd like to switch to using Gherkin in the future but have been making do with vanilla Pester tests for now (and because that's what much of the community has been using).

I'm not sure it would make maintainable sense to split the two projects back up again. I also like having the option to specify tests for private functions and scenarios for public. For some reason that makes more sense to my brain.

**Comment by redoz** [comment]
@dlwyatt Well, I wouldn't hitch a caravan to my car unless I'm actually going camping. In the same way it seems like supporting Gherkin in the Pester project means we'll have an increased maintenance cost for something we don't use. But like I said, I don't know what the back story is here, and maybe the code to support Gherkin is trivial?

But it does means that if I want to contribute to Pester, I might also have to learn Gherkin in order to make sure that keeps working.

This is obviously not something I feel that strongly about, Pester isn't my project, and I'm not going to abandon or fork it over something like this. I'm just providing my point of view as someone who sees Pester as an increasingly important tool and something I would like to contribute to in the future.

**Comment by it-praktyk** [comment]
What is a conclusion of this issue? Does should it be still open? IMHO not.
