### ISSUE TITLE
Unable to create an object in a test and use it in another

### ISSUE THREAD

**Issue by jeffchulg** [pester/Pester#561]
Hi,

I want to use an object in all my test suite. To do it, I want a test to create and initialize the object and other tests that will use it.

Here is an example of what I want to do:

```powershell
$TemporaryLogger=$null
Describe "Test home made PoSH Logger" {
    It "Check that New-Logger function is available and create logger object" {
        $TemporaryLogger = New-Logger  ...
    }
    It "Uses the logger object" {
        $TemporaryLogger.Info("Message")
    }
}
```

I get an error as the TemporaryLogger variable is not set at test level but at the "It" block level.

Is there a way to make it work ?

**Comment by nohwnd** [comment]
It does not work because `It` is a scriptblock, and you are creating a locally scoped variable. 
This is basically what's happening:

```powershell
$a = "original"
&{ $a = 10 }
&{ "a is: $a" }

#outputs: a is: original
```
You first set your variable to null, and then you create another *child* variable with the same name in the `It` scope. The child variable is only valid inside of the `It` scope (it hides the parent variable becuase they have the same name).

As soon as the execution leaves the first `It`, the variable is back to $null. In the second `It` you can read the parent variable, but you can't write it (at least not by a simple assignment). 

To overcome this problem you would either need to lookup the variable in the parent scope explicitly, or you can set the variable to reside in a well known parent scope such as `script` or `global`.
```powershell
$script:a = "original"
&{ $script:a = 10 }
&{ "a is: $script:a" }

#outputs: a is: 10
```
This might or might not be a good idea. Personally I think that using the `script` scope in test is quite fine as long as you don't assert on the resulting data and do not rely on order of test execution (which your tests do not meet, because all tests rely on the first test initializing the logger.)

If you are tempted to make the logger global and then you should rather go with modules and hide the state inside of a module rather than putting it in global scope. 






one more example: 
```powershell
$script:a = "scriptscoped"
&{ 
    
    $a = "localscoped"

    #look at the values in different scopes
    Get-Variable -name a -scope script | ft name, value
    Get-Variable -name a  -scope local  | ft name, value
}
```

**Comment by jeffchulg** [comment]
Hi,
thank you for the explanation. It is now crytal clear.
This is a particular test in which, unfortunately, the BeforeEach block is (to me) out of the scope.

**Comment by nohwnd** [comment]
You are welcome.
