### ISSUE TITLE
Is there a way to Mock start-jobs ?

### ISSUE THREAD

**Issue by sathish1000** [pester/Pester#575]
I have a code that starts background jobs. 
```powershell
Start-Job -ScriptBlock $scriptBlock -argumentlist $urlList[$i]
```
I tried two things.

First, to write a dummy scriptblock in my tests code and pass it. For that, it says:
```
ParameterBindingArgumentTransformationException: 
Cannot process argument transformation on parameter 'script'. 
Cannot convert the "System.Management.Automation.PSRemotingJob" 
value of type "System.Management.Automation.PSRemotingJob" to type 
System.Management.Automation.ScriptBlock".
```

Secondly, I tried to Mock Start-Jobs by returning a $true.

    Mock Start-Job {
        return $true
    }

But it says, 
```
Wait-Job : The input object cannot be bound to any parameters for the 
command either because the command does not take pipeline input or the 
input and its properties do not match any of the parameters that take pipeline
input.
```

how should i go abt this ?

**Comment by nohwnd** [comment]
The first error tells you that you are passing a job object to the scriptblock parameter and it cannot convert. I am not really sure what you were trying to do there. 

The second error is produced because you are returning boolean from Start-Job mock but Wait-Job is expecting a proper job object. 

It's a bit difficult to help you without knowing what you are trying to do. Could you share more details about what you are trying to do, please?

**Comment by DarkLite1** [comment]
Stumbled upon this question to. Trying to figure out how to Mock a job object of type `System.Management.Automation.PSRemotingJob`. That way there's no error from `Wait-Job` in case it doesn't receive a job object.

**Comment by DarkLite1** [comment]
For anyone interested I found the answer on [StackOverflow](https://stackoverflow.com/questions/51360568/how-to-mock-a-job-in-pester).
