### ISSUE TITLE
Need to able Pester to run tests in other folder

### ISSUE THREAD

**Issue by gilkatz** [pester/Pester#580]
As in any language we want that the source will be in src folder and the tests in tests folder
Right now Pester assume that both files are in the same folder

**Comment by dlwyatt** [comment]
You can run tests in any folder you like.  The `New-Fixture` command does assume that you want to have the source ps1 file and a corresponding .Tests.ps1 file in the same folder, because that was the preference of the original author, but there's nothing else in Pester that forces you into that structure (and personally, I never use `New-Fixture` anyway.)  For example:  https://github.com/PowerShell/xWebAdministration
