### ISSUE TITLE
Upgrade from 3.4.0 to 3.4.1 onwards will break Get-Help about_Should

### ISSUE THREAD

**Issue by kilasuit** [pester/Pester#586]
It seems between 3.4.0 & 3.4.1 being released the about_should file was renamed to about_Should in the following commit ae0649a

This causes an issue when you run Get-Help About_should as it returns the multiple topics issue that we had before though I think this is more a core Get-Help issue than a Pester module issue but thought it best to raise it here as well

**Comment by juneb** [comment]
Thanks for raising the issue. This is a versioning issue and help isn't versioned. I'll do some digging and see if there's a recommended way to fix this, other than reverting to the incorrect caps.

**Comment by nohwnd** [comment]
I succeeded to replicate the issue, but I can't reliably replicate it. I opened PowerShell, loaded the module and then did `Get-Help About_should`. And it actually shown two versions of the file rather than the contents. Then I renamed the file back to lower case, tried it again, and the I renamed the file back to the current casing, and since then I can't replicate the issue anymore. I tried it in multiple sessions and even restarted my computer, but it still works.

Do you have more information about what causes the issue? At first I was under the impression that the casing is at fault, but I also got the file versions with files that are named the same in 3.3.5 (the windows 10 built-in version) and 3.4.1.

**Comment by juneb** [comment]
No, it's not only the casing, although casing triggers this error. The problem is that Get-Help was not designed to deal with versions. I'm chatting with David Wilson in background. PowerShell Team has repro'd this and it's on their list for a fix.

**Comment by it-praktyk** [comment]
I assume that the issue can be closed soon (7 days). Please let me know if you want to leave the issue open.
