### ISSUE TITLE
how to mock a .net class function  with pester?

### ISSUE THREAD

**Issue by maxcli** [pester/Pester#592]
I am testing a Powershell module which calls a .net class function like this : 
```powershell
$result=[namespace.class]::function($param1,$param2) 
```

How can I mock this function ? I read that I can wrap this in a Powershell function - can I get an example?
Thanks,Peter

**Comment by dlwyatt** [comment]
In the most simple form:

```posh
function Get-Thingy($param1, $param2)
{
    return [namespace.class]::function($param1, $param2)
}
```

Then instead of making calls to `[namespace.class]::function()` in your code, you'd make calls to `Get-Thingy`.  `Get-Thingy` can then be mocked for your Pester tests.

**Comment by maxcli** [comment]
hello DL,
I tried to follow your example,  ,  but for some reason the test does not run my mock function. Instead , it calls function Get-Thingy($param1, $param2)
{
    return [namespace.class]::function($param1, $param2) 
}
Any ideas why my mock function does not get called?

this is what my test looks like : 
Describe "something" {
	 

	$result =(.$SomeScript)   <--- get modules loaded in memory	
Context "Happy Path" {
		it "Call mocked method 1x" {
 
			Mock  Get-Thingy{ "" }
			$result =$result =(& $SomeScript)

**Comment by nohwnd** [comment]
@maxcli That does not work because the `&` operator runs the script in it's own scope, redifining the all the functions with their original. You need to call the functions in your tests directly.  

Pester can test functions but not whole scripts, because it has no way of hooking itself in, because:
Calling the `Mock` function looks up the function that you want to mock and replaces it with some logic. The logic then either runs the provided mockWith script block, or calls the original function. 
To be able to mock a function, `Mock` needs to be called after the function is defined (so it can replace it) and the test code then needs to see the mocked funcntion and must not define it again.

**Comment by maxcli** [comment]
I tried replacing the & operator with a dot operator when i call the script inside the 'it' section but i still don't execute the mock. I guess I don't understand how to override . Any Tips ?

**Comment by maxcli** [comment]
Hello, can you elaborate?
I first run my ps1 script with a dot source.
then i mock the method.
then i call the script again (either dot source or & operator)
why the mock method is not seen. Why can't i override the function with my mock ? how do i fix it ?
Thanks,Peter

**Comment by nohwnd** [comment]
> then i call the script again (either dot source or & operator) , but the script does not call the mock method.
This step is where it goes wrong. By calling the script again redefine the mocked functions (or run in a different scope, depending on how you invoked the script). And that's why the mocked functions are not called. 

You need to do it like this: 
```powershell
. .\script.ps1
Describe "mocking" {
    It "should work" {
        Mock MyFunction  {"I am mock."}
        MyFunction | Should Be "I am mock."
    }
}
```
or like this 
```powershell
#inside of script.ps1
function MyFunction () {

}

**Comment by maxcli** [comment]
i really want to call the ps1 again, not just a function. 
I've done this with PSM before . But seems like Pester does not handle ps1 the same way.

**Comment by dlwyatt** [comment]
Pester should be behaving the same way for both file types.  If you run them again, you redefine your functions, which wipes out the mock that you may have previously defined.

**Comment by maxcli** [comment]
Dave, 
with psm , i can do this :
    dot source run my.ps1, which import-module a.psm1
    mock a function in a.psm1
    & run my.ps1 <-- and the function is mocked.

but i can't mock a ps1 function directly. :-(

**Comment by dlwyatt** [comment]
Ah.  That's because Import-Module doesn't do anything if a module's already imported (unless you do use its `-Force` switch.)  If you were doing `Import-Module -Force`, you'd see the same behavior as with everything in a ps1 file.

**Comment by maxcli** [comment]
Dave , so there is nothing i can do to mock a function in ps1 then ?

**Comment by dlwyatt** [comment]
Not without making the sorts of changes we've described already.  If the function both defines the function _and_ runs a bunch of code that uses the function, then Pester has no opportunity to mock anything.  You need to separate those steps somehow, so you can define a function first, then mock it, then run the rest of the code _without_ redefining the function.

**Comment by nohwnd** [comment]
To achieve the same thing with ps1 you need to be able to run the code in three different ways:
1. Including functions only (when you dot source the script)
2. Running only the part od the script that does stuff (when you run in the test body)
3. Running everything (when you run the script normally -- in production)

You can achieve that by adding two switches    to your script parameters (or one "threeway switch"). I will post how that would look like in code when I get to my computer.


Jakub Jareš

PowerShell & Pester
t 00420603800578<tel:00420603800578>
e me@jakubjares.com<mailto:me@jakubjares.com>
t @nohwnd

18. 8. 2016 v 19:21, Dave Wyatt <notifications@github.com<mailto:notifications@github.com>>:


Ah. That's because Import-Module doesn't do anything if a module's already imported (unless you do use its -Force switch.) If you were doing Import-Module -Force, you'd see the same behavior as with everything in a ps1 file.

**Comment by maxcli** [comment]
Thanks Guys! 
I moved the function into a PSM1 and now i can mock the function ok  !

**Comment by maxcli** [comment]
I appreciate the a great support :-)
