### ISSUE TITLE
Why pester runs a source script before executing test?

### ISSUE THREAD

**Issue by IvanovOleg** [pester/Pester#658]
Hi,
Source.ps1
```
function Clean {

}

$test = 5
$test
```
Source.Tests.ps1
```
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'
. "$here\$sut"

Describe "Clean" {
    It "does something useful" {
        $result = Clean
        $result | Should Be $false
    }
}
```
Output:

> 5
> Describing Clean
>  [-] does something useful 31ms
>    Expected: {False}
>    But was:  {}
>    8:         $result | Should Be $false
>    в Should<End>, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Functions\Assertions\Should.ps1: строка 92
>    в <ScriptBlock>, C:\Users\dlj\Documents\powershell_tutorial\tests\Source.Tests.ps1: строка 8
>    в Invoke-Test, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Functions\It.ps1: строка 253
>    в ItImpl, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Functions\It.ps1: строка 203
>    в It, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Functions\It.ps1: строка 117
>    в <ScriptBlock>, C:\Users\dlj\Documents\powershell_tutorial\tests\Source.Tests.ps1: строка 6
>    в Describe, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Functions\Describe.ps1: строка 100
>    в <ScriptBlock>, C:\Users\dlj\Documents\powershell_tutorial\tests\Source.Tests.ps1: строка 5
>    в <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Pester.psm1: строка 297
>    в Invoke-Pester, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Pester.psm1: строка 310
>    в <ScriptBlock>, <Нет файла>: строка 1
> Tests completed in 31ms
> Passed: 0 Failed: 1 Skipped: 0 Pending: 0 Inconclusive: 0

Why does pester show "5"? I don't want to execute $test = 5 and $test, I just want to test the clean function  and thats all. If I disable . "$here\$sut" than it can't find a function. Is it possible to test such script partially?

**Comment by nohwnd** [comment]
Because that is how dot sourcing works. By saying . "$here\$sut" you instruct powershell to run the script. It runs almost the same way as if you just invoked it normally (for example by the & operator). The difference is that instead of creating new scope, it runs in the current scope. We use this feature to import the functions and variables from the *tested* script to the *test* script, but it also runs all the other statements in the script, which in your case outputs the number 5.

There is no built in way run just the functions of a script (at least no that I know of), so you either have to put the main executablece in if ($underTest) and provide the parameter when testing or, do a varition on the same thing using different condition, such as checking if the code is being dot-sourced.


Jakub Jareš

.NET, Pester, PowerShell
t 00420603800578<tel:00420603800578>
e me@jakubjares.com<mailto:me@jakubjares.com>
t @nohwnd

12. 12. 2016 v 20:43, Oleg Ivanov <notifications@github.com<mailto:notifications@github.com>>:


Hi,
Source.ps1

function Clean {

}

$test = 5
$test


Source.Tests.ps1

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'
. "$here\$sut"

Describe "Clean" {
    It "does something useful" {
        $result = Clean
        $result | Should Be $false
    }
}


Output:

5
Describing Clean
[-] does something useful 31ms
Expected: {False}
But was: {}
8: $result | Should Be $false
? Should, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Functions\Assertions\Should.ps1: ?????? 92
? , C:\Users\dlj\Documents\powershell_tutorial\tests\Source.Tests.ps1: ?????? 8
? Invoke-Test, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Functions\It.ps1: ?????? 253
? ItImpl, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Functions\It.ps1: ?????? 203
? It, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Functions\It.ps1: ?????? 117
? , C:\Users\dlj\Documents\powershell_tutorial\tests\Source.Tests.ps1: ?????? 6
? Describe, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Functions\Describe.ps1: ?????? 100
? , C:\Users\dlj\Documents\powershell_tutorial\tests\Source.Tests.ps1: ?????? 5
? , C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Pester.psm1: ?????? 297
? Invoke-Pester, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Pester.psm1: ?????? 310
? , <??? ?????>: ?????? 1
Tests completed in 31ms
Passed: 0 Failed: 1 Skipped: 0 Pending: 0 Inconclusive: 0

Why does pester show "5"? I don't want to execute $test = 5 and $test, I just want to test the clean function and thats all. If I disable . "$here$sut" than it can't find a function. Is it possible to test such script partialy?

**Comment by nohwnd** [comment]
My web is down, but here is a copy of an aricle that I wrote on the topic a while ago.

**Comment by IvanovOleg** [comment]
@nohwnd , thank you!
