### ISSUE TITLE
Update README.MD to v4

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#687]
- Update the general information about the new version,
- Add information about what changed 
- Add information about Gherkin

https://github.com/pester/Pester/issues/683 Can be used as source of information.

**Comment by it-praktyk** [comment]
Now, when the master branch contains Pester v.4.0.3-rc, that issue is more important than previously. Do you agree?

**Comment by nohwnd** [comment]
The current readme feels very overwhelming. I suggest to simplify it _a lot_, to follow structure a many other readmes use, and that I consider to be very approachable: 

- very short explanation of what the project is
- simple code example
- installation
- short description of the main features 
- maybe faq, but probably rather link to next steps

All of the info on the readme page should be aimed at the simplest cases, and showcase the simplest way of using/installing/integrating Pester. Links should be then provided to pages that describe each section in more detail. 

I started authoring such [readme here](https://github.com/nohwnd/Pester/blob/master/README.md) and I would love to get some feedback on the idea. 

The two-phrase explanation of the project definitely needs some improvement, I am looking for something that re-assures the reader that Pester is used by many, to do many cool things, ranging from "trivial" to very advanced.

I don't want to throw the current info away, rather tuck it to keep it available, without trying to say way too much on the readme page. 

I also propose to change the "build" examples to something much more generic, such as listing planet names (maybe the examples in my code could do even without the population filter). I remember the "build" examples giving me the wrong idea about what pester is, and also remember getting what is happening in them much much later.

@dlwyatt ok with you, before I put way too much time into this? :)

**Comment by alx9r** [comment]
@nohwnd 

I think that the word "mock" ought to be front-and-center in the description of Pester.  "Test framework" alone leaves experienced readers with the question "what about mocking?"  I don't think Pester's mocking capability is self-evident as it seems that some (most?) "test frameworks" don't mock at all.  Both [Catch](https://github.com/philsquared/Catch) and [googletest](https://github.com/google/googletest) are self-described "testing frameworks."  Neither implement mocking.  Rather, those "testing frameworks" are meant to be used with a "mocking framework" like googlemock.  (This might not be obvious as googletest and googlemock are now distributed together.)

I also think Pester's ubiquity is worth stating.  It is the de-facto standard framework for PowerShell testing.  I think that's likely an important consideration for experienced readers new-ish to PowerShell or automated testing.  I don't think "ubiquitous" is an embellishment given that it ships with Windows 10.

I'm no wordsmith, but it seems like something like 

> Pester is a ubiquitous test and mock framework for PowerShell.

would be an accurate summary of the salient aspects of Pester.

**Comment by dlwyatt** [comment]
@nohwnd Sure, sounds good to me!  :)

**Comment by nohwnd** [comment]
@alx9r used anotated tag for [the current release](https://github.com/pester/Pester/releases/tag/4.0.6-rc) and copied notes from changelog there. I need to put just the version on the first line but apart from that it looks like it should work just fine. and writing script that will take everything between the first `##` and second `##` from changelog is trivial, especially if we can write tests for it. :))

**Comment by alx9r** [comment]
@nohwnd That's a huge improvement. :) 

This might be a philosophical or semantic difference, but I don't consider release notes to simply be a changelog from the last version.  Changelogs and release notes are certainly related, but I consider them to have different focuses.  Here are the (rough) guidelines I am currently using for my projects:

* Changelog: Audience is mainly developers of the project itself.  Uses jargon possibly understood only by the maintainers of the project.  Contains a terse account of all the significant code changes from release to release.  Usually part of the code repository because it does not need to change after release.
* Release Notes: Audience is mainly users of the software.  Avoids unnecessary use of jargon.  Uses no jargon specific to the project unless it is part of the public interface.  Contains an account of new things user's can experience using the public interface (eg. a "What's New" section).  Contains a list of significant known issues a person considering using the release should consider, if any (eg. a "Known Issues" section).  Does not mention things that might have changed internally but cannot be readily observed by a user.  Not part of source control because it is likely to be updated after release (eg. when a significant issue becomes known).

Because of the distinct audiences and focus, I have found it very awkward to write one set of text for both.

I'm interested in what your philosophy about this is.

**Comment by nohwnd** [comment]
@alx9r I have no philosophy about it, what you say sounds very reasonable, now we just need to find someone to write it for every release :)

**Comment by nohwnd** [comment]
Added simpler readme #837, some of the links are still missing content, and the install guide is not done yet, and we should link to the latest release from the top when it is done. But I am pretty happy about how it looks :)

**Comment by alx9r** [comment]
@nohwnd The new text is [what I see here](https://github.com/nohwnd/Pester/tree/ac253365d3bca4033a715a372fcbcfcb74e6d978), right?  That's a big improvement.  👍 

I'm amused that that's the first time I've seen a `-TestCases` example that is compelling. :)

**Comment by nohwnd** [comment]
@alx9r yes, that, there might be minor changes in the readme branch.

**Comment by it-praktyk** [comment]
I just added content to the page [Articles and other resources](https://github.com/pester/Pester/wiki/Articles-and-other-resources) - it was initially part of my blog.

**Comment by nohwnd** [comment]
@it-praktyk awesome!

**Comment by it-praktyk** [comment]
@nohwnd, please [retweet](https://twitter.com/ITpraktyk/status/902978966780346368) - let's make this page live.

**Comment by it-praktyk** [comment]
README updated by #837.

@nohwnd, what is a source for a graphic what illustrates a code coverage?

I assume that it from TFS/VSTS. IMHO, it should be mentioned that a graphic was generated using an external tool and a native for Pester output for a code coverage should be added to examples too.

**Comment by nohwnd** [comment]
It is VSTS. I would add that to the wiki article so we don't complicate the readme.

**Comment by nohwnd** [comment]
#872 Moving the task for the CC here. Rest is done, or has it own issue.
