### ISSUE TITLE
Add -Properties and -Methods to New-MockObject

### ISSUE THREAD

**Issue by adbertram** [pester/Pester#694]
It'd be nice to add "mock" properties and methods to the object produced by New-MockObject as a way to define properties that are referenced in the code being tested.  I do this now.

$obj = New-MockObject -Type 'type'
$obj | Add-Member -Type NoteProperty -Name 'existingproperty' -Value 'foo' -Force
$obj | Add-Member -Type ScriptMethod -Name 'existingmethod' -Value { whatever }  -Force

**Comment by nohwnd** [comment]
I like this idea, but we need to make sure to define when is this useful and the caveats of this approach. Since you are just shadowing the members it will only work in PowerShell, and only for members that are shadowed. The underlying object will still refer to the original members no matter what you do. 

In the end this basically only works for the scenario where you have a mocked Get-* on one side, mocked Set-* on the other and you are writing the Update-* function, trying to comply with the interfaces of the Set-* and Get-*.

**Comment by adbertram** [comment]
This works in situations like this where you're referencing a property of the object that's mocked with New-MockObject. This approach would allow the script to execute as usual by controlling what the property is.

This also applies to methods as well.

```
function foo {
    param()
    ## $obj is a type of Whatever.Bar
    $obj = Get-Thing
    if ($obj.Property1 -eq 'something') {
          ## do stuff
    }
}
```

**Comment by alx9r** [comment]
FWIW FWICT generalized mocking of objects is currently frustrated by a number of issues with PowerShell classes.  I'm thinking in particular of  PowerShell/PowerShell#4713 and PowerShell/PowerShell#2505.  AFAICT the PowerShell team is currently working to resolve those issues.  I suspect that once those are fixed commands for creating fully-featured mock objects can be implemented in a general and robust manner.  I _think_ there currently isn't any barrier to mocking non-PowerShell classes from PowerShell, but it would seem inefficient to invest in an implementation just to find out it needs to change significant to accommodate PowerShell classes too.

**Comment by nohwnd** [comment]
This needs a better proposal, working out the details and understanding the practicality and limitations. If you are interested in pursuing this further please comment below and we can re-open this.

**Comment by efie45** [comment]
I'd love this functionality as well. Here is an example use case - maybe someone can tell me a better way to be doing this. 

I am creating a script that uses VMware.PowerCLI. 

I have a function that makes calls out to Start-VM. I cannot simply use ```Mock Start-VM {...``` because Start-VM will fail before it even gets to the mock since I cannot pass in the correct custom types that it accepts. 

New-MockObject in its current state can't accomplish this because the original objects have read-only properties.

**Comment by fflaten** [comment]
> New-MockObject in its current state can't accomplish this because the original objects have read-only properties. 

@efie45 I guess the PR #1838 currently in review might suit you then 🙂
