### ISSUE TITLE
Should Be $true Fails When Piped Multiple Values

### ISSUE THREAD

**Issue by splatteredbits** [pester/Pester#696]
This passes in 3.4.6 but fails in 4.0.2:

    Describe 'Should Be when piped multipe values' {
         It 'should pass' {
             {
                @( $true, $true, $true ) | Should Be $true
             } | Should Not Throw
         }
    }

**Comment by dlwyatt** [comment]
That's intentional. "Should Be" now compares arrays instead of one element at a time.

**Comment by nohwnd** [comment]
As Dave said this is intentional, but I forgot to put it in the announcement (will update it in a minute). This is possibly the first step towards assertions that are more robust, easier to understand and more feature rich. At the moment I am writing all the assertions (and a ton of new ones :) ) just to get a fresh look at it. Simplifying the way pipeline input is consumed, and limiting unexpected behaviour is one of the goals of that side projects. Plus how else we could have new assertion syntax every release?:D
