### ISSUE TITLE
Code Coverage for PowerShell Classes

### ISSUE THREAD

**Issue by DWSR** [pester/Pester#731]
I would love to have support for generating code coverage stats for Classes in a similar manner to how they can be generated for functions (i.e. by specifying the function name, rather than the script line numbers).

**Comment by nohwnd** [comment]
@Thilas Any insight on this? Just trying since you've done great work on the jacoco output.

**Comment by Thilas** [comment]
@DWSR, I guess your are talking about [PowerShell classes](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_classes), right?

@nohwnd, if so, from what I saw, it would be fairly easy to add the class name of a given command. Then we just have to determine how to render those in the JaCoCo output since we are already using the "class" level of JaCoCo format to represent a PowerShell file (e.g. a .ps1 file). But I guess we could just add 1 "class" element per actual PS class. Then it would be easy to do.

**Comment by nohwnd** [comment]
@Thilas  I think covering class methods, static methods and constructors should be good for now if that can be achieved. The properties don't allow custom getters and setters so there is nothing to test on them. Could you have a look on it please? I think the changes with the files being put on the class level come in your recent changes, and those haven't been released so changes to acoomodate powershell classes can be made without breaking anyones code.

**Comment by Thilas** [comment]
@nohwnd, I wasn't clear about this but classes' coverage is already supported. To my understanding, it's just that Pester does not provide the related class name of hit/missed commands with the coverage info in order to compute coverage per class.

So the only thing to do here would be to add this optional "Class" information similarly to the "Function" property already provided. And to add those classes in the JaCoCo output.

**Comment by nohwnd** [comment]
@Thilas okay, sounds like a plan. Would you be interested in doing that, or should I mark this as help wanted?

**Comment by Thilas** [comment]
I'd suggest to mark it as help wanted for now. I'll see if I find time to
work on it.

Le mar. 18 déc. 2018 à 08:21, Jakub Jareš <notifications@github.com> a
écrit :

**Comment by Thilas** [comment]
@nohwnd, I finally found some time to work on this. Could you please review #1187?

**Comment by nohwnd** [comment]
Merged the PR. Thanks!
