### ISSUE TITLE
[RFC] What is it maintenance/development/branching model for Pester ?

### ISSUE THREAD

**Issue by it-praktyk** [pester/Pester#754]
Guys,
could you explain me what is it (?) your idea behind branching code in the Pester project now?

I see that
- master - has some features previously included in v. 4 (like Gherkin and the new color schema)
- DevelopmentV4 - I supposed that all new major changes will be pushed there
- V3Maintenance - (?)

I'm asking because due to my confusion I lost (?) some time preparing update to the master branch - when that was updated previously and merged to the V3Maintenance branch.

Some other prepared by me pull requests were addresses to update help and add/improve features in branches 3.4.* or 4.0.* but I don't know how I should resolved conflicts.

Thank you in advance for clarification.

**Comment by dlwyatt** [comment]
Basically the old master became v3maintenance (which may not be needed; just created it in case we want to do something < 4.0 at some point), and DevelopmentV4 moved to master.

I changed all the existing PRs to point at the proper branch, I think.

**Comment by it-praktyk** [comment]
@dlwyatt, thank you for your answer.

My remarks/wishes
- At least README.md has to be updated on the current master branch
- Rules of that kind of branching for future need to be established - like how it should be communicated etc.

If I missed public discussion about that please let me know and and accept my apologies.

**Comment by dlwyatt** [comment]
No public discussion, just something I did this weekend since for some reason, PRs to the v4 branch were triggering hundreds of builds on the TeamCity server.

**Comment by nohwnd** [comment]
@it-praktyk you don't have to resolve anything, I will fix the conflicts when merging and merge the changes from v3 to master if needed. But we will likely add new features only to v4, and only issue hotfixes to v3 if needed.

**Comment by Jaykul** [comment]
But 4 is still considered pre-release, right?

**Comment by nohwnd** [comment]
Yup.


Jakub Jareš

.NET, Pester, PowerShell
t 00420603800578<tel:00420603800578>
e me@jakubjares.com<mailto:me@jakubjares.com>
t @nohwnd

23. 3. 2017 v 0:23, Joel Bennett <notifications@github.com<mailto:notifications@github.com>>:


But 4 is still considered pre-release, right?

**Comment by trondhindenes** [comment]
As long as the PowerShell gallery stuff doesn't support `prerelease` tags, would it be an idea to _not_ publish prerelease versions to the gallery?

**Comment by nohwnd** [comment]
@trondhindenes too late for that now. Let's hope they will support it when we start working on 5.0
@it-praktyk Re-open if you think it should be open. :)

**Comment by it-praktyk** [comment]
I think that further development/releasing model should be discussed. The release of the 4th version of Pester can be a good moment.

**Comment by it-praktyk** [comment]
I would like to return to a discussion about release model for Pester.

Why now? Today I've opened the issue #970 what could be relatively simple to resolve if we stick to the git branching model described here as [Gitflow Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow).

I think that we should now and in the future

1. rename the current master branch to develop
2. develop branch should be the default branch but we should update README for it and explain purpose
2. make the new master branch based on the state from the last release (4.1.1)
3. resolve the issue #970 in both branches and publish releases 4.1.2 and 4.2.0-alpha4
4. all unstable releases should be released based on the develop branch
5. stable releases should be based on the master branch
6. code between the develop and the master branches can be rebased (?)

**Comment by nohwnd** [comment]
@it-praktyk I don't think gitflow is the way to go, it solves one problem but adds many other problems, and a lot of ceremony. if you want to be able to issue a hotfix/release without releasing all the other features/changes that were added since the last stable release then the build server can be configured to release also from tags on branches called hotfix-*, you can span that branch from any commit (ideally a tag, because we release from tags) and you are done. That is how gitflow does it as well, but we don't have too keep up a master branch and rename stuff.

**Comment by it-praktyk** [comment]
I've updated the tags in [the new branch in my fork](https://github.com/it-praktyk/Pester/tree/Pester_4.1.2).

I'm not sure if should I push this branch directly to Pester repository too.

**Comment by Jaykul** [comment]
Just because alternatives are fun: at work we use [OneFlow](http://endoflineblog.com/oneflow-a-git-branching-model-and-workflow) which dispenses with the (unnecessary?) second long-term branch, while still proscribing a little bit of "ceremony" as @nohwnd puts it.

We like that it proscribes a little organization of branches (i.e. someone unfamiliar with the project can immediately distinguish a feature branch from a release branch) -- and that at the end of the day, they all get merged back to master. 

As a side note, it's grown on me that there are no scripts and tools around it. It means that our flow is purely about branches and naming conventions -- we don't care _how_ you made the branch, just that it exists.

**Comment by nohwnd** [comment]
There is no branching model and there is none needed at the moment. Most patches come from PRs and should be provided as PRs from topic branches. The process of contributing is described in the contributing page and we don't support two versions at the same time so single master is okay. If the need arises I know who to get in touch with. :)

**Comment by nohwnd** [comment]
@Jaykul Oneflow looks good, I reviewed it but I don't commit to any branching model at the moment :)
