### ISSUE TITLE
Can't mock function used in two different scopes

### ISSUE THREAD

**Issue by splatteredbits** [pester/Pester#761]
I have a script that uses a module. The script calls one of the module's functions that I'm trying to mock. The script then calls another function that calls the function I want to mock. It seems with Pester I can only mock one of these calls: either the one in the scope of the script or the one in the scope of the module.

My script:
```
Import-Module 'Module'

$result = Test-SomeValue
if( $result )
{
     Write-Host 'Mock called from script!'
}

$context = New-ModuleContext
```

The module:
```
function Test-SomeValue
{
    return $false
}

function New-ModuleContext
{
    if( Test-SomeValue )
    {
        Write-Host 'Mock called from module!'
    }
}
```

My test

```
Describe 'My Script' {
    Mock -CommandName 'Test-SomeValue' -MockWith { return $true } 
    Mock -CommandName 'Test-SomeValue' -ModuleName 'Module' -MockWith { return $true }

    & $pathToScript
}
```

No matter what, I only see

```
Mock called from script!
```

I expected to see

```
Mock called from script!
Mock called from module!
```

**Comment by nohwnd** [comment]
I think your example is broken somehow. I've split it in files and I can only get it to print the mock from module message.  Or I am doing it wrong :)

You are not importing the module on the top of the test script, so how does the function get in scope?


Mocking in external scripts (& script.ps1) is not "supported", because most of the times it would not work anyway, because in most of the cases the function would be re-defined in the body of the script. 

This seems to be a special case where you work around the re-defining, by importing the module before calling the script, but then the mock is active in the current scope (where describe is executed) and in the Module scope  (inside of the Module module), but not in the script scope (in the newly created '& script.ps1' scope). 

Please check your example works (in a clean session) so I can have closer look on this :)

**Comment by it-praktyk** [comment]
@splatteredbits, do you still need help in this case? If not please close the issue. Thank you.

**Comment by nohwnd** [comment]
@splatteredbits Please re-open if this is still an issue for you.
