### ISSUE TITLE
Mocking Unexpected Error: PowerCLI cmdlet Disconnect-VIServer

### ISSUE THREAD

**Issue by Midacts** [pester/Pester#803]
**PowerCLI Version**: 6.5.1 (from the PSGallery)
**Error**: Cannot process argument transformation on parameter 'Server'. Cannot convert the "VCENTER" value of type "System.String" to type "VMware.VimAutomation.ViCore.Types.V1.VIServer[]".

For some reason when i have `Mock Disconnect-VIServer { } ` it still acts as if the cmdlet is not being mocked.
My guess is this is a PowerCLI thing?
Just looking for guidance. (I had to add in a try/catch to bypass the issue of failed mocks).

**Comment by nohwnd** [comment]
The Mock command copies the signature of the mocked cmdlet, so the parameters as well as the parameter types remain the same. The original cmdlet expects you to provide a list of `VIServer`s and so the mock does the same. There was a lot of discussion whether or not we should make this less strict, but the work has not been done yet. 

Usually you *do* want to be strict with you mock signatures, becuase otherwise your mock code is becoming more and more different from the real code.

**Comment by Midacts** [comment]
That makes sense.
It isn't a pester issue than, it is my lack of knowledge on how to mock PowerCLI cmdlets.

(do you have any suggestions?)
I asking in the powershell slack today. it seemed super difficult/unrealistically achievable to mock PowerCLI cmdlets.

**Comment by nohwnd** [comment]
You are right, PowerCLI is hard to test. See [this thread](https://github.com/pester/Pester/issues/682) for a way of generating a stub methods that resemble PowerCLI but have relaxed method signatures. I would also recommend going through code of [Vester](https://github.com/WahlNetwork/Vester) becuase I rememeber having a call about similar issue with @brianbunke who workeds on that project and so they might have some answers there for you :)

**Comment by Midacts** [comment]
Thanks for the link to the thread. I looked throgh Brian's sharepoint blog about stubs...they seem complicated and like alot of overhead just to mock a function. (Maybe it is just my naivity)

I did run across brian's [gist](https://gist.github.com/brianbunke/b31765f69781112f4b2ddfa9f949599e) about mocking VMs.
(This is a similar approach that Chrisdent took me through. He has his own function to create stubs - [indented-automation](https://github.com/indented-automation/Indented.StubCommand/blob/master/examples/VMWare/VMware.VimAutomation.Core.psm1))

I took the lazy man/easy approach and just declared the VMware function with the info i needed in it.

**Comment by brianbunke** [comment]
Happy to help, but only because my love for @nohwnd is neverending.

Throwing Pester at PowerCLI is difficult, but not impossible. It just depends on what you're trying to do.

There are three tiers here (that I know of):

1. Mock a normal PowerCLI command
2. Mock a normal PowerCLI command that stubbornly asks for a mandatory parameter
3. Mock a PowerCLI object to pass into a strongly-typed parameter

```posh
<#
Get-Module Pester,VMware.VimAutomation.Core | Select Name,Version

Name                      Version      
----                      -------      
Pester                    4.0.3        
VMware.VimAutomation.Core 6.5.1.5374329
#>
```
Scenario 1 works normally:
```posh
Describe 'Scenario 1: Basic mocking' {
    Mock Disconnect-VIServer {'bye'}

    It 'Overrides a PowerCLI cmdlet' {
        Disconnect-VIServer | Should Be 'bye'
    }
}
```
Scenario 2 is a little weird, just because of the closed-source, primarily C# nature of the PowerCLI modules. I haven't dug into Pester to figure out exactly why the mandatory parameter persists while overriding, but it's still manageable.
```posh
Describe 'Scenario 2: Mandatory parameters' {
    Mock Connect-VIServer {
        param ($Server)
        Write-Output $Server
    }

    It 'Overrides cmdlets with mandatory parameters' {
        Connect-VIServer -Server 'hi' | Should Be 'hi'
    }
}
```

Scenario 3 comes into play when you write your own functions, and want to ensure that only proper PowerCLI objects are passed into certain parameters. (See my [Get-VMotion](https://github.com/brianbunke/vCmdlets/blob/cef402de4dcdecb0fa74f0e39cf90f12691248cc/Get-VMotion.ps1) for an example.)

It's where I really got stuck, and ended up having @nohwnd walk me through things. It involves using a decompiler like DotPeek, and an amount of trial and error directly inverse from your amount of familiarity with C#. That's where my [VM gist](https://gist.github.com/brianbunke/b31765f69781112f4b2ddfa9f949599e) came from.

Ideally, I'd like to see PowerCLI open-sourced so we can easily solve this once and for all. Failing that, community effort to create a PowerShell module that provides PowerCLI mock objects (and abstracts away that mess in the Gist) would be amazing.

Let me know if you still have questions!

**Comment by it-praktyk** [comment]
@Midacts, is it your question answered?

**Comment by Midacts** [comment]
Yes. I must not have closed the issue

On Aug 17, 2017 5:19 PM, "Wojciech Sciesinski" <notifications@github.com>
wrote:

@Midacts <https://github.com/midacts>, is it your question answered?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/pester/Pester/issues/803#issuecomment-323197452>, or mute
the thread
