### ISSUE TITLE
Possibility for validating the It block's -skip param when splatting?

### ISSUE THREAD

**Issue by LawrenceHwang** [pester/Pester#813]
Hello,
Consider following example:
> Describe 'Different parameters' {
>   BeforeAll {
>     $itParams = @{Skip = $treu}
>   }
>   It @itParams "This should be skipped by using the itParams" {
>     1 | should be 1
>   }
> }

When splatting the -skip param with hash table. In the example, the @{Skip = $treu} has a typo: 
- the switch parameter -skip to have $false value and, 
- not skipping the test.

It appears to me test writers should pass proper value ($true, $false, 0, or 1)  to the -skip switch parameter. But, is it possible for Pester to validate splatted param in this case? If possible, then Pester can provide another layer of comfort for its users. 

The Pester module version used in the test is 4.0.5.

Cheers,

Lawrence

**Comment by nohwnd** [comment]
Hello,
splatting a param to switch follows the standard rules of casting to boolean. Anything that is falsy will become false and anything else will become true. In your case if $treu is $null it will become false, because $null is falsy.

If we wanted to validate the value passed to the Skip parameter (to see that it is a real false, and not a value cast to false) we would have to change the parameter type from [switch] to [object]. That would change the api, because everyone would have to provide the value explicitly -Skip $true, instead of using just -Skip.

To me this is not so severe to be worth changing the publoc api. If you need to dynamically skip tests then you should write tests for that dynamic part, and tests should highlight such issues.

**Comment by LawrenceHwang** [comment]
Thanks a lot for explaining the logic behind. It now seems to me that changing the validation model indeed doesn't provide much value in this case.
