### ISSUE TITLE
Functions from Environment.ps1 are not exported

### ISSUE THREAD

**Issue by it-praktyk** [pester/Pester#830]
I just found that functions
- GetPesterPsVersion
- GetPesterOs
- Get-TempDirectory
from the Functions\Environment.ps1 file are not exported by Pester module
- [in the manifest file](https://github.com/pester/Pester/blob/23eaf10c354eb4fbebc9d44f960bec89b24b5976/Pester.psd1#L28-L53)
- [in the block of exported module members](https://github.com/pester/Pester/blob/23eaf10c354eb4fbebc9d44f960bec89b24b5976/Pester.psm1#L1084-L1090)

Additionally, they are not advanced functions (lack of `[cmdletbindings()]`) so they need to be added to the list used by the [all non-deprecated, non-internal public commands use CmdletBinding' test](https://github.com/pester/Pester/blob/23eaf10c354eb4fbebc9d44f960bec89b24b5976/Pester.Tests.ps1#L129-L133).

I think that this need to be corrected before releasing Pester v4.0 because if it will not be correct we will deliver "orphaned" functions.

**Comment by nohwnd** [comment]
Why should they be exported?


Jakub Jareš

.NET, Pester, PowerShell
t 00420603800578<tel:00420603800578>
e me@jakubjares.com<mailto:me@jakubjares.com>
t @nohwnd

21. 8. 2017 v 20:55, Wojciech Sciesinski <notifications@github.com<mailto:notifications@github.com>>:


I just found that functions

  *   GetPesterPsVersion
  *   GetPesterOs
  *   Get-TempDirectory
from the Functions\Environment.ps1 file are not exported by Pester module
  *   in the manifest file<https://github.com/pester/Pester/blob/23eaf10c354eb4fbebc9d44f960bec89b24b5976/Pester.psd1#L28-L53>
  *   in the block of exported module members<https://github.com/pester/Pester/blob/23eaf10c354eb4fbebc9d44f960bec89b24b5976/Pester.psm1#L1084-L1090>

Additionally, they are not advanced functions (lack of [cmdletbindings()]) so they need to be added to the list used by the all non-deprecated, non-internal public commands use CmdletBinding' test<https://github.com/pester/Pester/blob/23eaf10c354eb4fbebc9d44f960bec89b24b5976/Pester.Tests.ps1#L129-L133>.

I think that this need to be corrected before releasing Pester v4.0 because if it will not be correct we will deliver "orphaned" functions.

**Comment by it-praktyk** [comment]
Because without that they can't be used to check what an environment is.

Generally, in my first iteration, I tried using $IsLinux directly but it wasn't a good idea so I switched back to existing functions. I couldn't use them without exporting.

**Comment by it-praktyk** [comment]
Is it any other option to use those functions inside Pester tests except exporting?

**Comment by dlwyatt** [comment]
There are many internal functions.  I don't think the benefit of exporting these is worth increasing our API / support surface.

**Comment by nohwnd** [comment]
Agree with Dave. Imho we should not publish those functions as they are. If we need to provide information about os, we should think about the use cases and about the best way to publish the information.

**Comment by it-praktyk** [comment]
It's not a bug, it's a feature.

**Comment by it-praktyk** [comment]
I tried use mentioned functions before the module Pester was imported - e.g. in the first line file Gherkin.Tests.ps1 to block executing Gherkin tests on non-Windows systems.

When I've added them to exported they well imported automatically by PowerShell itself.

In my last iteration, I've added code like below

```
#You need import functions from Environment.ps1 before the first usage because
#the whole Pester module content is imported later
$Script:FunctionsRoot = Split-Path -Path $MyInvocation.MyCommand.Path

$Script:ModuleName = Join-Path -Path $FunctionsRoot -ChildPath 'Environment.ps1'

. $(Resolve-Path -Path $ModuleName) | Out-Null

if ($PSVersionTable.PSVersion.Major -le 2 -or ((GetPesterOS) -ne 'Windows')){

    return

}
```

I'm not sure if is it correct/safe way. What do you think?

**Comment by nohwnd** [comment]
@it-praktyk 
1) do you need this to do something related to v4.0? It is still part of that milestone. Or you need it for the Linux compatibility work? (if so please move it to Linux milestone). 

2) I guess the approach you took is fine for now. Later I would like to encapsulate the functions into something like `Run-On -Linux -Windows -ScriptBlock {  ...test code to be run... } which allows us to eradicate untested if blocks from our tests (which is something I am telling people to do, and then they point out that they learned it from Pester :D )

3) best approach would probably be to move those functions we need for our tests to a separate module, and import that module on top of each tests file that needs it, but that's a big change (not necessarily in the code, but in the approach we take). So let's not do it that way for now :)

**Comment by it-praktyk** [comment]
1. I don't need for v4.0 - I just removed it from it.

2.-3. - I'm just curious about $SafeCommands in Pester code - I don't understand this but I didn't try to find answer myself yet. Any approach is/will be good for me - as long as will be work, technically correct and accepted by you.

4. I realized that better be perform check for $PSVersionTabale.PSEdition - as long as we don't support Gherkin on PSCore too.
