### ISSUE TITLE
Feature request: Parameterized Context blocks 

### ISSUE THREAD

**Issue by RemcoKapinga** [pester/Pester#832]
I would like to be able to repeat groups of tests (context blocks) against multiple items (systems, endpoints, etc..), so that my test results are grouped by item.

for example:

    Describe 'Parameterized Context Example' {

        $endpoints = @(
            @{ HostName = 'server-1' }
            @{ HostName = 'server-2' }
        )

        Context 'Network verification for <HostName>' -TestCases $endPoints {
            param($HostName)

            It 'can be reached' {
                Test-Connection $HostName | Should Be True
            }

            ....
        }
    }

- This would help with environment verification tests. 
- It would also help to change the execution sequence of tests (series of tests per system, instead of every test against every system).
- It would also help with grouping test results per system.

**Comment by Remco-74** [comment]
A nice addition to this feature is that you can save some state per context, like follows:

    Describe 'Parameterized Context Example' {

        $endpoints = @(
            @{ HostName = 'server-1' }
            @{ HostName = 'server-2' }
        )

        Context 'Network verification for <HostName>' -TestCases $endPoints {
            param($HostName)

            BeforeAll { $session = New-PsSession -ComputerName $HostName }
            AfterAll  { Remove-Session -Session $session -Force }

            It 'can be reached' {
                Test-Connection $HostName | Should Be True
            }

            It 'has remoting enabled' {
                $session | Should Not Be $null
            }

            It 'can list files remotely' {
            }

            # more test reusing the same session ...
        }
    }

**Comment by jakauppila** [comment]
+1 to this. It would be great to be able to pass TestCases to a context when writing more data-driven tests.

**Comment by michalporeba** [comment]
I have been thinking about something similar for quite some time, and this issue is very interesting to me. I wrap a lot of contexts in a loop, which works, but makes the test code look ugly. 

What I don't like in this proposed solution is the use of `-TestCases` parameter, the same as on `It`. Wouldn't this lead to confusion? `It` is the test. Context is not.

How about changing the name to be more in line with the `Context`? Perhaps `-ContextValues` or `-ForEach`, `-MultipleContexts`? 

Consider syntax like this:

```powershell
Describe 'Parameterized Context Example' {

    $endpoints = @(
        @{ HostName = 'server-1' }
        @{ HostName = 'server-2' }
    )

    Context '<HostName> network verification' -ForEach $endoints {
        param($HostName)

        It 'can be reached' {
            Test-Connection $HostName | Should Be True
        }
    }
}
```

or perhaps even further simplification, where a default parameter would be passed to the context implicitly. We could have something like this:

```powershell
Describe 'Parameterized Context Example' {

    $endpoints = @('server-1','server-2')

    Context '<Context> network verification' -ForEach $endpoints {
        It 'can be reached' {
            Test-Connection $Context | Should Be True
        }
    }
}
```

What do you think?

**Comment by michalporeba** [comment]
in #1108 using objects[] instead of a hashtable has been discussed. I think if that is implemented adding string[] should be trivial. I can see the problem with choosing the variable name, but I was thinking it could be something like `$psitem`. It would serve exactly the same purpose. 

I like the option without params in the script block.

**Comment by nohwnd** [comment]
> adding string[]
As I said I am not very keen on that. The implementation would be simple, but the rest is problematic, and does not seem extremely useful. So I would rather not do it.

**Comment by michalporeba** [comment]
That's what I wanted to clear, because this ticket suggested that you are still considering adding `ojbect[]`. It could potentially be very expensive, some objects have a lot of properties, even on the first level. So the latest for v5 is that there will be `-ForEach` that will take a hashtable? It's easy enough to create functions for a specific project that take an object and create a specific hashtable.

**Comment by jakauppila** [comment]
Any plans for this on the horizon? There are scenarios like @Remco-74 described in the initial where I'd like to be able to pass in a _set_ of hosts and then perform a series of checks against those hosts and report on the outcome of the tests.

**Comment by nohwnd** [comment]
@jakauppila yes, but far away, I need to publish v5 first. Finish 5.1 and then this could come back into  picture. Seeing that adding parametrized tests was not very difficult in v5, this should not be that difficult either, it's basically just adding foreach and making sure the data and expansion works. I just need to think about conflicts of names and how it will inherit.

**Comment by nohwnd** [comment]
Added #1679 to link all the pieces together, please comment.
