### ISSUE TITLE
Assert-MockCalled breaks when tests are run using FileSystemWatcher.

### ISSUE THREAD

**Issue by crmckenzie** [pester/Pester#845]
I've created a repo to demo the problem [here](https://github.com/crmckenzie/pester-tests).
**From the README**

The purpose of this repo is to demonstrate a problem I'm having with Pester in versions 4.0.5 and 4.0.6.

When setting up an auto-watch, calls to `Assert-MockCalled` fail with this error:

>RuntimeException: Module '__DynamicModule_4432ff5d-ed1a-4cea-aa96-ff13c6e0cd2d' is not a Script module.  Detected modules of the following types: ''
at Get-ScriptModule, C:\Program Files\WindowsPowerShell\Modules\Pester\4.0.6\Functions\InModuleScope.ps1: line 128
at Validate-Command, C:\Program Files\WindowsPowerShell\Modules\Pester\4.0.6\Functions\Mock.ps1: line 839
at <ScriptBlock>, C:\Users\{UserName}\src\Modules\pester-tests\tests\Invoke-DoStuff.Tests.ps1: line 24

To see the failure, do the following steps:

1. Clone the repo
2. Navigate to the repo root
3. Execute `./Test.ps1 -Watch`
4. Open and Save /Tests/Invoke-DoStuff.Tests.ps1

**Comment by it-praktyk** [comment]
Please provide output of the command 

```
$bugReport = &{
    $p = get-module pester 
    "Pester version     : " + $p.Version + " " + $p.Path 
    "PowerShell version : " + $PSVersionTable.PSVersion
    "OS version         : " + [System.Environment]::OSVersion.VersionString
}
$bugReport
```
Thank you.

**Comment by nohwnd** [comment]
@crmckenzie Looked at your repro and the problem is that the FileWatcher seems to be putting your callback into a dynamic module. Pester then [picks this up](https://github.com/pester/Pester/blob/0d4f1d3e76d40f541e64eb4f7b318b02754278d1/Pester.psm1#L786) and uses it in Mock, and mock can only do with script modules, hence the error. You can observe the behavior yourself simply by adding `Write-Host $ExecutionContext.SessionState.Module` into your OnTestFileChanged callback (in the Pester code you see `$PSCmdlet.SessionState` which is looking at the calling function session state - so exactly the same thing).

I tried saving your code as module but that did not help, so your best chance is looking at how @smurawski does it in [PowerShellGuard](https://github.com/smurawski/PowerShellGuard). Maybe he can offer som insight on this :)

As a side note, put `Start-Sleep -Milliseconds 300` into your `while (1) {}`, or some other reasonable time out that is non-zero, otherwise you are burnig one core just on spin waiting. 🔥
