### ISSUE TITLE
Are nested Describe and Context still experimental?

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#852]
The changelog for 4.0.0-rc1 includes "(experimental) Add nested Describe and Context".  That capability still seems to be present in 4.0.6-rc but there is no subsequent mention of nesting in the changelog.  Are nested Describe and Context still experimental?

**Comment by nohwnd** [comment]
I remember saying it is experimental because I needed to keep it in the release, but noone was really sure how it will behave with all the crazy things people will throw at it. Especially mocks. And we did not have any spec of our own to describe how it should behave. So far it looks to work just fine if you just use it to group tests, but I haven't tested with mocks and all the other stuff that happens in scopes. So That is what I would put in the release notes, that nested describes are meant mainly for grouping tests.

**Comment by alx9r** [comment]
I have updated #853 per @nohwnd's comment.
