### ISSUE TITLE
Splatting parameters in ParameterFilter of Assert-MockCalled

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#862]
I was wondering if it's possible to use a hashtable within the `ParameterFilter` of `Assert-MockCalled`? An example might clear things up:

```
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'
. "$here\$sut"

$DoStuffParams = @{
    Name = 1
    Type = 2
}

Function DoStuff {
    Param (
        $Name,
        $Type
    )
    Write-Host "Do stuff"
}

Describe "DoStuff" {
    Mock DoStuff 
        
    it 'Good' {
        DoStuff -Name 1 -Type 2
        DoStuff -Name 2
        Assert-MockCalled DoStuff -Exactly 1 -Scope it -ParameterFilter {$Name -eq 1 -and $Type -eq 2}
    }
    it 'Good' {
        DoStuff @DoStuffParams
        DoStuff -Name 2
        Assert-MockCalled DoStuff -Exactly 1 -Scope it -ParameterFilter {$Name -eq 1 -and $Type -eq 2}
    }
    it 'Bad' {
        DoStuff @DoStuffParams
        DoStuff -Name 2
        Assert-MockCalled DoStuff -Exactly 1 -Scope it -ParameterFilter {$DoStuffParams}
    }
}
```

It would really be great to be able to use `        Assert-MockCalled DoStuff -Exactly 1 -Scope it -ParameterFilter {@DoStuffParams}`, because the hashtable `$DoStuffParams` is filled in the production script with data/parameters. 

Thank you for your help.

**Comment by it-praktyk** [comment]
The related issue #796, #88.

@davebrannan, what about your results?

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.

**Comment by DarkLite1** [comment]
I would like to have it reopened as there isn't a valid workaround to use a `HashTable` within the `-ParameterFiler`.

**Comment by nohwnd** [comment]
This might be complimentary #1158 and #1162 where we could explicitly provide context to the scriptblock . This would possibly simplify testing among scopes, and would not require the user to understand in which scope the scriptblock is invoking, because then we would simply invoke it in the most logical scope, and not in the most practical scope (eg. `Assert-MockCalled -ModuleName A -ParameterFilter { $name -eq "Jakub"}` would execute the parameter filter in the module A scope and not in the test script scope (Caller scope). There is [Invoke-WithContext](https://github.com/nohwnd/Assert/blob/670a9b7fea958360286c6444b19319cf6b995fee/Compatibility/src/Compatibility.ps1#L5) in assert that I recently implemented that should be easy to leverage for this kind of thing. It's a more advanced work, and some discussion will be needed but it should be doable.

**Comment by nohwnd** [comment]
Most of the problems of moving parameters to the right scope should be solved by running the parameter filter in the test scope which is how it is done now. Since this was not requested by anyone else, and it seems to complicate the already complicated situation around mocking I am closing this as won't fix.
