### ISSUE TITLE
A dynamically created and imported module is not removed after a test execution

### ISSUE THREAD

**Issue by it-praktyk** [pester/Pester#867]
After performing tests on Pester code the module created under the test scenario [Functions\Mock.Tests.ps1\$args handling](https://github.com/pester/Pester/blob/f28880bb1eb54eccc6aeee79b57aa4e907064df4/Functions/Mock.Tests.ps1#L1537-L1581) is not removed from a memory.

The result is 

```
PS >Get-Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
<OUTPUT_PARTIALLY_OMMITED> 
Binary     0.0.0.0    dynamic_code_module_03ju4cip, Ve... Invoke-CmdletWithArgs
<OUTPUT_PARTIALLY_OMMITED> 
```

**Comment by it-praktyk** [comment]
```
PS >Get-Command Invoke-CmdletWithArgs | Select name

Name
----
Invoke-CmdletWithArgs

PS >Get-Command Invoke-CmdletWithArgs | Select ModuleName, Source,module | fl


ModuleName : dynamic_code_module_twainnpd, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
Source     : dynamic_code_module_twainnpd, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
Module     : dynamic_code_module_twainnpd, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null


PS >Get-Command Invoke-CmdletWithArgs | Select Module | Remove-Module
Remove-Module : No modules were removed. Verify that the specification of modules to remove is correct and those modules exist in the runspace.
At line:1 char:53
+ Get-Command Invoke-CmdletWithArgs | Select Module | Remove-Module
+                                                     ~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Remove-Module], InvalidOperationException
    + FullyQualifiedErrorId : Modules_NoModulesRemoved,Microsoft.PowerShell.Commands.RemoveModuleCommand
```

**Comment by it-praktyk** [comment]
@nohwnd, I don't have more ideas how it can be resolved.

**Comment by nohwnd** [comment]
@it-praktyk okay I will have a look on it.

**Comment by nohwnd** [comment]
@it-praktyk so two issues with this code. 

1) when you are querying for the command to get the module the command is mocked so you get the alias back instead of the cmdlet. You need to explicitly ask for the cmdlet type of a command otherwise you just get the alias (more generally: you get the command that would resolve to that name, in this case the alias).

2) in the code you are doing select module on the object but you should be expanding the module property to get the module object, so it should be select -expandproperty module.
