### ISSUE TITLE
Pester test behaving differently with breakpoints and without breakpoints

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#890]
For some specific reason `Pester` behaves differently when stopped before executing a test then if it does when it's not stopped at all. Some examples to show the problem:

**File.Tests.ps1**

```
#Requires -Modules Pester
#Requires -Modules ImportExcel

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'

$DefaultsFile = [PSCustomObject]@{
    Settings = @"
        MailTo
        Chuck.Norris@gmail.com
"@ | ConvertFrom-Csv
    Permissions = [PSCustomObject]@{
        ADObjectName = $null 
        Permission = $null
    }
}

Describe 'Defaults.xlsx' {
    In $TestDrive {        
        it 'Test import' {
            $DefaultsFile.Settings | Export-Excel -Path Defaults.xlsx -WorkSheetname Settings
            $DefaultsFile.Permissions | Export-Excel -Path Defaults.xlsx -WorkSheetname Permissions
            ."$here\$sut"

            Import-DefaultPermissionsHC | Should BeNullOrEmpty
        }  
    }
}
```

**File.ps1**

```
Begin {
    Function Import-DefaultPermissionsHC {
        Try {
            $Permissions = Import-Excel -Path $DefaultsFile -Sheet Permissions -DataOnly -NoHeader

            Test-DefaultPermissionsHC -Sheet $Permissions

            $Permissions | Select-Object -Skip 1 -Property @{N='ADObjectName'; E={$_.P1}}, @{N='Permission'; E={$_.P2}}
        }
        Catch {
            throw "Defaults file '$DefaultsFile' worksheet 'Permissions': $_"
        }
    }

    Function Test-DefaultPermissionsHC {
        Param (
            [Array]$Sheet
        )

        $Sheet = $Sheet | Select-Object -Skip 1 

        $Sheet | where {(-not $_.P1)} | ForEach-Object {
            throw "No AD ObjectName found for permission '$($_.P2)'"
        }
    }
}

Process {
    $DefaultsFile = Get-Item -LiteralPath Defaults.xlsx -EA Stop
    $DefaultPermissions = Import-DefaultPermissionsHC
}

```

When executing `Pester` by opening `File.Tests.ps1` and hitting `F5` or clicking `Play` in the PowerShell ISE the following error is thrown:
```
Describing Defaults.xlsx
  [-] Test import 62ms
    RuntimeException: Defaults file 'C:\...
ts.xlsx' worksheet 'Permissions': No AD ObjectName found for permission ''
    at Import-DefaultPermissionsHC, S:\Test.ps1: line 11
    at <ScriptBlock><Process>, S:\Test.ps1: line 30
    at <ScriptBlock>, S:\Test.ps1: line 23
```
Now when running the same test, please add a breakpoint in `File.Tests.ps1` at `line 20` where it says `it 'Test import'` and hit `F5`. The debugger will stop at `line 20`, when you then continue with `F5` the script continues and throws no error. All tests are marked as green while this was the previous case not so.

I can understand if mu code is incorrect that I should fix it. But I don't understand why the results in `Pester` differ with or without using the debugger. 

In any case, thank you for your help.

**Comment by DarkLite1** [comment]
I'm not able to `Edit` my post for proper formatting. Sorry for that.. Might be a bug on `GitHub`.

**Comment by it-praktyk** [comment]
I've corrected formatting.

**Comment by nohwnd** [comment]
Could you check if the rest of the test is actually executed (for example write the current date to a file after the breakpoint), please? If that is not done then Code coverage is likely to blame, because that uses breakpoints, si maybe it skips the rest of the test for some resson, but I doubt it is as simple as that.

**Comment by DarkLite1** [comment]
In real life, because the example here is highly simplified. the other tests are correctly executed. The ones before it and the ones after it. I hope that answers your question. I simplified it so much, so that everyone is able to reproduce it.

**Comment by alx9r** [comment]
Replacing `Test-DefaultPermissionsHC` with 

```PowerShell
    Function Test-DefaultPermissionsHC {
        Param (
            [Array]$Sheet
        )
        $Sheet = $Sheet | Select-Object -Skip 1 
        Write-Host (Get-Variable Sheet)
        $Sheet | where {Write-Host 'where'; (-not $_.P1)} | ForEach-Object {
            throw "No AD ObjectName found for permission '$($_.P2)'"
        }
    }
```

reveals that `$Sheet` varies depending on whether a breakpoint is set or not.  It differs enough that when a breakpoint is set `where` is never invoked while it is invoked otherwise.  I'm not sure whether this is caused by Pester or PowerShell or both.  

What I do know is that, in general, debugging in PowerShell clobbers variables.  Invoking, for example,

```PowerShell
function f
{
    param($x)
    $PSBoundParameters
}

f -x 1
```

will output
```
Key Value
--- -----
x       1
```

however, if you set a breakpoint on `$PSBoundParameters` that variable will be defined but empty.  That has nothing to do with Pester.

FWIW, I generally distrust what I see in the debugger and defer to the results of automated tests run without breakpoints.

You might also consider that there are differences between running tests using `F5` versus `Invoke-Pester` versus `powershell.exe Invoke-Pester`.  You can get a taste of some of those differences [in this test](https://github.com/alx9r/ToolFoundations/blob/a7ad54074594a9cdf519fc253e8193675b170f4e/EnvironmentTests/pester4InModuleScopeTests.ps1) (look for all the special-cases for `$h.DirectlyInvokedScript`) and the places linked to from [this stackoverflow answer](https://stackoverflow.com/a/42878789/1404637).

The only tests I trust are those run without breakpoints in a fresh PowerShell process (eg. by running `powershell.exe Invoke-Pester`).  I have found every other method of invocation to be susceptible to inadvertent interference by things in memory that should be unrelated, but aren't.

**Comment by DarkLite1** [comment]
Thank you for the thorough investigation @alx9r . really appreciate your help. It shows indeed that, as you say, there is a difference when a breakpoint is set and when not. Maybe some of the `Pester` devs can have a look too. to see if they can see it being a problem within `Pester` or not.

For now, I fixed the code as following:
```
Function Test-DefaultPermissionsHC {
    Param (
        [Array]$Sheet
    )

    if ($Sheet = $Sheet | Select-Object -Skip 1 ) {
        $Sheet | where {(-not $_.P1)} | ForEach-Object {
            throw "No AD ObjectName found for permission '$($_.P2)'"
        }
    }
}
```

Thanks again for your help as this was really driving me nuts.

**Comment by nohwnd** [comment]
> Maybe some of the Pester devs can have a look too. to see if they can see it being a problem within Pester or not.

Alx9r is a Pester dev, and knows the most about Pester edge cases than anyone else. 🙂

**Comment by DarkLite1** [comment]
:embarrassed_humble_face:

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.

**Comment by alx9r** [comment]
There's a repro that seems similar in PowerShell/PowerShell#5607 that doesn't involve Pester.
