### ISSUE TITLE
Failed Gherkin tests do not report the correct error.

### ISSUE THREAD

**Issue by RandomNoun7** [pester/Pester#904]
When a test in a *.steps.ps1 file fails, the error reported in some cases is not the error the caused the test to fail, but an internal error handling the ErrorRecord object. To illustrate, create a feature file and a test file as specified below and run Invoke-Gherkin. The error you receive will not be expected error of $true <> $false, but ```ConvertTo-FailureLines : Cannot bind argument to parameter 'ErrorRecord' because it is null.```

bugrepro.feature
```cucumber
Feature: Reproduce Gherkin Bug
If a Pester Test fails in the Gherkin run mode, Gherkin.ps1 does not handle the error record properly and causes an internal failure, rather than reporting the real error that occurred.

    Scenario: Gherkin Bug
        Given A test to run
        Then Pester reports an internal error
```

bugrepro.steps.ps1
```powershell
Given "A test to run" {
}

Then "Pester reports an internal error" {
    $true | Should Be $false 
}
```
Bug Report Info
```
Pester version     : 4.0.8 C:\Program Files\WindowsPowerShell\Modules\Pester\4.0.8\Pester.psm1
PowerShell version : 5.1.15063.483
OS version         : Microsoft Windows NT 10.0.15063.0

```

**Comment by myriad90** [comment]
Seeing the same issue with same version of Pester. Basic assertion tests fail exactly as described in this bug

ConvertTo-FailureLines : Cannot bind argument to parameter 'ErrorRecord' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\Pester\4.0.8\Functions\Output.ps1:267 char:25
+                         ConvertTo-FailureLines |
+                         ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertTo-FailureLines], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,ConvertTo-FailureLines
