### ISSUE TITLE
Error when cleaning up Mocks defined outside of Describe, when running via Invoke-Pester

### ISSUE THREAD

**Issue by nohwnd** [pester/Pester#952]
```powershell
function f () {}
mock f {}
Describe 'd' {
    It 't' {}
}
```
It fails to cleanup properly when Mock is defined outside of Describe, when you run via Invoke-Pester. When you run via Invoke-Pester then `$script:pester` is populated before Describe is entered, and that is what the "you cannot run Mock outside of Pester tests" looks at. Then when the cleanup is done, the uppermost Describe tears down all the mocks, but keeps the entry in the mockTable (did not look too deep into that yet). And then the there is probably teardown after all Describes run, that picks up the entry from mockTable and tries to teardown the mock again.

```
Exception calling "Remove" with "4" argument(s): "Cannot find path 'Function:\83b18fa0-bcd8-4e09-865f-2429958f00bd' because it does not exist."
At C:\Program Files\WindowsPowerShell\Modules\Pester\4.1.0\Functions\Mock.ps1:757 char:9
+         $ExecutionContext.InvokeProvider.Item.Remove("Function:\$Comm ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ItemNotFoundException
 
Invoke-InMockScope : Exception calling "Remove" with "4" argument(s): "Cannot find path 'Function:\83b18fa0-bcd8-4e09-865f-2429958f00bd' because it does not exist."
At C:\Program Files\WindowsPowerShell\Modules\Pester\4.1.0\Functions\Mock.ps1:777 char:21
+ ...     $null = Invoke-InMockScope -SessionState $mock.SessionState -Scri ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-InMockScope], MethodInvocationException
    + FullyQualifiedErrorId : ItemNotFoundException,Invoke-InMockScope
```

**Comment by renehernandez** [comment]
@nohwnd I am going to take a look at this over the weekend

**Comment by nohwnd** [comment]
@renehernandez Great! That error is gonna be a slightly different because the mock functions are named `Pester___<guid>` now. There is also a function that removes all mocks before we start testing because we had problems mocking when the tests were aborted and no cleanup was run. In that case aliases stuck around pointing to mocks that we did not know about.

**Comment by renehernandez** [comment]
@nohwnd This bug is baffling :)!! I have spent quite sometime debugging it but I haven't found out the root cause yet as to why it happens.

A quick workaround, which I am submitting in the pull request is to check at https://github.com/pester/Pester/blob/master/Functions/Mock.ps1#L751 if the Function exists in the Provider before removing it.

For what I could gather while tackling this issue, the mock function is already gone by the time the `Exit-MockScope` function (called at https://github.com/pester/Pester/blob/master/Pester.psm1#L1141) actually tries to remove the function from the provider. Since the call is throwing an exception, the key will never get remove from the mock table, making the subsequent `Exit-MockScope` call (https://github.com/pester/Pester/blob/master/Pester.psm1#L1157) fail as well

**Comment by nohwnd** [comment]
@renehernandez that is quite possible. I will test it when I get to it 🙂

**Comment by renehernandez** [comment]
> @renehernandez that sounds like a reasonable explanation. I will test it when I get to it 🙂

@nohwnd Any updates on this? Is it OK as is or do you have any feedback?

**Comment by nohwnd** [comment]
@renehernandez nothing yet sorry. I was glad that I got to release the new version this weekend but did not get to anything else.
