### ISSUE TITLE
Get-ADGroupMember with ParameterFilter

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#973]
## 1. Provide a general summary of the issue in the Title above

We're trying to have two `Mocks`, one `Mock` that does a catch all with no `ParameterFilter` and one `Mock` that is only called when the group name matches the `ParameterFilter`.

## 2. Describe Your Environment

Pester version     : 4.1.1 C:\Program Files\WindowsPowerShell\Modules\Pester\4.1.1\Pester.psm1
PowerShell version : 5.1.14409.1012
OS version         : Microsoft Windows NT 6.2.9200.0

## 3. Expected Behavior

When `GroupB` is called, we would only like to see one result. When other groups are called, we want to see two results.

## 4.Current Behavior

The `ParameterFilter` is never matched in `test 2` below.

```powershell
Describe 'test' {
    Mock Get-ADGroupMember {
       [PSCustomObject]@{
            SamAccountName = 'bob'
        }
        [PSCustomObject]@{
            SamAccountName = 'dylan'
        }
    }
    Mock Get-ADGroupMember {
        [PSCustomObject]@{
            SamAccountName = 'mike'
        }
    } -ParameterFilter {$Identity -eq 'GroupB'}

    it 'test 1' {
        (Get-ADGroupMember -Identity 'GroupA' | Measure-Object).Count | Should -BeExactly 2
    }
    it 'test 2' {
       # Fails:
        (Get-ADGroupMember -Identity 'GroupB' | Measure-Object).Count | Should -BeExactly 1
    }
    it 'test 3' {
        (Get-ADGroupMember -Identity 'GroupC' | Measure-Object).Count | Should -BeExactly 2
    }
}
```

**Comment by nohwnd** [comment]
@DarkLite1 Sorry for the late reply, I was a bit busy in the past weeks. It works with normal function, so the problem here is the AD cmdlet itself. When you look at the type of the Identity parameter you can see that it has type `ADGroup` (more precisely `Microsoft.ActiveDirectory.Management.ADGroup` ). 

Using a simple test to compare it to a string, you can see that it matches when we force it to serialize to string (the left side of comparison dictates the type to be used for the comparison). 

```powershell
$identity = [Microsoft.ActiveDirectory.Management.ADGroup]"abc"

# true because Identity serializes to "abc" string
"$identity" -eq "abc" 
# true because we force the comparison to be done as string
"abc" -eq $identity  

# false because the adgroup object does not implement custom equality 
#checking, so we compare by reference, and that means we get false when 
#the objects are two different instances
$identity -eq [Microsoft.ActiveDirectory.Management.ADGroup]"abc" 

# false, because we convert "abc" into the ADGroup type, 
#and the same rules as in the previous case apply
$identity -eq "abc" 
```

As a side note if you are comparing to string, use `"$value"` or `[string]$value` to get the value the `-eq` operator will use. Do NOT use `.ToString()`, it likely won't give you accurate results, and in some cases it is locale dependent (which is only one of the reasons). See some examples when comparing datetime to a string:

```powershell
$d = Get-Date

#true, "$d" is 02/10/2018 15:37:10
"$d" -eq $d 
#true, ([string]$d) is 02/10/2018 15:37:10
([string]$d) -eq $d 

#false, the  ($d.ToString()) is 10.02.2018 15:37:10, but the other $d serializes to 02/10/2018 15:37:10
($d.ToString()) -eq $d 
```

So to fix your test simply change the filter to `{"$Identity" -eq 'GroupB'}` or `{'GroupB' -eq $Identity}`.

**Comment by DarkLite1** [comment]
Thank you very much @nohwnd, I fully understand it now. Couldn't get my head around it. Big thumbs up :)

**Comment by nohwnd** [comment]
@DarkLite1 no problem, it is a bit intricate. :) glad I could help you
