### ISSUE TITLE
Comment-based help for Should is useless...

### ISSUE THREAD

**Issue by Jaykul** [pester/Pester#998]
Can we please make the Synopsis for Should say:

```
... Please read ABOUT_SHOULD instead. We apologize for our lazyness.
```

And then, you know, switch to PlatyPS and generate the help for Should from the About_Should, because this is ridiculous 😉

**Comment by nohwnd** [comment]
No we can't because I am working on this in my free time, as anyone else. For little to no benefit, and very little credit. You are free to post a PR and implement the help the way you see fit. Or you could sponsor the development, and then we can talk about being lazy, and not doing our work properly. ;P

**Comment by Jaykul** [comment]
This response to my request is confusing. I can't tell if I should submit a PR to implement my suggestion, or just go away...

**Comment by nohwnd** [comment]
A PR :)

**Comment by it-praktyk** [comment]
@Jaykul, your remarks/opinions about the uselessness of help - in some places - of Pester documentation are OK. You have the right to your opinion. 

The words "our lazyness" used in your proposal were not fair.

Yes, we are open to any constructive help to update and maintain the code - especially we need help in the subject of Gherkin - improve a documentation, support our Community.

**Comment by it-praktyk** [comment]
I'm closing the current issue because it's covered by #720.
